### ISSUE TITLE
Tests: warning: ISO C90 does not support ‘long long’ [-Wlong-long]

### ISSUE THREAD

**Issue by notorand-it** [libuv/libuv#348] opened 2015-05-08 08:35 UTC
While running "make check" I get these warnings:
```
test/test-platform-output.c: In function ‘run_test_platform_output’:
test/test-platform-output.c:50:59: warning: ISO C90 does not support ‘long long’ [-Wlong-long]
   printf("uv_resident_set_memory: %llu\n", (unsigned long long) rss);
                                                           ^
test/test-platform-output.c:50:3: warning: ISO C90 does not support the ‘ll’ gnu_printf length modifier [-Wformat=]
   printf("uv_resident_set_memory: %llu\n", (unsigned long long) rss);
   ^
test/test-platform-output.c:65:25: warning: ISO C90 does not support ‘long long’ [-Wlong-long]
          (unsigned long long) rusage.ru_utime.tv_sec,
                         ^
test/test-platform-output.c:66:25: warning: ISO C90 does not support ‘long long’ [-Wlong-long]
          (unsigned long long) rusage.ru_utime.tv_usec);
                         ^
test/test-platform-output.c:66:10: warning: ISO C90 does not support the ‘ll’ gnu_printf length modifier [-Wformat=]
          (unsigned long long) rusage.ru_utime.tv_usec);
          ^
test/test-platform-output.c:66:10: warning: ISO C90 does not support the ‘ll’ gnu_printf length modifier [-Wformat=]
test/test-platform-output.c:68:25: warning: ISO C90 does not support ‘long long’ [-Wlong-long]
          (unsigned long long) rusage.ru_stime.tv_sec,
                         ^
test/test-platform-output.c:69:25: warning: ISO C90 does not support ‘long long’ [-Wlong-long]
          (unsigned long long) rusage.ru_stime.tv_usec);
                         ^
...
```
I presume a higher standard (-std= option) needs to be used at least for tests.

**Comment by kthelgason** [comment] 2016-05-07 11:49
I think this issue can be closed. It's a duplicate of #850

**Closed** 2016-05-07 19:33 UTC
Labels: test
