### ISSUE TITLE
Blocking stdin read on OSX in iojs and node 0.11 and 0.12 but not 0.10

### ISSUE THREAD

**Issue by secrettriangle** [libuv/libuv#340] opened 2015-05-02 20:28 UTC
See slap-editor/slap#156. [dtruss output](https://gist.github.com/secrettriangle/f45e83ed6e6ffe96605c) with reproduction steps on the bottom.

Possibly related: #304

**Comment by saghul** [comment] 2015-05-05 09:00
Duplicate of #304

**Closed by saghul** 2015-05-05 09:00 UTC
