### ISSUE TITLE
uv_getnameinfo returns an error if async, no error if sync

### ISSUE THREAD

**Issue by skypjack** [libuv/libuv#1406] opened 2017-07-07 08:12 UTC
Consider the following code:

```
#include <cassert>
#include "uv.h"

void async() {
    auto *loop = uv_default_loop();
    sockaddr_in saddr;
    uv_getnameinfo_t nameinfo;
    auto err = uv_ip4_addr("", 6667, &saddr);
    assert(err);
    uv_getnameinfo(loop, &nameinfo, +[](uv_getnameinfo_t *, int status, const char *, const char *) {
        // error detected
        assert(status);  
    }, reinterpret_cast<const sockaddr *>(&saddr), 0);
}
 
void sync() {
    auto *loop = uv_default_loop();
    sockaddr_in saddr;
    uv_getnameinfo_t nameinfo;
    auto err = uv_ip4_addr("", 6667, &saddr);
    assert(err);
    auto status = uv_getnameinfo(loop, &nameinfo, nullptr, reinterpret_cast<const sockaddr *>(&saddr), 0);
    // no error detected ?
    assert(status); // (1)
}
 
int main() {
    async();
    sync();
}
```

If you compile and run it, assert `(1)` fails.  
The expectation was that if I get an error as an invalid `status` when used in async mode, I should get an error as an invalid return value when used in sync mode.  
One could argue that I should stop the function as soon as I detect the error using `uv_ip4_addr` and that makes perfectly sense. Anyway the behavior of `uv_getnameinfo` is somehow inconsistent.

I noticed that it changed over time because of the tests of `uvw`. Until a couple of weeks ago this test works just fine (well, a similar one, I stripped out all the `uvw` stuff to open the issue). You can look at the [history on travis](https://travis-ci.org/skypjack/uvw) for more details.

---

Side note.  
It doesn't seem to be due to a change in `libuv`. The test worked just fine until a few weeks ago and simply fails since then. Today it doesn't work anymore even with older versions of `libuv`. That being said, even if the problem is due to the surrounding environment or to some other change in an external library to which `libuv` links, I guess it would worth giving to the users a consistent behavior both in async and sync mode.  
Here is the result of `./autogen.sh && ./configure` on my laptop:

```
+ libtoolize --copy
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
+ aclocal -I m4
+ autoconf
+ automake --add-missing --copy
configure.ac:38: installing './ar-lib'
configure.ac:25: installing './compile'
configure.ac:22: installing './config.guess'
configure.ac:22: installing './config.sub'
configure.ac:21: installing './install-sh'
configure.ac:21: installing './missing'
Makefile.am: installing './depcomp'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking if gcc supports -pedantic flag... yes
checking for gcc way to treat warnings as errors... -Werror
checking if gcc supports -fvisibility=hidden... yes
checking if gcc supports -g flag... yes
checking if gcc supports -std=gnu89 flag... yes
checking if gcc supports -Wall flag... yes
checking if gcc supports -Wextra flag... yes
checking if gcc supports -Wno-unused-parameter flag... yes
checking if gcc supports -Wstrict-prototypes flag... yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether make supports nested variables... (cached) yes
checking for dlopen in -ldl... yes
checking for kstat_lookup in -lkstat... no
checking for gethostbyname in -lnsl... yes
checking for perfstat_cpu in -lperfstat... no
checking for pthread_mutex_init in -lpthread... yes
checking for clock_gettime in -lrt... yes
checking for sendfile in -lsendfile... no
checking for socket in -lsocket... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking sys/ahafs_evProds.h usability... no
checking sys/ahafs_evProds.h presence... no
checking for sys/ahafs_evProds.h... no
checking for pkg-config... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating libuv.pc
config.status: creating Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
```
Host system is:

>Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 unknown unknown GNU/Linux

**Comment by bnoordhuis** [comment] 2017-07-07 21:40
Your `uv_getnameinfo_t` is located on the stack, it goes out of scope before `uv_getnameinfo()` is done with it.

Closing, not a libuv bug.

**Closed by bnoordhuis** 2017-07-07 21:40 UTC

**Comment by skypjack** [comment] 2017-07-08 19:37
@bnoordhuis The issue explicitly mentions the `sync` function, so I don't see how an error in the `async` one can influence it. That being said, my fault, I stripped too much from the original code. Anyway, as you can guess, unfortunately the problem is still there if you allocate correctly the instance of `uv_getnameinfo_t`.

**Comment by bnoordhuis** [comment] 2017-07-08 21:17
> The issue explicitly mentions the sync function, so I don't see how an error in the async one can influence it.

By the time sync() runs the program is already into UB territory.  There is no point discussing what is or isn't the expected behavior because it's by definition undefined.

**Comment by skypjack** [comment] 2017-07-08 22:07
Wait a moment: why `sync` is in UB? It is sync, so it's fine to allocate everything in the scope where I make the call. Right? Did you mean `async`? Otherwise I'm missing something.

**Comment by bnoordhuis** [comment] 2017-07-08 22:44
async() has UB and runs before sync().  Once a program exhibits UB, all bets are off.

A sufficiently smart and nasty compiler could replace it with a null program or one that spawns nasal demons (or nethack, like gcc used to do) and it would still be fully conforming to the standard.

**Comment by skypjack** [comment] 2017-07-09 05:25
Yeah, the blablabla was already clear. We were referring to different things, that's all. I was speaking about the reason of the UB, instead you were saying something like - once you have an UB, it's forever.  
Good, thank you anyway. At the end of the day, it was me that made a mistake in a test for `uvw` and has unexpected results. No UB, no loops that don't run. I was just catching the wrong event and I missed completely the error.  
A stupid, well buried typo.
