### ISSUE TITLE
zos,ci: threadpool_multiple_event_loops fails frequently

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2183] opened 2019-02-10 16:53 UTC
Example:
```
not ok 288 - threadpool_multiple_event_loops
# timeout
# Output from process `threadpool_multiple_event_loops`:
# CEE5205S The signal SIGTERM was received.
```
Some non-scientific statistics suggest it fails more often than it passes.

cc @libuv/zos

**Comment by bnoordhuis** [comment] 2019-02-10 16:53
@mhdawson aside: who should be in @libuv/zos now that @jBarz no longer works on it?

**Comment by mhdawson** [comment] 2019-02-11 14:17
Oops opened a duplicate https://github.com/nodejs/build/issues/1685.  @miladfarca is looking at this one.

**Comment by mhdawson** [comment] 2019-02-11 14:17
duplicate off [nodejs/build#1685](https://github.com/nodejs/build/issues/1685).

**Comment by cjihrig** [comment] 2019-04-11 16:25
I think this has been resolved. Closing out.

**Closed by cjihrig** 2019-04-11 16:25 UTC
Labels: test
