### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#4468] opened 2024-07-25 11:19 UTC
we have a bunch of commits and last release was 6 months ago. 

https://github.com/libuv/libuv/compare/v1.48.0...v1.x

**Comment by santigimeno** [comment] 2024-07-26 09:58
Sounds good. I can take care of it if needed.
Would love to add, if possible, https://github.com/libuv/libuv/pull/4376, or at least, the macos subset of it.

**Comment by santigimeno** [comment] 2024-08-06 20:33
I'm running https://ci.nodejs.org/view/libuv/job/libuv-in-node/244/ to see how it goes. Any thoughts on some PR's/Issues that should go in? @libuv/collaborators

**Comment by saghul** [comment] 2024-08-06 20:34
Probably https://github.com/libuv/libuv/pull/4491 can land.

**Comment by santigimeno** [comment] 2024-08-06 20:40
Those [aix](https://github.com/libuv/libuv/issues/4483) and [ibmi](https://github.com/libuv/libuv/issues/4484) test failures don't look great though not sure if they are all new. Don't know if they're being worked on. /cc @libuv/aix @libuv/ibmi

**Comment by panjf2000** [comment] 2024-08-07 00:42
I hope this can wait for #4330.

**Comment by saghul** [comment] 2024-08-07 08:35
> I hope this can wait for #4330.

It still contains unadressed feedback and cannot land as-is.

**Comment by richardlau** [comment] 2024-08-07 12:52
> Those [aix](https://github.com/libuv/libuv/issues/4483) and [ibmi](https://github.com/libuv/libuv/issues/4484) test failures don't look great though not sure if they are all new. Don't know if they're being worked on. /cc @libuv/aix @libuv/ibmi

These look to be issues in recently added tests. https://github.com/libuv/libuv/pull/4494 should fix them.

**Comment by santigimeno** [comment] 2024-08-14 22:49
I think all the pending PR's are merged now. Let me know if you think anything else needs to go in, otherwise I'll proceed with the release (tomorrow afternoon, most probably)

**Comment by vtjnash** [comment] 2024-08-15 00:38
This should be the last release with Win 8 support, and then that will be dropped in v1.x

**Comment by saghul** [comment] 2024-08-15 06:51
> This should be the last release with Win 8 support, and then that will be dropped in v1.x

Nice! Do you reckon we can remove some workarounds / cleanup as a result of that?

**Comment by santigimeno** [comment] 2024-08-15 10:33
libuv-in-node CI: https://ci.nodejs.org/view/libuv/job/libuv-in-node/245/

**Comment by santigimeno** [comment] 2024-08-15 12:13
So for the moment, the main issue I'm observing is related with `Node.js` `fs-watch` tests: https://ci.nodejs.org/job/node-test-commit-osx/60239/. It looks like a timing issue to me: apparently, on `macos` `uv_fs_event_t` API might report events generated immediately before calling `uv_fs_event_start()`. I've modified one of the failing tests to wait a few ms before start watching and confirms this. Were we aware of this behaviour in `macos`? Should we document it?. This [commit](https://github.com/libuv/libuv/commit/badecdca14d30fbfea655b7d4b18bdb4b3518c5d) makes the issue apparent in the Node.js tests but if this is the `macos` expected behavior, it seems something to be fixed in their tests. Thoughts?

**Comment by saghul** [comment] 2024-08-15 12:17
> Were we aware of this behaviour in `macos`?

Memory is fuzzy, but maybe?



> Should we document it?

I'd say so.

**Comment by santigimeno** [comment] 2024-08-15 14:41
> We have an open issue about it.

@vtjnash are you referring to  https://github.com/libuv/libuv/issues/3866 right?

Are we ok if I open a PR documenting the current limitation and we can pursue the real fix afterwards?

**Comment by clason** [comment] 2024-08-17 09:12
Current master is failing the Neovim tests on Windows and (intermittently) macOS; I'll bisect today. The offending commit must be after https://github.com/libuv/libuv/commit/4e310d0f90af29e699e2dedad5fa0dcee181a7cc.

**Comment by clason** [comment] 2024-08-17 11:04
Bisected to https://github.com/libuv/libuv/commit/727ee7237ede117c539a64258bf82a1b36b9991e (test hang on Windows).

**Comment by santigimeno** [comment] 2024-08-17 11:53
Release update status:
After looking at the nodejs ci run, the 2 main issues are:
- Failures due making io_uring SQPOLL disabled by default: I already have a patch for that.
- The fs-watch test failures on `macOS` I mentioned in https://github.com/libuv/libuv/issues/4468#issuecomment-2291159172.
To fix those I'll need to rewrite not a small number of tests in Node.js so I'm going to ask them whether they'll be ok with it before doing that. Yes, the  `macOS` behaviour was already there but the changes in this release made all those tests really flaky.

**Comment by clason** [comment] 2024-08-17 11:56
(It's not just Node; Neovim is affected by the `fs-watch` issue as well.)

**Comment by santigimeno** [comment] 2024-08-17 12:00
@clason can you be more specific on what issues you're observing?

**Comment by clason** [comment] 2024-08-17 12:03
Easiest if I link the failing tests:

* [macOS fswatch failures](https://github.com/neovim/neovim/actions/runs/10431268093/job/28890739255) (type of change is detected incorrectly), bisected to https://github.com/libuv/libuv/commit/9b3b61f606cbc4df1680a1aa08959c91023d99eb
* [Windows test hang](https://github.com/neovim/neovim/actions/runs/10431581693/job/28891392804) when waiting for stdin, bisected to https://github.com/libuv/libuv/commit/727ee7237ede117c539a64258bf82a1b36b9991e

**Comment by santigimeno** [comment] 2024-08-17 12:07
Thanks. The changes in  the ubsan commit should not affect fswatch at all. It's really strange. Could it be that test was already flaky? Maybe, something like what I was trying to explain in https://github.com/libuv/libuv/issues/4468#issuecomment-2291159172 was already happening?

**Comment by clason** [comment] 2024-08-17 12:08
Possibly, but the effect of the commit is reproducible. _Somehow_ it surfaced the issue for that specific change.

**Comment by santigimeno** [comment] 2024-08-17 12:12
So, if you revert https://github.com/libuv/libuv/commit/badecdca14d30fbfea655b7d4b18bdb4b3518c5d, does the test failure go away? If that's the case, before reverting it, could it be the problem in how the test is designed? I'd like to understand the problem better, as I think that commit was ok (I might be wrong of course)

**Comment by santigimeno** [comment] 2024-08-17 12:20
Ok, sorry, I though you were referring also to the actual commit that modified the `fs_events` logic.

**Comment by clason** [comment] 2024-08-17 12:22
(And to be clear, the Windows hang is much more worrying and a blocker for us.)

**Comment by vtjnash** [comment] 2024-08-17 13:02
Do you have some instructions on how to reproduce the build environment for the hang? I can look next week

**Comment by clason** [comment] 2024-08-17 13:06
Not really, sorry, since the hang is on Windows only (and hanging means no test failure to investigate).

**Comment by vtjnash** [comment] 2024-08-18 00:07
It doesn't need to be anything too specific, just any information on how to cmake this configuration on Windows and how to run this particular test would be helpful. Neovim is my main editor and I hope someday it gets packaged in Cygwin so I can use it when stuck doing Windows work.

**Comment by clason** [comment] 2024-08-18 10:14
Oh, OK. The cmake file for libuv is here: https://github.com/neovim/neovim/blob/master/cmake.deps/cmake/BuildLibuv.cmake (so pretty vanilla). The build instructions for Neovim itself are here: https://github.com/neovim/neovim/blob/master/BUILD.md#building-on-windows. It doesn't seem to be a specific test that hangs, so I'd start with just cloning the neovim repo and doing `make functionaltest` (which is what CI does).

You can run specific tests with
```
make functionaltest TEST_FILE=test/functional/core/startup_spec.lua
```
(which is one place I've seen hangs.

If you want to change the libuv commit to build against, edit [these lines](https://github.com/neovim/neovim/blob/33464189bc02b2555e26dc4e9f7b3fbbcdd02490/cmake.deps/deps.txt#L1-L2) (you can use a local path instead of an URL; this will skip the hash check, too).

**Comment by vtjnash** [comment] 2024-08-19 15:02
Okay, it looks like I just forgot that some programs will open pipes in the legacy (non-overlapped) mode, which forces IO on them to use less reliable syscalls to handle them. I think https://github.com/libuv/libuv/pull/4511 should restore the necessary code for handling this case, though I haven't yet run it with the neovim tests. In theory the same bug has always existed on unix too, but it is less common to encounter there, so it is not an issue for the neovim tests.

**Comment by clason** [comment] 2024-08-19 15:03
If there's a better way (that works cross-platform), we're all ears!

**Comment by vtjnash** [comment] 2024-08-19 15:16
I didn't actually figure out where the pipe was coming from, so I don't know where it got created, and it should be made to work in libuv regardless, but if it was from `uv_spawn`, setting the `UV_NONBLOCK_PIPE` whenever you know the target supports it (e.g. is a neovim or libuv subprocess) will improve performance and correctness of the stdio of the target.

**Comment by santigimeno** [comment] 2024-08-28 22:48
Hello. Unfortunately, I won't be able to move forward with the release. Multiple reasons:
- I've been very busy and didn't find the time.
- I think there's some PR's that still need to be merged: https://github.com/libuv/libuv/pull/4515 and maybe https://github.com/libuv/libuv/pull/4513.
- I'm going on holidays for a couple of weeks :partying_face: 

So, if somebody wants to pick this up, it would be great.
A couple of things I worked on so that the Node.js upgrade goes a bit more smoothly (in case some Node.js maintainer wants to do the upgrade there):
- https://github.com/nodejs/node/pull/54498 is approved but will need to be merged.
- The last 2 commits in https://github.com/santigimeno/node/commits/santi/io_uring_for_1.49.0/ will probably need to be added as well: https://github.com/santigimeno/node/commit/70c7d8a091b82fa00ddf1aa82838feefc5b6f6d8 and https://github.com/santigimeno/node/commit/c4758692c3597009e9a5615fd0e7d2a2973c567c

Otherwise I'll retake this once I return (around September 9th)

**Comment by clason** [comment] 2024-08-29 08:43
> Current master is failing the Neovim tests on Windows and (intermittently) macOS; I'll bisect today. The offending commit must be between [4e310d0](https://github.com/libuv/libuv/commit/4e310d0f90af29e699e2dedad5fa0dcee181a7cc) (good) and [9b3b61f](https://github.com/libuv/libuv/commit/9b3b61f606cbc4df1680a1aa08959c91023d99eb) (bad).

Just wanted to add that #4515 fixed the Neovim issues so things look good from our side. Thank you for the quick fixes, and sorry for holding up the release!

**Comment by saghul** [comment] 2024-08-29 09:14
I haven't done a release in a while, but I could give it a try next week.

**Comment by santigimeno** [comment] 2024-09-11 08:37
Update: I'm taking this up again. Stalled due to a `preadv` failure in the Node.js repo on `armv7l` which I plan to investigate as soon as I have access: https://github.com/nodejs/build/issues/3895#issuecomment-2340599679.

**Comment by johnsonjh** [comment] 2024-09-16 20:05
I'll try to look at #4533 before 1.48.1 (unless someone beats me to it).

**Comment by StefanStojanovic** [comment] 2024-09-24 09:22
Do you think the new libuv release will be ready for the next Node.js [major release](https://github.com/nodejs/Release/issues/1034)?

**Comment by santigimeno** [comment] 2024-09-24 09:28
I hope so. I plan to do it this week if nothing new comes up

**Comment by bnoordhuis** [comment] 2024-09-24 16:07
If not, no biggy. It's just a minor release, node can always upgrade afterwards.

**Comment by santigimeno** [comment] 2024-09-25 09:00
This is done: https://github.com/libuv/libuv/releases/tag/v1.49.0.

**Closed by santigimeno** 2024-09-25 09:00 UTC

**Comment by saghul** [comment] 2024-09-25 09:14
Thanks a lot Santi!
