### ISSUE TITLE
make check failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by tikhono** [libuv/libuv#2267] opened 2019-04-20 11:28 UTC
After running test `make check` I got 1 error:
```
not ok 72 - fs_fstat
# exit code 134
# Output from process `fs_fstat`:
# Assertion failed in test/test-fs.c on line 1259: s->st_birthtim.tv_nsec == 0 || s->st_birthtim.tv_nsec == t.st_ctim.tv_nsec
```
* **Version**: v1.x
* **Platform**: Linux 4.15.0-47-generic #50~16.04.1-Ubuntu x86_64 GNU/Linux

**Comment by mgaf** [comment] 2019-04-20 23:12
请帮帮我！

**Comment by bnoordhuis** [comment] 2019-04-21 07:31
Duplicate of #2235 but thanks for the report.

**Closed by bnoordhuis** 2019-04-21 07:31 UTC
Labels: duplicate

**Comment by tikhono** [comment] 2019-04-21 07:44
Sorry for duplication.
Hmm. There is something strange. I got one failed test. Then I ran some code that uses libuv and after I make yet another check all test passed.

**Comment by bnoordhuis** [comment] 2019-04-21 07:47
Yeah, it's very intermittently flaky; those are the most difficult to debug. I've seen it fail once or twice on our CI over the course of 100+ runs.

**Comment by vbashkirtsev** [comment] 2019-07-12 08:31
I have this test failing under QEMU emulation (not KVM). Apparently assumption that birth time is equivalent to the change time just because we just created the file does not hold ground. Birth time is slightly ahead of change time in my case. I believe that on loaded CI systems or in my case due to emulation it may be delayed just enough to have test failure. On dedicated CI systems issue does not manifest itself readily because it is likely for times to match.

**Comment by bnoordhuis** [comment] 2019-07-15 11:47
@vbashkirtsev Do you remember with what fs that was? I suppose it's possible some file systems don't set the birth and change time as a single atomic transaction.

**Comment by vbashkirtsev** [comment] 2019-07-15 12:11
ext4, mainline linux kernel 4.14.36. I do full system builds in QEMU and they are reproduceable. Same code persistently fails under full emulation and passes under KVM.

**Comment by bnoordhuis** [comment] 2019-07-15 19:44
Hm, okay. I think I checked ext4 and xfs when I filed #2235 and they both looked atomic. I rechecked just now ext4 and it's pretty much as I recall:

https://github.com/torvalds/linux/blob/0ecfebd2b52404ae0c54a878c872bb93363ada36/fs/ext4/ialloc.c#L1088-L1089

(Reproducing for posterity since GH doesn't seem to want to show the snippet inline.)
```c
inode->i_mtime = inode->i_atime = inode->i_ctime = current_time(inode);
ei->i_crtime = inode->i_mtime;
```
I'm inclined to believe there's something changing the ctime _after_ the inode is created but I'm at a loss as to what it is.

**Comment by vbashkirtsev** [comment] 2019-10-14 16:43
You're at right to be at a loss! :)

Believe it or not but I hit **TWO** QEMU TCG bugs in a few days! These bugs effectively prevented proper execution of the compiled code. But because bugs are subtle they don't manifest itself directly with some sort of log or dump. For example SSE instruction to right shift unsigned 32 bit value of 0 was expected to produce 0 as a result but in reality produced -1 (all bits set). Executing under KVM these instructions are executed by real CPU and thus work as expected.

I will re-try my build with latest QEMU master which now has fixes to these instructions and hopefully then libuv tests will succeed. May be I was barking at the wrong tree. Sorry...
