### ISSUE TITLE
handle EHOSTDOWN

### ISSUE THREAD

**Issue by Ognian** [libuv/libuv#195] opened 2015-02-10 12:56 UTC
This is a mirror of https://github.com/joyent/libuv/issues/1512 .
I'm not sure if you have handled this...

**Comment by rowild** [comment] 2015-02-19 11:19
This makes npm fail, when trying to install modules via npm.
Any solutions?

**Comment by bnoordhuis** [comment] 2015-02-19 14:39
Fixed by 3f910a0.

**Closed by bnoordhuis** 2015-02-19 14:39 UTC

**Comment by yunong** [comment] 2015-03-03 00:38
Has this been fixed? I'm running node v0.12 on Yosemite and am still seeing: 
```
Assertion failed: (0), function uv_err_name, file ../deps/uv/src/uv-common.c, line 75.
```

**Comment by saghul** [comment] 2015-03-03 09:43
@yunong yes, but the builtin libuv in Node hasn't been updated.

**Comment by vveerrgg** [comment] 2015-03-19 12:48
@saghul is there a workaround to Node to pass the fail?   I've been trying to figure out a way around this error.

**Comment by bnoordhuis** [comment] 2015-03-19 13:16
@vveerrgg You'd have to hand-upgrade the libuv that's bundled with joyent/node.

**Comment by saghul** [comment] 2015-03-19 15:16
@vveerrgg looks like Node 0.12.1 will contain the fix, but before that
there is nothing you can do other than manually patching as Ben suggested.

**Comment by vveerrgg** [comment] 2015-03-19 18:50
Thanks @saghul I'll give that a try.

**Comment by vveerrgg** [comment] 2015-03-19 19:10
for anyone else who might be in the same problem... looks like this set of commands will also update node (which may have been updated)

> sudo brew uninstall node
> brew update
> brew upgrade
> brew cleanup
> brew install node
> sudo chown -R *YourUsernameHere* /usr/local
> brew link --overwrite node
> sudo brew postinstall node

I kinda don't know *exactly* what I'm doing... but it seemed to fix the error for me.

**Comment by ibash** [comment] 2015-03-31 18:45
For posterity - it looks like Node 12.1 does *not* include the fix.

**Comment by saghul** [comment] 2015-03-31 19:25
I know, it's 12.2. which will.

**Comment by sjackman** [comment] 2015-04-04 18:32
I saw this error just now with node 0.12.2.
```
❯❯❯ npm install -g npm@latest
Assertion failed: (0), function uv_err_name, file ../deps/uv/src/uv-common.c, line 75.
❯❯❯ node --version
v0.12.2
❯❯❯ npm --version
2.7.5
```

**Comment by saghul** [comment] 2015-04-05 07:34
Can you inspect the core dump and check the error code?

**Comment by dwaligora** [comment] 2015-04-21 13:11
I got the same error still...

**Comment by saghul** [comment] 2015-04-21 14:06
What is the unmapped errno?

**Comment by dwaligora** [comment] 2015-04-21 14:16
node `0.12.12`:

> node: ../deps/uv/src/uv-common.c:75: uv_err_name: Assertion `0' failed.
Aborted

**Comment by saghul** [comment] 2015-04-21 14:31
Can you please paste the entire backtrace? Also, the unmapped code would be
the value of "err" when passed to that function.

Last, do you have a reliable way to reproduce it?

**Comment by mauvm** [comment] 2015-05-04 09:40
@vveerrgg Thanks, that also worked for me! I'd suggest others to use this slightly less intrusive version first though:

```bash
brew uninstall node
brew update
brew upgrade --all
brew cleanup
brew install node
```
