### ISSUE TITLE
xmrig-proxy: src/unix/core.c:233: uv__finish_close: Assertion `handle->flags & UV_CLOSING' failed.

### ISSUE THREAD

**Issue by alebeta90** [libuv/libuv#1743] opened 2018-02-13 22:14 UTC
Hello friends, 
im running xmrig-proxy and it is running but some times I got this error:

xmrig-proxy: src/unix/core.c:233: uv__finish_close: Assertion `handle->flags & UV_CLOSING' failed.

and obviously it is killing the program, normally the program is running few hours.

Libuv Package:

Package: libuv1
Priority: optional
Section: universe/libs
Installed-Size: 166
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Javascript Maintainers <pkg-javascript-devel@lists.alioth.debian.org>
Architecture: amd64
Version: 1.8.0-1
Depends: libc6 (>= 2.14)
Filename: pool/universe/libu/libuv1/libuv1_1.8.0-1_amd64.deb
Size: 57426
MD5sum: 9aabb25665c1b868260eb95d24507fb5
SHA1: 859f2d0613c4b9f49d735bbfbe1f3934372a5266
SHA256: 2854d5b9bd2ea549610f0a806636f36db44df2d93eb9b1bf5448545b881d53a7
Description-en: asynchronous event notification library - runtime library
 Libuv is the asynchronous library behind Node.js. Very similar to libevent or
 libev, it provides the main elements for event driven systems: watching and
 waiting for availability in a set of sockets, and some other events like timers
 or asynchronous messages. However, libuv also comes with some other extras
 like:
  * files watchers and asynchronous operations
  * a portable TCP and UDP API, as well as asynchronous DNS resolution
  * processes and threads management, and a portable inter-process
    communications mechanism, with pipes and work queues
  * a plugins mechanism for loading libraries dynamically
  * interface with external libraries that also need to access the I/O.
 .
 This package includes the dynamic library against which you can link
 your program.
Description-md5: 93573ad1b9de0529887627652f90b981
Multi-Arch: same
Homepage: https://github.com/libuv/libuv
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu

Linux version:
Linux virtualmachine01 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
OS: Ubuntu 16.04

Thanks and all the best

**Comment by alebeta90** [comment] 2018-02-14 08:17
Hello @cjihrig thanks for your answer,

Now I'm running:

Name        : libuv
Arch        : x86_64
Epoch       : 1
Version     : 1.10.2
Release     : 1.el7
Size        : 273 k
Repo        : installed
From repo   : epel
Summary     : Platform layer for node.js
URL         : http://libuv.org/
License     : MIT and BSD and ISC
Description : libuv is a new platform layer for Node. Its purpose is to abstract IOCP on
            : Windows and libev on Unix systems. We intend to eventually contain all platform
            : differences in this library.

this is a new version available for Centos using the EPEL repository. and we have the same problem.

**Comment by alebeta90** [comment] 2018-02-14 08:28
@cjihrig I see the last version is 1.19.x I will compile that version instead of using the one from EPEL Repo. And check how it behave

**Comment by bnoordhuis** [comment] 2018-02-14 09:39
You should report this to xmrig-proxy.  It's most likely not a bug in libuv but in the way xmrig-proxy uses libuv.

I'll close this out for now.  Can reopen if it does turn out to be a bug in libuv.

**Closed by bnoordhuis** 2018-02-14 09:39 UTC
