### ISSUE TITLE
linux: uv_cpu_info may abort when cpu offline during the procedure

### ISSUE THREAD

**Issue by legendecas** [libuv/libuv#3498] opened 2022-02-28 02:48 UTC
* **Version**: 1.43.0
* **Platform**: `Linux my-localmachine 4.9.151.x86_64 #1 SMP Tue Mar 12 19:10:26 CST 2019 x86_64 x86_64 x86_64 GNU/Linux`

`uv_cpu_info` read `/proc/stat` twice, first reading the CPU count, then `rewind` in the [`read_times`](https://github.com/libuv/libuv/blob/v1.x/src/unix/linux-core.c#L543) and read the detailed stats. This may be a problem when any of the CPU core is offline between those two reads: `read_times` [asserts](https://github.com/libuv/libuv/blob/v1.x/src/unix/linux-core.c#L590) that it read the same number of CPU before the rewind.

Expected behavior: `uv_cpu_info` should not abort when any of the CPU cores go offline.

**Comment by vtjnash** [comment] 2022-03-01 02:05
Duplicate of https://github.com/libuv/libuv/issues/2351

**Comment by bnoordhuis** [comment] 2022-03-06 09:44
Closing as duplicate.

**Closed by bnoordhuis** 2022-03-06 09:44 UTC
