### ISSUE TITLE
creating child processes under Windows inherits all handles

### ISSUE THREAD

**Issue by oktoberfest6** [libuv/libuv#3612] opened 2022-04-28 18:41 UTC
Hi,

under Windows uv_spawn() uses CreateProcessW() to start the child process.
The STARTUPINFO structure is populated with three handles (stdin/stdout/stderr) and the fifth argument of CreateProcessW (bInheritHandles) is set to true so that the child process inherits the handles.
The problem is that the child inherits all handles marked is inheritable, which can be problematic in some situations. You can find in sample.c a small piece of code to illustrate this issue.

To explicitely define which handles should be inherited we can use InitializeProcThreadAttributeList() and its related functions (see https://devblogs.microsoft.com/oldnewthing/20111216-00/?p=8873).

I have attached a modified version of process.c which uses these entry points to inherit only the stdin/stdout/stderr handles.

Will it be possible to modify uv_spawn so that the child process only inherits only the mentioned needed ? IMHO I don't find any reason to inherit other handles than the ones used for the input/output/error
[process.zip](https://github.com/libuv/libuv/files/8585492/process.zip)
.

**Comment by vtjnash** [comment] 2022-04-28 19:23
Duplicate of https://github.com/libuv/libuv/issues/1490

**Comment by vtjnash** [comment] 2022-04-28 19:24
Please submit code via PRs, and not zip files

**Closed by vtjnash** 2022-04-28 19:24 UTC
