### ISSUE TITLE
Assertion failed: new_time >= loop->time, file src\win\core.c, line 309 using expo

### ISSUE THREAD

**Issue by amoltivarekar** [libuv/libuv#2125] opened 2019-01-01 11:51 UTC
I am making application using react-native with Expo, but I'm facing above error. please give me the solution for this, thank you... 
![image](https://user-images.githubusercontent.com/19485287/50572663-b7487c00-0dea-11e9-9c87-e9684e5775ce.png)

**Comment by bnoordhuis** [comment] 2019-01-01 18:06
Closing as a duplicate of #1633. In short, not a libuv bug, libuv just reports that something is amiss with your system.

**Closed by bnoordhuis** 2019-01-01 18:06 UTC
