### ISSUE TITLE
Crash randomly in libuv

### ISSUE THREAD

**Issue by ssrlive** [libuv/libuv#1599] opened 2017-10-18 11:26 UTC
Hi friends,
I'm try to write a native proxy client for ShadowsocksR, integrating libuv into it. 
https://github.com/ShadowsocksR-Live/shadowsocksr-libev
It looks good in beginning, but it will crash randomly after running a few minutes.

The crash points often are uv_tcp_endgame and uv_stream_init.

Can anyone help?

* **Version**: https://github.com/libuv/libuv/tree/44b7c71035a4270510f642923604cc5fed93d20e
* **Platform**: Windows 10 and Visual Studio 2015, Linux 16.04 TLS and CLion 2017.2.1

**Comment by cjihrig** [comment] 2017-10-18 13:09
Can you please provide a reduced test case that reproduces the problem. Otherwise, you're basically asking us to debug your large application without any direction.

**Comment by ssrlive** [comment] 2017-10-18 13:37
I have send you an email. it contain configure information.

**Comment by ssrlive** [comment] 2017-10-18 13:49
After clone my project and recursive submodules, we can open it with VS2015 directly. And run it with parameter `-c config_file_path` , run chrome with SwitchySharp plugin and set proxy settings to socks host 127.0.0.1 and port 2080 with SOCKS v5 type. 

Watch a youtube video, then switch the resolution of the video. now it will crash. 

Please help me. 
Thanks.

**Comment by cjihrig** [comment] 2017-10-18 13:52
Sorry, I think there was some confusion. By "provide a reduced test case" I meant please submit a single file code snippet that relies on nothing but libuv and reproduces the problem. Running your app doesn't count as a reduced test case, and watching YouTube videos certainly doesn't 😄

**Comment by ssrlive** [comment] 2017-10-18 13:57
OK I will debug it myself. Thank you anyway.

**Comment by bnoordhuis** [comment] 2017-10-18 16:13
Closing then, can reopen if it turns out to be a bug in libuv.

**Closed by bnoordhuis** 2017-10-18 16:13 UTC
