### ISSUE TITLE
Serialport operations failing since introduction of IO_URING in v1.45

### ISSUE THREAD

**Issue by GazHank** [libuv/libuv#4101] opened 2023-07-22 11:29 UTC
* **Version**: 1.45 (since https://github.com/libuv/libuv/pull/3952 - also occurs on latest v1.x branch)
* **Platform**: 5.19.0-46-generic (Ubuntu 22.04.2 LTS)

I'm seeing these issues on x86 64bit, but other users have raised the issue on Raspberry Pi devices too.  Additionally, they also appear to be seeing issues in v6 kernels regardless of architecture (per https://github.com/serialport/node-serialport/issues/2656 and https://github.com/serialport/node-serialport/issues/2659)

The issue occurs if we:

1. Open a serial port
2. Write some data
3. Drain the port
4. Try to close the connection

The port fails to close.

For a sample set of code please refer to https://github.com/serialport/node-serialport/issues/2656 "steps to reproduce".

I can disable the issue if I change the linux.c file:

https://github.com/libuv/libuv/blob/d09441ca03e399fe641da88624c8ea0476967187/src/unix/linux.c#L434-L435

Excluding my kernel version number and recompile the library causes the operations work as expected.  I should also note that setting the environment variable `UV_USE_IO_URING=0` does not have any affect at all.

**Comment by santigimeno** [comment] 2023-07-22 11:49
Yes, kernel 5.19.x doesn't work and has the same CLOSE bug https://github.com/nodejs/docker-node/issues/1912#issuecomment-1646333970. Probably that's going to happen for most of non LTS kernel lines.

**Comment by GazHank** [comment] 2023-07-22 13:17
Thanks for the speedy response @santigimeno

**Comment by bnoordhuis** [comment] 2023-07-22 14:51
The 5.x kernels seem to have all kinds of bug. Maybe we should just move the baseline to 6.x?

**Comment by bnoordhuis** [comment] 2023-07-22 14:53
Oh, I see one of the node-serialport bug reports is against 6.1... then maybe we should disable io_uring and revisit in a year or two? I don't fancy debugging a long tail of kernel bugs and neither do most libuv users, I assume.

**Comment by santigimeno** [comment] 2023-07-23 18:13
I've been looking a bit into it, and have a simple reproducer in C using liburing.
<details>
<summary>

```
Liburing Example
```

</summary>

```
#include <stdio.h>
#include <fcntl.h>
#include <liburing.h>
#include <unistd.h>

#define BUF_SIZE 1024

int main() {
    int ret;
    struct io_uring ring;
    char buffer[BUF_SIZE];

    // Initialize io_uring instance
    if (io_uring_queue_init(16, &ring, 0) < 0) {
        perror("io_uring_queue_init");
        return 1;
    }

    // Open the file /dev/pts/2 with the specified flags
    int fd = open("/dev/pts/2", O_RDWR | O_NOCTTY | O_NONBLOCK | O_SYNC | O_CLOEXEC, 0);
    if (fd < 0) {
        perror("open");
        io_uring_queue_exit(&ring);
        return 1;
    }

    // Prepare the read operation
    struct io_uring_sqe* sqe = io_uring_get_sqe(&ring);
    if (!sqe) {
        perror("io_uring_get_sqe");
        io_uring_queue_exit(&ring);
        return 1;
    }
    io_uring_prep_read(sqe, fd, buffer, BUF_SIZE, 0);

    // Submit the read operation
    io_uring_submit(&ring);

    // Closing after submiting the READ op doesn't actually close the file description as there must be another file descriptor pointing to it ??
    close(fd);

    // Wait for completion
    struct io_uring_cqe* cqe;
    ret = io_uring_wait_cqe(&ring, &cqe);
    if (ret < 0) {
        perror("io_uring_wait_cqe");
        io_uring_queue_exit(&ring);
        return 1;
    }

    // Check if the operation completed successfully
    if (cqe->res < 0) {
        fprintf(stderr, "Read error: %d\n", cqe->res);
        io_uring_queue_exit(&ring);
        return 1;
    }

    // Print the data read from the file
    printf("Data read from /dev/pts/2: %s\n", buffer);

    // Release the completion queue entry
    io_uring_cqe_seen(&ring, cqe);

    // Clean up io_uring
    io_uring_queue_exit(&ring);

    return 0;
}

```

</details>

It seems to me that the issue is that after submitting the READV iouring request on a file descriptor, the program calls `close(fd)` and expects the iouring read operation to return, which it doesn't. My guess is that the iouring op holds a reference to the file description which prevents it from actually closing it.

The original issue example works when using libuv without iouring because reading from a non-blocking serial port without data, directly returns `EAGAIN` which prevents the `uv_fs_t` read request to complete and not to block the loop.

**Comment by bnoordhuis** [comment] 2023-07-29 18:16
Santi, do you have an opinion on disabling/removing io_uring? I lean towards stability over performance but I'm open to being persuaded otherwise.

**Comment by santigimeno** [comment] 2023-07-29 22:16
Yeah, I have opinions:
- If we're only talking about these serialport issues, I would say no. I think this [first issue is not an io_uring bug but a feature](https://github.com/serialport/node-serialport/issues/2656#issuecomment-1653399372) and I think it should / can be solved in serialport itself. Also, I've started looking into [the second issue](https://github.com/serialport/node-serialport/issues/2659) and also it doesn't seem io_uring related either: the CPU usage goes very high because one of the threads is not consuming a `EPOLLIN` event:
```
[pid 15168] epoll_pwait(17, [{events=EPOLLIN, data={u32=18, u64=18}}], 1024, 2273, NULL, 8) = 1                                                                                                                      
[pid 15168] epoll_pwait(17, [], 1024, 0, NULL, 8) = 0                                                                                                                                                                
[pid 15168] epoll_pwait(17, [{events=EPOLLIN, data={u32=18, u64=18}}], 1024, 2271, NULL, 8) = 1                                                                                                                      
[pid 15168] epoll_pwait(17, [], 1024, 0, NULL, 8) = 0                                                                                                                                                                
[pid 15168] epoll_pwait(17, [{events=EPOLLIN, data={u32=18, u64=18}}], 1024, 2239, NULL, 8) = 1                                                                                                                      
[pid 15168] epoll_pwait(17, [], 1024, 0, NULL, 8) = 0                                                                                                                                                                
[pid 15168] epoll_pwait(17, [{events=EPOLLIN, data={u32=18, u64=18}}], 1024, 2238, NULL, 8) = 1                                                                                                                      
[pid 15168] epoll_pwait(17, [], 1024, 0, NULL, 8) = 0                                                     
[pid 15168] epoll_pwait(17, [{events=EPOLLIN, data={u32=18, u64=18}}], 1024, 2206, NULL, 8) = 1                                                                                                                      
[pid 15168] epoll_pwait(17, [], 1024, 0, NULL, 8) = 0                                                                                                                                                                
[pid 15168] epoll_pwait(17, [{events=EPOLLIN, data={u32=18, u64=18}}], 1024, 2205, NULL, 8) = 1                                                                                                                      
[pid 15168] epoll_pwait(17, [], 1024, 0, NULL, 8) = 0                                                     
[pid 15168] epoll_pwait(17, [{events=EPOLLIN, data={u32=18, u64=18}}], 1024, 2173, NULL, 8) = 1                                                                                                                      
[pid 15168] epoll_pwait(17, [], 1024, 0, NULL, 8) = 0                                                                                                                                                                
[pid 15168] epoll_pwait(17, [{events=EPOLLIN, data={u32=18, u64=18}}], 1024, 2172, NULL, 8) = 1
```
could that be a libuv issue: yes, but most likely is a serialport issue too. Still have to look into it a bit more.

- On the other hand the thing that worries me more is stuff like [this](https://github.com/nodejs/docker-node/issues/1912#issuecomment-1646333970): people using non lts kernel versions, which won't receive io_uring fixes, or people using lts kernel versions but not willing or being able to update to a more stable one. For the latter I'm not so concerned as there are not so many of those lines and we can more or less establish which version ranges we support. For the former is going to be a lot of pain and not worth our time. One option could be only allow io_uring in LTS kernel versions, at least until io_uring really stabilizes.

- In general, I feel io_uring is working pretty well with not so many bug reports after the normal initial hiccups. Yes, it's a new technology and takes a bit of time to discern whether it's an actual io_uring issue or not, but to take such a drastic decision we should actually have proof the io_uring is the culprit.

**Comment by cjihrig** [comment] 2023-07-29 23:00
This might be a far fetched idea, so sorry in advance. What if we introduced an API for enabling/disabling more experimental features at runtime. Something like `uv_config_enable(UV_IO_URING)`. The API wouldn't be strictly tied to io_uring since we could add more flags in the future. Once a feature is considered stable enough, the flag used for that feature could become a noop.

**Comment by bnoordhuis** [comment] 2023-07-30 08:14
I don't think that helps runtimes like node or julia because, while they're the direct downstream users, the real downstream users are the applications running on the runtime, and they're too far removed to make a well-informed decision.

(I mean, look at how many people blindly copy `NODE_TLS_REJECT_UNAUTHORIZED=0` answers off SO, and that's for something the average programmer hopefully understands is a dumb idea.)

Santi's suggestion of enabling io_uring only on LTS kernels seems like a good approach in principle although I'm unsure how you recognize such kernels in practice.

**Comment by santigimeno** [comment] 2023-07-30 08:55
> I'm unsure how you recognize such kernels in practice.

There you go: https://kernel.org/ with their EOL date

**Comment by bnoordhuis** [comment] 2023-07-30 09:16
Right, that's mainline LTS but I think we'll also need to include distro LTS kernels. I can make an educated guess about Debian and RHEL but I'd have to read up on e.g. SUSE's maintenance policy.

**Comment by bnoordhuis** [comment] 2023-10-28 10:54
We have an impressively long and varied kernel blacklist now so I think this can be closed. If you still experience problems with v1.46.0, then please retest with the upcoming v1.47.0 release.

**Closed by bnoordhuis** 2023-10-28 10:54 UTC
