### ISSUE TITLE
udp_multicast_join test failed

### ISSUE THREAD

**Issue by wedobetter** [libuv/libuv#3913] opened 2023-02-24 10:07 UTC
* **Version**: v1.44.2
* **Platform**: Darwin macbook.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64

While running `make check`

```bash
exit code 6
Output from process `udp_multicast_join`:
Assertion failed in test/test-udp-multicast-join.c on line 131: r == 0
```

FAIL: test/run-tests
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues

**Comment by vtjnash** [comment] 2023-02-24 16:26
Duplicate of https://github.com/libuv/libuv/issues/3849?

**Comment by bnoordhuis** [comment] 2023-03-06 11:47
Closing, no follow-up (and likely a duplicate.)

**Closed by bnoordhuis** 2023-03-06 11:47 UTC
