### ISSUE TITLE
timeout of io poll is not right in some case

### ISSUE THREAD

**Issue by coderzh** [libuv/libuv#2901] opened 2020-07-01 13:09 UTC
* **Version**: v1.x
* **Platform**: all

```cpp
#include <stdio.h>
#include <unistd.h>
#include <uv.h>

uv_loop_t *loop;
uv_timer_t my_timer;
int count = 0;

static void on_timer(uv_timer_t* handle) {
    uv_timeval64_t tv;
    uv_gettimeofday(&tv);
    printf("on timer %lld\n", tv.tv_sec);
    sleep(2);
    if (count++ > 10) {
        uv_timer_stop(handle);
    }
}

int main(int argc, char **argv) {
    loop = uv_default_loop();
    uv_timer_init(loop, &my_timer);
    uv_timer_start(&my_timer, on_timer, 0, 2000);

    while (uv_run(loop, UV_RUN_ONCE)) {
        printf("uv_run\n");
    }
    return 0;
}
```

expect `on_timer` be called every 2 seconds even if on_timer itself costs 2 seconds, but the real outputs:

```
on timer 1593606697
on timer 1593606701
uv_run
on timer 1593606703
on timer 1593606707
uv_run
on timer 1593606709
on timer 1593606713
uv_run
on timer 1593606715
on timer 1593606719
uv_run
on timer 1593606721
on timer 1593606725
uv_run
on timer 1593606727
on timer 1593606731
```

on timer be called every 4(2+2) seconds and 2 seconds.  (2 seconds for the sleep, 2 seconds for the io poll wait.)

when I change sleep(2) to sleep(1), the outputs:

```
on timer 1593607862
on timer 1593607865
uv_run
on timer 1593607867
uv_run
on timer 1593607869
uv_run
on timer 1593607871
uv_run
on timer 1593607873
uv_run
on timer 1593607875
uv_run
on timer 1593607877
uv_run
on timer 1593607879
uv_run
on timer 1593607881
uv_run
on timer 1593607883
uv_run
on timer 1593607885
```

the second on timer is 3 seconds after the first one, after that, it called every 2 seconds(expected).

when I reviewed the uv source code, I found that in `uv_run`

```cpp
while (r != 0 && loop->stop_flag == 0) {
    uv__update_time(loop);
    uv__run_timers(loop);
    ran_pending = uv__run_pending(loop);
    uv__run_idle(loop);
    uv__run_prepare(loop);

    timeout = 0;
    if ((mode == UV_RUN_ONCE && !ran_pending) || mode == UV_RUN_DEFAULT)
      timeout = uv_backend_timeout(loop);

    uv__io_poll(loop, timeout);
```

the timeout calculated by `uv_backend_timeout` is not right cause by the `loop->time` is not be updated after `uv__run_timers`.

If I call `uv__update_time(loop);` before `timeout = uv_backend_timeout(loop);` , it looks works.

```cpp
    if ((mode == UV_RUN_ONCE && !ran_pending) || mode == UV_RUN_DEFAULT) {
      uv__update_time(loop);  // update loop->time before uv_backend_timeout
      timeout = uv_backend_timeout(loop);
    }
``` 

and outputs what expected:

```
on timer 1593608538
on timer 1593608540
uv_run
on timer 1593608542
on timer 1593608544
uv_run
on timer 1593608546
on timer 1593608548
uv_run
on timer 1593608550
on timer 1593608552
uv_run
on timer 1593608554
on timer 1593608556
uv_run
on timer 1593608558
on timer 1593608560
```

every 2 seconds on timer calls.

should update `loop->time` before calculate the timeout?

**Comment by bnoordhuis** [comment] 2020-07-01 14:11
Thanks for the bug report but the answer is no. From docs/src/timer.rst:

> Does not update the event loop's concept of "now". See :c:func:`uv_update_time` for more information.

I'm closing the issue but I can move it to libuv/help if you have follow-up questions.

**Closed by bnoordhuis** 2020-07-01 14:11 UTC

**Comment by bnoordhuis** [comment] 2020-07-01 14:13
And from the section on `uv_timer_set_repeat()` in the same document:

> The timer will be scheduled to run on the given interval, regardless of the callback execution duration, and will follow normal timer semantics in the case of a time-slice overrun.

In other words, the behavior you observe is expected.

**Comment by coderzh** [comment] 2020-07-01 15:15
Sad, but the behavior is not my expect.

**Comment by coderzh** [comment] 2020-07-01 15:34
The behavior is so abnormal. When I scheduled a timer N milliseconds interval, callback execution duration is longer than N milliseconds(for example M milliseconds), the callback will be triggered every N+M milliseconds and N seconds alternately.

**Comment by bnoordhuis** [comment] 2020-07-02 06:51
You don't have to like it but you'll have to learn to live with it - libuv has always worked this way and it's not going to change. Call `uv_update_time(loop)` at the end of your callback.

**Comment by coderzh** [comment] 2020-07-02 12:32
> You don't have to like it but you'll have to learn to live with it - libuv has always worked this way and it's not going to change. Call `uv_update_time(loop)` at the end of your callback.

Call `uv_update_time(loop)` at the end of your callback will cause `uv__run_timers` infinite when callback execution duration always longer than the interval.

```cpp
void uv__run_timers(uv_loop_t* loop) {
  struct heap_node* heap_node;
  uv_timer_t* handle;

  for (;;) {
    heap_node = heap_min(timer_heap(loop));
    if (heap_node == NULL)
      break;

    handle = container_of(heap_node, uv_timer_t, heap_node);
    if (handle->timeout > loop->time)  // <-- never break when callback execution duration always longer than the interval, if uv_update_time at the end of callback 
      break;

    uv_timer_stop(handle);
    uv_timer_again(handle);
    handle->timer_cb(handle);
  }
}
```

**Comment by bnoordhuis** [comment] 2020-07-02 13:55
I kind of understand what you're saying but I can't reproduce it. Below is a test case, can you try it out and/or modify it to demonstrate the behavior you're seeing?
<details>

```diff
diff --git a/test/test-list.h b/test/test-list.h
index 6146434e..1171f0cd 100644
--- a/test/test-list.h
+++ b/test/test-list.h
@@ -208,6 +208,7 @@ TEST_DECLARE   (sys_error)
 TEST_DECLARE   (timer)
 TEST_DECLARE   (timer_init)
 TEST_DECLARE   (timer_again)
+TEST_DECLARE   (timer_overrun)
 TEST_DECLARE   (timer_start_twice)
 TEST_DECLARE   (timer_order)
 TEST_DECLARE   (timer_huge_timeout)
@@ -766,6 +767,7 @@ TASK_LIST_START
   TEST_ENTRY  (timer)
   TEST_ENTRY  (timer_init)
   TEST_ENTRY  (timer_again)
+  TEST_ENTRY  (timer_overrun)
   TEST_ENTRY  (timer_start_twice)
   TEST_ENTRY  (timer_order)
   TEST_ENTRY  (timer_huge_timeout)
diff --git a/test/test-timer-again.c b/test/test-timer-again.c
index e87d2edf..0af0ccd9 100644
--- a/test/test-timer-again.c
+++ b/test/test-timer-again.c
@@ -139,3 +139,36 @@ TEST_IMPL(timer_again) {
   MAKE_VALGRIND_HAPPY();
   return 0;
 }
+
+
+static void timer1_cb(uv_timer_t* timer1) {
+  uv_sleep(10);
+  uv_update_time(timer1->loop);
+}
+
+
+static void timer2_cb(uv_timer_t* timer2) {
+  uv_timer_t* timer1;
+
+  timer1 = timer2->data;
+  uv_close((uv_handle_t*) timer1, NULL);
+  uv_close((uv_handle_t*) timer2, NULL);
+}
+
+
+TEST_IMPL(timer_overrun) {
+  uv_timer_t timer1;
+  uv_timer_t timer2;
+
+  timer1.data = &timer2;
+  timer2.data = &timer1;
+
+  ASSERT_EQ(0, uv_timer_init(uv_default_loop(), &timer1));
+  ASSERT_EQ(0, uv_timer_start(&timer1, timer1_cb, 1, 1));
+  ASSERT_EQ(0, uv_timer_init(uv_default_loop(), &timer2));
+  ASSERT_EQ(0, uv_timer_start(&timer2, timer2_cb, 5, 0));
+  ASSERT_EQ(0, uv_run(uv_default_loop(), UV_RUN_DEFAULT));
+
+  MAKE_VALGRIND_HAPPY();
+  return 0;
+}
```

</details>

**Comment by coderzh** [comment] 2020-07-03 03:27
Please try this case, the idle callback will never run second times, and the timer will never be stopped.

```diff
diff --git a/test/test-list.h b/test/test-list.h
index 6146434e..1171f0cd 100644
--- a/test/test-list.h
+++ b/test/test-list.h
@@ -208,6 +208,7 @@ TEST_DECLARE   (sys_error)
 TEST_DECLARE   (timer)
 TEST_DECLARE   (timer_init)
 TEST_DECLARE   (timer_again)
+TEST_DECLARE   (timer_overrun)
diff --git a/test/test-list.h b/test/test-list.h
index 6146434e..1171f0cd 100644
--- a/test/test-list.h
+++ b/test/test-list.h
@@ -208,6 +208,7 @@ TEST_DECLARE   (sys_error)
 TEST_DECLARE   (timer)
 TEST_DECLARE   (timer_init)
 TEST_DECLARE   (timer_again)
+TEST_DECLARE   (timer_overrun)
 TEST_DECLARE   (timer_start_twice)
 TEST_DECLARE   (timer_order)
 TEST_DECLARE   (timer_huge_timeout)
@@ -766,6 +767,7 @@ TASK_LIST_START
   TEST_ENTRY  (timer)
   TEST_ENTRY  (timer_init)
   TEST_ENTRY  (timer_again)
+  TEST_ENTRY  (timer_overrun)
   TEST_ENTRY  (timer_start_twice)
   TEST_ENTRY  (timer_order)
   TEST_ENTRY  (timer_huge_timeout)
diff --git a/test/test-timer-again.c b/test/test-timer-again.c
index e87d2edf..e0766c63 100644
--- a/test/test-timer-again.c
+++ b/test/test-timer-again.c
@@ -139,3 +139,34 @@ TEST_IMPL(timer_again) {
   MAKE_VALGRIND_HAPPY();
   return 0;
 }
+
+static void timer1_cb(uv_timer_t* timer1) {
+  uv_sleep(10);
+  uv_update_time(timer1->loop);
+}
+
+int64_t counter = 0;
+
+void wait_for_a_while(uv_idle_t* handle) {
+    counter++;
+    if (counter >= 10) {
+        uv_idle_stop(handle);
+        uv_timer_t* timer1;
+        timer1 = handle->data;
+        uv_close((uv_handle_t*) timer1, NULL);
+    }
+}
+
+TEST_IMPL(timer_overrun) {
+  uv_timer_t timer1;
+  uv_idle_t idler;
+  idler.data = &timer1;
+  uv_idle_init(uv_default_loop(), &idler);
+  uv_idle_start(&idler, wait_for_a_while);
+  ASSERT_EQ(0, uv_timer_init(uv_default_loop(), &timer1));
+  ASSERT_EQ(0, uv_timer_start(&timer1, timer1_cb, 1, 1));
+  ASSERT_EQ(0, uv_run(uv_default_loop(), UV_RUN_DEFAULT));
+
+  MAKE_VALGRIND_HAPPY();
+  return 0;
+}
```
