### ISSUE TITLE
Segmentation Fault (SIGSEGV)

### ISSUE THREAD

**Issue by pszemus** [libuv/libuv#1306] opened 2017-04-13 10:29 UTC
Hello
I'm building a multithreaded async gRPC service that uses a libuv loop as a singleton (I think I've done proper synchornization with mutexes), and under a heavy load it quits with SIGSEGV.
GDB backtrace:
```
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x7f9274ecd700 (LWP 22877) 0x00007f92798c8765 in raise () from /lib64/libc.so.6
  2    Thread 0x7f927bc639c0 (LWP 22875) 0x00007f9279c62bd0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  3    Thread 0x7f9273ecb700 (LWP 22879) 0x00007f9279997307 in epoll_pwait () from /lib64/libc.so.6
  4    Thread 0x7f92726c8700 (LWP 22883) 0x0000000000418f55 in grpc::CompletionQueue::Next (this=0xdb9c90, tag=0x7f92726c7bb0, ok=0x7f92726c7baf) at libs/include/grpc++/impl/codegen/completion_queue.h:151
  5    Thread 0x7f926bfff700 (LWP 22880) 0x00007f9279997307 in epoll_pwait () from /lib64/libc.so.6
  6    Thread 0x7f9271ec7700 (LWP 22884) 0x00007f9279997307 in epoll_pwait () from /lib64/libc.so.6
  7    Thread 0x7f92746cc700 (LWP 22878) 0x00007f927a41faf0 in __dynamic_cast () from /lib64/libstdc++.so.6
  8    Thread 0x7f92736ca700 (LWP 22881) 0x00007f9279997307 in epoll_pwait () from /lib64/libc.so.6
  9    Thread 0x7f92716c6700 (LWP 22885) 0x00007f9279997307 in epoll_pwait () from /lib64/libc.so.6
  10   Thread 0x7f9272ec9700 (LWP 22882) 0x00007f9279997307 in epoll_pwait () from /lib64/libc.so.6
  11   Thread 0x7f92756ce700 (LWP 22876) 0x00007f9279997307 in epoll_pwait () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f92798c8765 in raise () from /lib64/libc.so.6
#1  0x00007f92798ca483 in abort () from /lib64/libc.so.6
#2  0x00007f927b2cff11 in MagickPanicSignalHandler () from /lib64/libGraphicsMagick-Q16.so.3
#3  <signal handler called>
#4  heap_remove (less_than=0x5a7f20 <timer_less_than>, node=0x7fffb5bef848, heap=0x874a88 <default_loop_struct+520>) at ./src/heap-inl.h:196
#5  uv_timer_stop (handle=0x7fffb5bef7e0) at src/unix/timer.c:97
#6  0x00000000005a84ac in uv__run_timers (loop=loop@entry=0x874880 <default_loop_struct>) at src/unix/timer.c:163
#7  0x00000000005a0eac in uv_run (loop=0x874880 <default_loop_struct>, mode=UV_RUN_DEFAULT) at src/unix/core.c:343
#8  0x000000000041465a in imageresizer::engine::FileDownloader::StartLoop (this=0x7fffb5bef7a0) at src/engine/FileDownloader.cpp:103
#9  0x0000000000416360 in std::__invoke_impl<void, void (imageresizer::engine::FileDownloader::* const&)(), imageresizer::engine::FileDownloader*>(std::__invoke_memfun_deref, void (imageresizer::engine::FileDownloader::* const&)(), imageresizer::engine::FileDownloader*&&) (__f=@0xdbf1c0: (void (imageresizer::engine::FileDownloader::*)(imageresizer::engine::FileDownloader * const)) 0x41459c <imageresizer::engine::FileDownloader::StartLoop()>, 
    __t=<unknown type in /opt/WP/imageresizer-worker/dist/Debug/GNU-Linux/imageresizer-worker, CU 0x16b92, DIE 0x213f3>) at /usr/include/c++/6.3.1/functional:227
#10 0x00000000004162ed in std::__invoke<void (imageresizer::engine::FileDownloader::* const&)(), imageresizer::engine::FileDownloader*>(void (imageresizer::engine::FileDownloader::* const&)(), imageresizer::engine::FileDownloader*&&) (
    __fn=@0xdbf1c0: (void (imageresizer::engine::FileDownloader::*)(imageresizer::engine::FileDownloader * const)) 0x41459c <imageresizer::engine::FileDownloader::StartLoop()>, 
    __args#0=<unknown type in /opt/WP/imageresizer-worker/dist/Debug/GNU-Linux/imageresizer-worker, CU 0x16b92, DIE 0x213f3>) at /usr/include/c++/6.3.1/functional:251
#11 0x000000000041629e in std::_Mem_fn_base<void (imageresizer::engine::FileDownloader::*)(), true>::operator()<imageresizer::engine::FileDownloader*>(imageresizer::engine::FileDownloader*&&) const (this=0xdbf1c0, 
    __args#0=<unknown type in /opt/WP/imageresizer-worker/dist/Debug/GNU-Linux/imageresizer-worker, CU 0x16b92, DIE 0x213f3>) at /usr/include/c++/6.3.1/functional:604
#12 0x0000000000416269 in std::_Bind_simple<std::_Mem_fn<void (imageresizer::engine::FileDownloader::*)()> (imageresizer::engine::FileDownloader*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0xdbf1b8)
    at /usr/include/c++/6.3.1/functional:1391
#13 0x00000000004161b7 in std::_Bind_simple<std::_Mem_fn<void (imageresizer::engine::FileDownloader::*)()> (imageresizer::engine::FileDownloader*)>::operator()() (this=0xdbf1b8) at /usr/include/c++/6.3.1/functional:1380
#14 0x0000000000416196 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (imageresizer::engine::FileDownloader::*)()> (imageresizer::engine::FileDownloader*)> >::_M_run() (this=0xdbf1b0)
    at /usr/include/c++/6.3.1/thread:196
#15 0x00007f927a44d5cf in ?? () from /lib64/libstdc++.so.6
#16 0x00007f9279c5d5ca in start_thread () from /lib64/libpthread.so.0
#17 0x00007f92799970ed in clone () from /lib64/libc.so.6
```
That `MagickPanicSignalHandler` in frame #2 is a GraphicsMagick signal handler.
libuv version: 1.11.0 (tag v1.11.0 from GitHub repo)

I'm asking for help to debug that issue.
Thanks!

**Comment by bnoordhuis** [comment] 2017-04-13 11:17
> I think I've done proper synchornization with mutexes

Are you manipulating the same event loop or handles from the same event loop from more than one thread?

**Comment by pszemus** [comment] 2017-04-13 13:17
If I understand the way libuv loop works correctly - it doesn't spawn any new threads.
All threads that my service spawns are manipulating libcurl multi handle and **not** libuv loop nor its handles.

**Comment by bnoordhuis** [comment] 2017-04-13 16:48
Those multi handles are implemented in terms of libuv handles?  If yes, you can only manipulate them from a single thread.

**Comment by bnoordhuis** [comment] 2017-04-18 09:02
I assume it's working for you now or you know at least what the issue is?  I'll go ahead and close this out.  If you still have questions, please visit https://github.com/libuv/help.

**Closed by bnoordhuis** 2017-04-18 09:02 UTC
