### ISSUE TITLE
Sporadic `SIGILL`/`EFAULT` on M1/arm64 Apple Macs

### ISSUE THREAD

**Issue by andreialecu** [libuv/libuv#3095] opened 2021-01-15 14:13 UTC
Just wanted to bring this into attention, hopefully it's the right place to post.

I've been using an M1 Mac Mini with 8GB of ram (this is important). While testing out the new (beta) VSCode arm64 build, I've been running into frequent crashes with a `SIGILL` exit code.

Besides VSCode I've seen SIGILL in some other CLI apps as well, for example while running some python scripts.

I recently came across this issue report that was originally discovered in Go: https://openradar.appspot.com/FB8922558

> This occurs whenever the copyout call in sendsig fails. The copyout call is responsible for writing the user-space signal handler’s stack frame. It should not be possible for copyout to fail in a well-behaved program where the stack frame is to be written to memory that is validly mapped in the target process. However, on arm64, if the copyout triggers a page fault, the copyout fails. The absent page should be paged in and used.

> In the wild, the bug occurs most readily on a system under heavy load (particularly, memory pressure).

I have attached some crash dumps from VSCode here:
https://github.com/microsoft/vscode/issues/113410#issuecomment-755635208

The stack traces for the SIGILL crashes include `libuv`:

```
52  Electron Framework!node::LibuvStreamWrap::OnUvRead(long, uv_buf_t const*) [stream_base-inl.h : 126 + 0x10]
     sp = 0x000000016b956790    pc = 0x0000000106e80710
    Found by: stack scanning
53  Electron Framework!node::LibuvStreamWrap::ReadStart()::$_1::__invoke(uv_handle_s*, unsigned long, uv_buf_t*) [stream_wrap.cc : 218 + 0x4]
     sp = 0x000000016b9567c0    pc = 0x0000000106e80ed0
    Found by: stack scanning
54  Electron Framework!uv__stream_io [stream.c : 1239 + 0xc]
     sp = 0x000000016b956810    pc = 0x00000001046d6f80
    Found by: stack scanning
```

In the issue linked above, we thought this might be fixed by https://github.com/libuv/libuv/pull/3064 but I now believe this is a separate problem.

Note that the Golang guys were able to find a workaround, see: https://github.com/golang/go/commit/7f688d18c0ae6df3e895d21799b8ece7d5941293

Also important is that nodejs crashes with `EFAULT` or `EPIPE` quite frequently by itself on the M1, as reported in: https://github.com/nodejs/node/issues/36826

* **Version**: (not sure, latest from nodejs 15.5.1 and from Electron)
* **Platform**: `Darwin Andreis-Mac-mini.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64`

**Comment by bnoordhuis** [comment] 2021-01-15 23:01
Thanks for the report. The sigaltstack+mlock workaround from the go people won't work for libuv because it doesn't own the signal stack. Node.js on the other hand could implement it.

(The sigaltstack is a process-global property. It's not safe for libuv to change it because other parts of the program may rely on the stack having properties that libuv isn't aware of, like a specific address, size or alignment.)

**Comment by andreialecu** [comment] 2021-01-18 15:33
Thank you for the detailed answer. 

One remaining question though, could the `EFAULT` errors be related to the bug mentioned? From my understanding the bug completely crashes the process with an uncatchable `SIGILL`, so `EFAULT` might be caused by something else.

Is the potential source for the `EFAULT`/`EPIPE` errors within `libuv` or are they also something for Node to address?

**Comment by bnoordhuis** [comment] 2021-01-18 20:57
I expect the EFAULT and EPIPE errors you see are caused by something else but I don't have a good working hypothesis on what specifically.

EFAULT means a bad pointer is passed to the kernel, usually an address that isn't mapped (i.e., would cause a segfault if the program tried to read from or write to it.)

However, libuv mostly just forwards the pointers it receives from the embedder (Node.js, Electron) so yeah, that's probably where to go start looking first.

EPIPE is (within reason) expected, it means you're trying to read from or write to a pipe or socket pair where the other end was closed.

**Comment by bnoordhuis** [comment] 2021-01-23 12:21
I'll take the liberty of closing this out but let me know if there are ways to improve libuv's M1 support.

**Closed by bnoordhuis** 2021-01-23 12:21 UTC
