### ISSUE TITLE
unix udp close crash

### ISSUE THREAD

**Issue by gdestiny** [libuv/libuv#4319] opened 2024-02-19 14:00 UTC
# here we send the udp msg
uv__udp_send -> uv__io_start

# recvmsg we close the handle
uv__udp_io -> uv__udp_recvmsg -> uv__udp_close

# after close on recvmsg
uv__udp_io -> uv__udp_sendmsg -> uv__io_feed

# on close callback, we free the handle, but it's still in pendding queue, we get crash in uv__run_pending
uv__run_pending

**Comment by gdestiny** [comment] 2024-02-19 14:04
is that fine to prevent sendmsg while uv__is_closing?

**Comment by bnoordhuis** [comment] 2024-02-19 16:23
From a quick look, it looks like the issue is legitimate but probably really rare in practice.

**Comment by vtjnash** [comment] 2024-02-19 19:14
`uv_close` immediately deletes the handle from pending here: https://github.com/libuv/libuv/blob/507f3046d104db2be2c33d5e8fc0d5322818a62c/src/unix/core.c#L966

So it may be the case that `uv_udp_send` and `uv_udp_recv` need to check if `!closing` and throw an invalid state exception

**Comment by bnoordhuis** [comment] 2024-02-19 20:25
I reckon' the order of events is this:

1. uv__io_poll calls uv__udp_io with revents == POLLIN + POLLOUT
2. uv__udp_io calls your recv_cb
3. you close the handle
4. uv__udp_io calls uv__udp_sendmsg
5. uv__udp_sendmsg calls uv__io_feed
6. kaboom!

But like I said, it's probably really hard to hit (I tried earlier today) because it depends on the socket becoming readable and writable at the same time right when you're about to close it.

POLLOUT itself is a fairly exceptional event because UDP sockets are almost always immediately writable. There's rarely a need to wait for it to become writable. Stress tests like our udp_timed_pummel_100v100 benchmark never even hit that code path on my machine.

**Comment by vtjnash** [comment] 2024-02-19 22:03
Ah, I see, that makes sense. The handling for all other streams appears to here have a guard against that from happening:
https://github.com/libuv/libuv/blob/507f3046d104db2be2c33d5e8fc0d5322818a62c/src/unix/stream.c#L1205-L1206

**Comment by gdestiny** [comment] 2024-02-20 02:00
> I reckon' the order of events is this:
> 
> 1. uv__io_poll calls uv__udp_io with revents == POLLIN + POLLOUT
> 2. uv__udp_io calls your recv_cb
> 3. you close the handle
> 4. uv__udp_io calls uv__udp_sendmsg
> 5. uv__udp_sendmsg calls uv__io_feed
> 6. kaboom!
> 
> But like I said, it's probably really hard to hit (I tried earlier today) because it depends on the socket becoming readable and writable at the same time right when you're about to close it.
> 
> POLLOUT itself is a fairly exceptional event because UDP sockets are almost always immediately writable. There's rarely a need to wait for it to become writable. Stress tests like our udp_timed_pummel_100v100 benchmark never even hit that code path on my machine.

it always happend while the pc is in hight load and the POLLOUT becoming slowly

**Comment by gdestiny** [comment] 2024-02-20 02:23
what's more, the handle->io_watcher.fd is invalid with udp closed
recvmsg will always get EBADF in the situation

**Comment by gdestiny** [comment] 2024-02-20 02:52
#4321 
@bnoordhuis is the pull request OK?

**Closed** 2024-03-02 03:45 UTC
