### ISSUE TITLE
Potential bug in `uv__udp_sendmmsg`

### ISSUE THREAD

**Issue by roshanr95** [libuv/libuv#3249] opened 2021-07-23 09:12 UTC
* **Version**: master
* **Platform**: Ubuntu

I was looking into the error handling and guarantees given by libuv with regards to UDP and came across what I think might be a bug while reading through the code.

The udp handle eventually reaches [here](https://github.com/libuv/libuv/blob/v1.x/src/unix/udp.c#L357) where it makes the `sendmmsg` syscall. It returns the number of packets that were successfully queued, but the return value doesn't seem to be handled appropriately.

Say I'm trying to send 10 packets and the send buffer has room for only 5. `npkts` would be 5, it skips the `if` block [here](https://github.com/libuv/libuv/blob/v1.x/src/unix/udp.c#L360). It then removes all 10 packets from the request queue [here](https://github.com/libuv/libuv/blob/v1.x/src/unix/udp.c#L379) instead of only the 5 that were successfully sent. Maybe the author meant to write `npkts` instead of `pkts` there?

Something very similar seems to be happening [here](https://github.com/libuv/libuv/blob/v1.x/src/unix/udp.c#L364) as well where nothing has actually been sent, yet packets are getting popped off the queue. Though this one might actually be fine as it seems to be draining the queue on (non-recoverable?) errors only.

Are these bugs, the first one especially? Or am I just misunderstanding what's actually happening?

**Comment by santigimeno** [comment] 2021-07-23 09:22
Duplicate of https://github.com/libuv/libuv/issues/3129. And yes, I think it's a bug.

**Comment by santigimeno** [comment] 2021-07-23 09:23
I'll close this and keep the other one open.

**Closed by santigimeno** 2021-07-23 09:23 UTC
