### ISSUE TITLE
Use liburing

### ISSUE THREAD

**Issue by jimmyjones2** [libuv/libuv#2238] opened 2019-03-29 17:44 UTC
Linux 5.1 has a new, more efficient API for asynchronous IO - io_uring (see [LWN](https://lwn.net/Articles/776703/)) with a userspace library [liburing](http://git.kernel.dk/cgit/liburing/)

Could using this make libuv more efficient?

**Comment by rektide** [comment] 2019-03-31 23:19
Possible dupe of #1947.

Mods- I would like to see #1947 actually mention the specific "new kernel polling interface" in the title (io_uring or liburing), to avoid this confusion in the future.

**Comment by saghul** [comment] 2019-04-01 07:48
Done.

**Closed by saghul** 2019-04-01 07:48 UTC
