### ISSUE TITLE
102 not ok and 103 not ok when make check on centos

### ISSUE THREAD

**Issue by muyuxx** [libuv/libuv#2744] opened 2020-03-19 09:55 UTC
environment

centos6.8
cmake3.6
gcc6.1
libuv1.22

102 not ok and 103 not ok when make check. how to fix it?

**Comment by bnoordhuis** [comment] 2020-03-19 12:27
Can you post the verbatim output of `make check`?

**Comment by muyuxx** [comment] 2020-03-20 03:48
times.nice: 0
# uv_interface_addresses:
#   name: lo
#   internal: 1
#   physical address: 00:00:00:00:00:00
#   address: 127.0.0.1
#   netmask: 255.0.0.0
#   name: eth0
#   internal: 0
#   physical address: 00:0c:29:8b:94:2b
#   address: 192.168.23.129
#   netmask: 255.255.255.0
#   name: lo
#   internal: 1
#   physical address: 00:00:00:00:00:00
#   address: ::1
#   netmask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
#   name: eth0
#   internal: 0
#   physical address: 00:0c:29:8b:94:2b
#   address: fe80::20c:29ff:fe8b:942b
#   netmask: ffff:ffff:ffff:ffff::
# uv_os_get_passwd:
#   euid: 0
#   gid: 0
#   username: root
#   shell: /bin/bash
#   home directory: /root
# uv_os_getpid: 9271
# uv_os_getppid: 9102
ok 2 - active
ok 3 - async
ok 4 - async_null_cb
ok 5 - async_ref
ok 6 - barrier_1
ok 7 - barrier_2
ok 8 - barrier_3
ok 9 - callback_stack
ok 10 - check_ref
ok 11 - close_fd
ok 12 - close_order
ok 13 - closed_fd_events
ok 14 - condvar_1
ok 15 - condvar_2
ok 16 - condvar_3
ok 17 - condvar_4
ok 18 - condvar_5
ok 19 - connect_unspecified
ok 20 - connection_fail
ok 21 - connection_fail_doesnt_auto_close
ok 22 - cwd_and_chdir
ok 23 - default_loop_close
ok 24 - delayed_accept
ok 25 - dlerror
ok 26 - eintr_handling
ok 27 - embed
ok 28 - emfile
ok 29 - env_vars
ok 30 - error_message
ok 31 - fork_fs_events_child
ok 32 - fork_fs_events_child_dir
ok 33 - fork_fs_events_file_parent_child
ok 34 - fork_signal_to_child
ok 35 - fork_signal_to_child_closed
ok 36 - fork_socketpair
ok 37 - fork_socketpair_started
ok 38 - fork_threadpool_queue_work_simple
ok 39 - fork_timer
ok 40 - fs_access
ok 41 - fs_async_dir
ok 42 - fs_async_sendfile
ok 43 - fs_chmod
ok 44 - fs_chown
ok 45 - fs_copyfile
ok 46 - fs_event_close_in_callback
ok 47 - fs_event_close_with_pending_event
ok 48 - fs_event_error_reporting
ok 49 - fs_event_getpath
ok 50 - fs_event_immediate_close
ok 51 - fs_event_no_callback_after_close
ok 52 - fs_event_no_callback_on_close
ok 53 - fs_event_ref
ok 54 - fs_event_start_and_close
ok 55 - fs_event_watch_dir
ok 56 - fs_event_watch_dir_recursive # SKIP Recursive directory watching not supported on this platform.
ok 57 - fs_event_watch_file
ok 58 - fs_event_watch_file_current_dir
ok 59 - fs_event_watch_file_exact_path
ok 60 - fs_event_watch_file_twice
ok 61 - fs_event_watch_invalid_path
ok 62 - fs_file_async
ok 63 - fs_file_loop
ok 64 - fs_file_nametoolong
ok 65 - fs_file_noent
ok 66 - fs_file_open_append
ok 67 - fs_file_pos_after_op_with_offset
ok 68 - fs_file_sync
ok 69 - fs_file_write_null_buffer
ok 70 - fs_fstat
ok 71 - fs_futime
ok 72 - fs_mkdtemp
ok 73 - fs_null_req
ok 74 - fs_open_dir
ok 75 - fs_poll
ok 76 - fs_poll_getpath
ok 77 - fs_poll_ref
ok 78 - fs_read_file_eof
ok 79 - fs_read_write_null_arguments
ok 80 - fs_readlink
ok 81 - fs_realpath
ok 82 - fs_rename_to_existing_file
ok 83 - fs_scandir_empty_dir
ok 84 - fs_scandir_file
ok 85 - fs_scandir_non_existent_dir
ok 86 - fs_stat_missing_path
ok 87 - fs_symlink
ok 88 - fs_symlink_dir
ok 89 - fs_unlink_readonly
ok 90 - fs_utime
ok 91 - fs_write_alotof_bufs
ok 92 - fs_write_alotof_bufs_with_offset
ok 93 - fs_write_multiple_bufs
ok 94 - get_currentexe
ok 95 - get_loadavg
ok 96 - get_memory
ok 97 - get_osfhandle_valid_handle
ok 98 - get_passwd
ok 99 - getaddrinfo_basic
ok 100 - getaddrinfo_basic_sync
ok 101 - getaddrinfo_concurrent
not ok 102 - getaddrinfo_fail
# exit code 134
# Output from process `getaddrinfo_fail`:
# Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
ok 103 - getaddrinfo_fail_sync
ok 104 - gethostname
ok 105 - getnameinfo_basic_ip4
ok 106 - getnameinfo_basic_ip4_sync
ok 107 - getnameinfo_basic_ip6
ok 108 - getsockname_tcp
ok 109 - getsockname_udp
ok 110 - getters_setters
ok 111 - handle_fileno
ok 112 - handle_type_name
ok 113 - has_ref
ok 114 - homedir
ok 115 - hrtime
ok 116 - idle_ref
ok 117 - idle_starvation
ok 118 - ip4_addr
ok 119 - ip6_addr_link_local
ok 120 - ip6_pton
ok 121 - ipc_closed_handle
ok 122 - ipc_heavy_traffic_deadlock_bug
ok 123 - ipc_listen_after_write
ok 124 - ipc_listen_before_write
ok 125 - ipc_send_recv_pipe
ok 126 - ipc_send_recv_pipe_inprocess
ok 127 - ipc_send_recv_tcp
ok 128 - ipc_send_recv_tcp_inprocess
ok 129 - ipc_tcp_connection
ok 130 - kill
ok 131 - kill_invalid_signum
ok 132 - loop_alive
ok 133 - loop_backend_timeout
ok 134 - loop_close
ok 135 - loop_configure
ok 136 - loop_handles
ok 137 - loop_instant_close
ok 138 - loop_stop
ok 139 - loop_update_time
ok 140 - multiple_listen
ok 141 - pipe_bind_error_addrinuse
ok 142 - pipe_bind_error_addrnotavail
ok 143 - pipe_bind_error_inval
ok 144 - pipe_close_stdout_read_stdin
ok 145 - pipe_connect_bad_name
ok 146 - pipe_connect_multiple
ok 147 - pipe_connect_on_prepare
ok 148 - pipe_connect_to_file
ok 149 - pipe_getsockname
ok 150 - pipe_getsockname_abstract
ok 151 - pipe_getsockname_blocking
ok 152 - pipe_listen_without_bind
ok 153 - pipe_pending_instances
ok 154 - pipe_ping_pong
ok 155 - pipe_ping_pong_vec
ok 156 - pipe_ref
ok 157 - pipe_ref2
ok 158 - pipe_ref3
ok 159 - pipe_ref4
ok 160 - pipe_sendmsg
ok 161 - pipe_server_close
ok 162 - pipe_set_chmod
ok 163 - pipe_set_non_blocking
ok 164 - poll_bad_fdtype
ok 165 - poll_close
ok 166 - poll_close_doesnt_corrupt_stack # SKIP Test only relevant on Windows
ok 167 - poll_closesocket # SKIP Test only relevant on Windows
ok 168 - poll_duplex
ok 169 - poll_nested_epoll
ok 170 - poll_oob
ok 171 - poll_unidirectional
ok 172 - prepare_ref
ok 173 - process_ref
ok 174 - process_title
ok 175 - process_title_threadsafe
ok 176 - queue_foreach_delete
ok 177 - ref
ok 178 - req_type_name
ok 179 - run_nowait
ok 180 - run_once
ok 181 - semaphore_1
ok 182 - semaphore_2
ok 183 - semaphore_3
ok 184 - shutdown_close_pipe
ok 185 - shutdown_close_tcp
ok 186 - shutdown_eof
ok 187 - shutdown_twice
ok 188 - signal_multiple_loops
ok 189 - socket_buffer_size
ok 190 - spawn_and_kill
ok 191 - spawn_and_kill_with_std
ok 192 - spawn_and_ping
ok 193 - spawn_auto_unref
ok 194 - spawn_closed_process_io
ok 195 - spawn_detached
ok 196 - spawn_exit_code
ok 197 - spawn_fails
ok 198 - spawn_fails_check_for_waitpid_cleanup
ok 199 - spawn_fs_open
ok 200 - spawn_ignored_stdio
ok 201 - spawn_inherit_streams
ok 202 - spawn_preserve_env
ok 203 - spawn_quoted_path # SKIP Test for Windows
ok 204 - spawn_reads_child_path
ok 205 - spawn_setgid_fails
ok 206 - spawn_setuid_fails
ok 207 - spawn_setuid_setgid # SKIP user 'nobody' cannot access the test runner
ok 208 - spawn_stdin
ok 209 - spawn_stdio_greater_than_3
ok 210 - spawn_stdout
ok 211 - spawn_stdout_and_stderr_to_file
ok 212 - spawn_stdout_and_stderr_to_file2
ok 213 - spawn_stdout_and_stderr_to_file_swap
ok 214 - spawn_stdout_to_file
ok 215 - spawn_tcp_server
ok 216 - stdio_over_pipes
ok 217 - sys_error
ok 218 - tcp6_ping_pong
ok 219 - tcp6_ping_pong_vec
ok 220 - tcp_alloc_cb_fail
ok 221 - tcp_bind6_error_addrinuse
ok 222 - tcp_bind6_error_addrnotavail
ok 223 - tcp_bind6_error_fault
ok 224 - tcp_bind6_error_inval
ok 225 - tcp_bind6_localhost_ok
ok 226 - tcp_bind_error_addrinuse
ok 227 - tcp_bind_error_addrnotavail_1
ok 228 - tcp_bind_error_addrnotavail_2
ok 229 - tcp_bind_error_fault
ok 230 - tcp_bind_error_inval
ok 231 - tcp_bind_invalid_flags
ok 232 - tcp_bind_localhost_ok
ok 233 - tcp_bind_writable_flags
ok 234 - tcp_close
ok 235 - tcp_close_accept
ok 236 - tcp_close_while_connecting
ok 237 - tcp_connect_error_after_write
ok 238 - tcp_connect_error_fault
ok 239 - tcp_connect_timeout
ok 240 - tcp_create_early
ok 241 - tcp_create_early_accept
ok 242 - tcp_create_early_bad_bind
ok 243 - tcp_create_early_bad_domain
ok 244 - tcp_flags
ok 245 - tcp_listen_without_bind
ok 246 - tcp_oob
ok 247 - tcp_open
ok 248 - tcp_open_bound
ok 249 - tcp_open_connected
ok 250 - tcp_open_twice
ok 251 - tcp_ping_pong
ok 252 - tcp_ping_pong_vec
ok 253 - tcp_read_stop
ok 254 - tcp_ref
ok 255 - tcp_ref2
ok 256 - tcp_ref2b
ok 257 - tcp_ref3
ok 258 - tcp_ref4
ok 259 - tcp_shutdown_after_write
ok 260 - tcp_try_write
ok 261 - tcp_unexpected_read
ok 262 - tcp_write_after_connect
ok 263 - tcp_write_fail
ok 264 - tcp_write_queue_order
ok 265 - tcp_write_to_half_open_connection
ok 266 - tcp_writealot
ok 267 - thread_create
ok 268 - thread_equal
ok 269 - thread_local_storage
ok 270 - thread_mutex
ok 271 - thread_mutex_recursive
ok 272 - thread_rwlock
ok 273 - thread_rwlock_trylock
ok 274 - thread_stack_size
ok 275 - threadpool_cancel_fs
ok 276 - threadpool_cancel_getaddrinfo
ok 277 - threadpool_cancel_getnameinfo
ok 278 - threadpool_cancel_single
ok 279 - threadpool_cancel_work
ok 280 - threadpool_multiple_event_loops
ok 281 - threadpool_queue_work_einval
ok 282 - threadpool_queue_work_simple
ok 283 - timer
ok 284 - timer_again
ok 285 - timer_early_check
ok 286 - timer_from_check
ok 287 - timer_huge_repeat
ok 288 - timer_huge_timeout
ok 289 - timer_init
ok 290 - timer_null_callback
ok 291 - timer_order
ok 292 - timer_ref
ok 293 - timer_ref2
ok 294 - timer_run_once
ok 295 - timer_start_twice
ok 296 - tmpdir
ok 297 - tty
ok 298 - tty_file
ok 299 - tty_pty
ok 300 - udp_alloc_cb_fail
ok 301 - udp_bind
ok 302 - udp_bind_reuseaddr
ok 303 - udp_create_early
ok 304 - udp_create_early_bad_bind
ok 305 - udp_create_early_bad_domain
ok 306 - udp_dgram_too_big
ok 307 - udp_dual_stack
ok 308 - udp_ipv6_only
ok 309 - udp_multicast_interface
ok 310 - udp_multicast_interface6
ok 311 - udp_multicast_join
ok 312 - udp_multicast_join6
ok 313 - udp_multicast_ttl
ok 314 - udp_no_autobind
ok 315 - udp_open
ok 316 - udp_open_twice
ok 317 - udp_options
ok 318 - udp_options6
ok 319 - udp_ref
ok 320 - udp_ref2
ok 321 - udp_ref3
ok 322 - udp_send_and_recv
ok 323 - udp_send_hang_loop
ok 324 - udp_send_immediate
ok 325 - udp_send_unreachable
ok 326 - udp_try_send
ok 327 - unref_in_prepare_cb
ok 328 - walk_handles
ok 329 - watcher_cross_stop
ok 330 - we_get_signal
ok 331 - we_get_signal_one_shot
ok 332 - we_get_signals
ok 333 - we_get_signals_mixed
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory `/root/Desktop/libuv-v1.22.0'
make: *** [check-am] Error 2
[root@localhost libuv-v1.22.0]#

**Comment by bnoordhuis** [comment] 2020-03-20 08:58
I only see this failure:
```
not ok 102 - getaddrinfo_fail
# exit code 134
# Output from process `getaddrinfo_fail`:
# Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
```
And that's almost certainly caused by your local DNS returning something for the domain name `xyzzy.xyzzy.xyzzy.` instead of NXDOMAIN.

I'm going to close this out but let me know if you have reason to believe it's an issue with libuv after all.

**Closed by bnoordhuis** 2020-03-20 08:58 UTC

**Comment by muyuxx** [comment] 2020-03-20 10:22
@bnoordhuis  
make check passed after changed my network
think you
