### ISSUE TITLE
make check fails one test

### ISSUE THREAD

**Issue by themaddoctor** [libuv/libuv#1517] opened 2017-09-03 03:18 UTC
libuv-1.14.0

not ok 252 - fs_copyfile
exit code 6
Output from process `fs_copyfile`:
Assertion failed in test/test-fs-copyfile.c on line 57: stat_req.statbuf.st_mode == mode

FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================

**Comment by cjihrig** [comment] 2017-09-03 13:37
@themaddoctor can you provide more information.

- What platform is this?
- Does the test fail consistently or sporadically?
- The line number of the failed assertion is executed a number of times. Are you able to debug which `uv_fs_copyfile()` call is the culprit?
- If the platform is not Windows or macOS, does the patch in #1494 make any difference?

**Comment by themaddoctor** [comment] 2017-09-03 15:52
I'm sorry, but I'm unable to navigate github very well. In that thread I could not find any links to a patch. The link to "413" gave an HTTP 404 not found error.

I use linux.

HTTP ERROR 404

Problem accessing /view/libuv/job/libuv-test-commit/413/. Reason:

    Not Found

Powered by Jetty://

**Comment by cjihrig** [comment] 2017-09-03 16:13
How about this: https://patch-diff.githubusercontent.com/raw/libuv/libuv/pull/1494.patch

**Comment by themaddoctor** [comment] 2017-09-03 16:20
Hunk 2 fails because the code I have (1.14.0) contains the following. Instead of NULL, I have req->loop. It seems like an important difference.

  err = uv_fs_sendfile(req->loop,
                       &fs_req,
                       dstfd,
                       srcfd,
                       0,
                       statsbuf.st_size,
                       NULL);

**Comment by cjihrig** [comment] 2017-09-03 16:30
There have been a few changes to the file since 1.14.0 was released. The most current version is [here](https://github.com/libuv/libuv/blob/v1.x/src/unix/fs.c).

**Comment by cjihrig** [comment] 2017-09-03 16:31
Or just pull the `v1.x` branch. That'd probably be best.

**Comment by themaddoctor** [comment] 2017-09-03 16:32
If I replace "req->loop" with "NULL", will it break anything?

**Comment by themaddoctor** [comment] 2017-09-03 16:33
After patching, the error remains:
```
not ok 252 - fs_copyfile
# exit code 6
# Output from process `fs_copyfile`:
# Assertion failed in test/test-fs-copyfile.c on line 57: stat_req.statbuf.st_mode == mode
```

**Comment by cjihrig** [comment] 2017-09-03 16:34
No. But there have been other changes that have landed. It would be best to get the most up to date version of the `v1.x` branch, just to see if you're still running into problems.

**Comment by cjihrig** [comment] 2017-09-03 16:34
> After patching, the error remains:

So that reproduces every time for you? On Linux? Can you identify which `uv_fs_copyfile()` call results in the failed assertion?

**Comment by themaddoctor** [comment] 2017-09-03 16:43
Building it now.

BTW, automake fails because of a missing ltmain.sh

**Comment by themaddoctor** [comment] 2017-09-03 16:46
All tests now pass. Today's code with patch 1494.

Thank you

**Comment by cjihrig** [comment] 2017-09-03 16:47
Cool. Thanks for checking. Let's leave this open for now, and close it when #1494 lands.

**Closed** 2017-09-05 13:57 UTC
