### ISSUE TITLE
win: uv_send_buffer_size() failed 

### ISSUE THREAD

**Issue by dkrikun** [libuv/libuv#769] opened 2016-03-17 12:03 UTC
`uv_send_buffer_size()` fails occasionaly with error code `WSAENOTSOCK` for a udp socket.

libuv version: 1.8.0
Windows 7 x64, Visual Studio 2015.

**Comment by txdv** [comment] 2016-03-17 12:26
Libuv creates the socket at the last possible moment. Try, after creating the socket, to send a packet somewhere (the content and the target is not important). Then set the buffer size. It should work then.

**Comment by kthelgason** [comment] 2016-03-17 16:19
Shouldn't `uv_send_buffer_size()` force creation of the socket, or record the setting and lazily apply it when the socket is created?

Or perhaps just a warning added to the docs?

**Comment by txdv** [comment] 2016-03-17 19:34
> Shouldn't uv_send_buffer_size() force creation of the socket

The underlying socket api needs the network family in the creation of the socket. There is also uv_udp_init_ex which immediately created  the socket.

**Comment by dkrikun** [comment] 2016-03-17 19:38
I guess, it would be best if libuv could handle setting buffer size without forcing socket creation. After all, it is an implementation detail that the socket is created lazily.

**Comment by txdv** [comment] 2016-03-17 19:44
That would require an extra field in the handle or a different approach.

**Comment by saghul** [comment] 2016-03-18 10:36
Closing, not a bug. The socket needs to exist in order to be able to set the buffer, I recommend using `uv_udp_init_ex`, which also saves you from getting EMFILE in unexpected places, since the socket would have already been created.

**Closed by saghul** 2016-03-18 10:36 UTC

**Comment by dkrikun** [comment] 2016-03-19 17:54
I think this should be documented in `uv_send_buffer_size()`.

**Comment by saghul** [comment] 2016-03-21 08:49
Feel free to open a documentation PR :-)
