### ISSUE TITLE
Undefined symbols "_close$NOCANCEL$UNIX2003", referenced from 

### ISSUE THREAD

**Issue by gamecreating** [libuv/libuv#2680] opened 2020-02-10 10:19 UTC
Undefined symbols for architecture armv7:
  "_close$NOCANCEL$UNIX2003", referenced from:
      _uv__close_nocancel in libuv.a(core.o)
      _uv__close_nocheckstdio in libuv.a(core.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

link libuv to ios dylib

xcode version 11.3.1 (11C504)

**Comment by bnoordhuis** [comment] 2020-02-10 10:35
Duplicate of #2638. Already fixed in commit 2475296, will be part of the next libuv release.

**Closed by bnoordhuis** 2020-02-10 10:35 UTC
