### ISSUE TITLE
I need libuv.so.1 on...

### ISSUE THREAD

**Issue by GazbonicAcid** [libuv/libuv#1802] opened 2018-04-18 04:07 UTC
I need libuv.so.1 on the Xubuntu derivitive of Trusty 14.04.2
A game I want to play requires it.
14.04.2 is the latest lts that AMD supports for my laptop's apu's gpu drivers.
The latest non lts they support is 15, but 15's security support has expired so no thanks.
P.S. Not sure if I should make new issue or not. See [this](https://github.com/libuv/libuv/issues/643#issuecomment-382251861)
Edit: yeaaaah. that one's too old. the other issue I mean

**Comment by bnoordhuis** [comment] 2018-04-18 09:05
Then build it from source?  Closing, not a bug.  If you're looking for help, go to libuv/help.

**Closed by bnoordhuis** 2018-04-18 09:05 UTC
