### ISSUE TITLE
Mispelled variable name VSWHERE_WITH_PRERELASE -> VSWHERE_WITH_PRERELEASE

### ISSUE THREAD

**Issue by 3DHDSoft** [libuv/libuv#1477] opened 2017-08-13 16:00 UTC
Mispelled variable name VSWHERE_WITH_PRERELASE -> VSWHERE_WITH_PREREL**E**ASE at https://github.com/libuv/libuv/blob/ce56a85b19e13287d2613f8de33f479a9c1104b5/tools/vswhere_usability_wrapper.cmd#L21

**Comment by cjihrig** [comment] 2017-08-13 17:29
Closing as essentially a duplicate of #1477 I think.

**Closed by cjihrig** 2017-08-13 17:29 UTC
