### ISSUE TITLE
libuv broke Node

### ISSUE THREAD

**Issue by Archcry** [libuv/libuv#1716] opened 2018-01-18 09:27 UTC
* **Version**: 1.19.0-1
* **Platform**: Linux

The new version (1.19.0-1) of libuv broke node on my Linux machine (ArchLinux). According to [semver](https://semver.org/) minor releases should not break dependant software. See https://github.com/npm/npm/issues/19634#issuecomment-358585641

**Comment by bnoordhuis** [comment] 2018-01-18 09:31
We're aware.  There's a reason we bundle libuv with node.js and it looks like arch users are finding that out the hard way today.

**Comment by Archcry** [comment] 2018-01-18 09:33
Well, minor versions should not introduce breaking changes so blaming Arch users for it seems kind of odd in my opinion.

**Comment by bnoordhuis** [comment] 2018-01-18 09:36
It's a bug, nothing more.  We do integration testing on the node.js side and it caught the regression.  If arch had stuck with the bundled version, you wouldn't be experiencing fallout right now.

**Comment by Archcry** [comment] 2018-01-18 09:38
Ah my apologies, I though you meant that is was okay to introduce breaking changes in a minor version. Thanks for clarifying that it is a bug.

**Comment by bnoordhuis** [comment] 2018-01-18 09:39
Oh, and to be clear, the real bug is most likely on the node.js side, the newest libuv release merely exposes it.  But we'll be reverting the libuv change for now until things get fixed in node.js.

**Comment by Archcry** [comment] 2018-01-18 09:41
Hmm ok, thanks for the quick responses :D

**Closed** 2018-01-19 16:53 UTC
