### ISSUE TITLE
tcp_connect_timeout

### ISSUE THREAD

**Issue by ninopereira** [libuv/libuv#1339] opened 2017-05-09 14:49 UTC
* **Version**:  libuv-v.1.9.1 
* **Platform**:  152-Ubuntu SMP Fri Dec 2 15:37:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux 
Ubuntu 14.04

When running make check:

not ok 65 - tcp_connect_timeout
exit code 6
Output from process `tcp_connect_timeout`:
Assertion failed in test/test-tcp-connect-timeout.c on line 42: status == UV_ECANCELED
not ok 66 - tcp_close_while_connecting
exit code 6
Output from process `tcp_close_while_connecting`:
Assertion failed in test/test-tcp-close-while-connecting.c on line 45: status == UV_ECANCELED || status == UV_ENETUNREACH

**Comment by santigimeno** [comment] 2017-05-09 15:05
@ninopereira can you check if it fails with latest `v1.x` branch. At least there were fixes for `tcp_close_while_connecting` failures. If the tests keep failing could you print the `status` is really returning?

**Comment by ninopereira** [comment] 2017-05-11 08:50
I repeated the test with the latest version (as from 2017-05-10) and I have the same problem.

not ok 65 - tcp_connect_timeout
# exit code 6
# Output from process `tcp_connect_timeout`:
# Assertion failed in test/test-tcp-connect-timeout.c on line 42: status == UV_ECANCELED
not ok 66 - tcp_close_while_connecting
# exit code 6
# Output from process `tcp_close_while_connecting`:
# Assertion failed in test/test-tcp-close-while-connecting.c on line 45: status == UV_ECANCELED || status == UV_ENETUNREACH

**Comment by santigimeno** [comment] 2017-05-14 08:03
Can you print the value of `status` on those failing tests? Thanks!

**Comment by vennand** [comment] 2017-09-14 17:38
I have the same problem at the moment

Version: libuv-v.1.9.1
Platform: Raspbian 4.9.46-v7+ on Raspberry Pi 3

The value of `status` is `-111`

**Comment by bnoordhuis** [comment] 2017-09-14 19:28
`-111` is `ECONNREFUSED`, which suggests there is something (like a firewall rule) rejecting the connection to `tcp://8.8.8.8:9999/`.

I suppose the test could terminate silently on `ECONNREFUSED` or `ENETUNREACH` but that might decrease its validity.  I.e., it might let regressions slip in due to being overly accepting.

**Comment by vennand** [comment] 2017-09-15 11:03
It seems to be a network configuration in my case, none of my other machines on the network can connect either.

It might be useful to print out the value of `status` by default when an error occurs in the tests though.

**Comment by cjihrig** [comment] 2018-03-03 17:08
Closing as a network configuration issue.

**Closed by cjihrig** 2018-03-03 17:08 UTC
