### ISSUE TITLE
fs_scandir_file test fail on SunOS

### ISSUE THREAD

**Issue by Zikoel** [libuv/libuv#1708] opened 2018-01-16 14:24 UTC
Hi at all,
I am able to compile the last released version of libuv `v1.18.0` on my SunOS (OpenIndiana), many test
pass without problem, but some trouble occurs on fs tests! I try to understand what happen on the
`fs_scandir_file` test. After some debugging session I have found the point that cause the fail:

On file fs.c the test pass on the function `uv__fs_scandir` twice.

* First time *synchronously* and all go ok.
* Second time *asynchronously* and here I have the error: The excecution of `scandir()` return -1 as expected, but the `errno` number is not setted to 20 but to 0.

The test fail message is:
```
not ok 83 - fs_scandir_file
# exit code 134
# Output from process `fs_scandir_file`:
# Assertion failed in <path>/libuv/test/test-fs.c on line 549: req->result == UV_ENOTDIR
```

I have try to reproduce this error using `scandir` directly many time but this kind of error appear only
when the call is performing by libuv. Someone have suggestion for solve this problem?

**Comment by bnoordhuis** [comment] 2018-01-17 10:54
Perhaps you can trace the test with dtruss?  `run-tests fs_scandir_file fs_scandir_file` will run just that test.

**Comment by Zikoel** [comment] 2018-01-17 13:31
Thank you for the tip, the output is a little bit tricky to understand. I think that what concern the error are the two `open` of the file `empty_file` (sorry for the long paste but I don't known what can be important or not)
```
truss -a ./uv_tests fs_scandir_file fs_scandir_file
execve("uv_tests", 0xFFFFFD7FFFDFFAC8, 0xFFFFFD7FFFDFFAE8)  argc = 3
sysinfo(SI_MACHINE, "i86pc", 257)		= 6
mmap(0x00000000, 56, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF390000
mmap(0x00000000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF380000
mmap(0x00000000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF370000
mmap(0x00000000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF360000
memcntl(0xFFFFFD7FFF393000, 110320, MC_ADVISE, MADV_WILLNEED, 0, 0) = 0
mmap(0x00000000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF350000
memcntl(0x00400000, 143488, MC_ADVISE, MADV_WILLNEED, 0, 0) = 0
resolvepath("/usr/lib/amd64/ld.so.1", "/lib/amd64/ld.so.1", 1023) = 18
getcwd("/home/myuser/libuv/build", 1014) = 0
resolvepath("/home/myuser/libuv/build/uv_tests", "/home/myuser/libuv/build/uv_tests", 1023) = 61
stat("/home/myuser/libuv/build/uv_tests", 0xFFFFFD7FFFDFF7C0) = 0
open("/var/ld/64/ld.config", O_RDONLY)		Err#2 ENOENT
stat("/opt/GCC-7.2.0.x64/lib/amd64/libuv.so", 0xFFFFFD7FFFDFEBF0) Err#2 ENOENT
stat("/home/myuser/libuv/build/libuv.so", 0xFFFFFD7FFFDFEBF0) = 0
resolvepath("/home/myuser/libuv/build/libuv.so", "/home/myuser/libuv/build/libuv.so", 1023) = 61
open("/home/myuser/libuv/build/libuv.so", O_RDONLY) = 3
mmapobj(3, MMOBJ_INTERPRET, 0xFFFFFD7FFF350BE0, 0xFFFFFD7FFFDFEB7C, 0x00000000) = 0
close(3)					= 0
memcntl(0xFFFFFD7DA44E0000, 68096, MC_ADVISE, MADV_WILLNEED, 0, 0) = 0
stat("/opt/GCC-7.2.0.x64/lib/amd64/libdl.so.1", 0xFFFFFD7FFFDFEBF0) Err#2 ENOENT
stat("/home/myuser/libuv/build/libdl.so.1", 0xFFFFFD7FFFDFEBF0) Err#2 ENOENT
stat("/lib/64/libdl.so.1", 0xFFFFFD7FFFDFEBF0)	= 0
resolvepath("/lib/64/libdl.so.1", "/lib/amd64/libdl.so.1", 1023) = 21
open("/lib/64/libdl.so.1", O_RDONLY)		= 3
mmap(0x00000000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF340000
mmapobj(3, MMOBJ_INTERPRET, 0xFFFFFD7FFF340030, 0xFFFFFD7FFFDFEB7C, 0x00000000) = 0
close(3)					= 0
stat("/opt/GCC-7.2.0.x64/lib/amd64/libkstat.so.1", 0xFFFFFD7FFFDFEBF0) Err#2 ENOENT
stat("/home/myuser/libuv/build/libkstat.so.1", 0xFFFFFD7FFFDFEBF0) Err#2 ENOENT
stat("/lib/64/libkstat.so.1", 0xFFFFFD7FFFDFEBF0) = 0
resolvepath("/lib/64/libkstat.so.1", "/lib/amd64/libkstat.so.1", 1023) = 24
open("/lib/64/libkstat.so.1", O_RDONLY)		= 3
mmapobj(3, MMOBJ_INTERPRET, 0xFFFFFD7FFF3409E0, 0xFFFFFD7FFFDFEB7C, 0x00000000) = 0
close(3)					= 0
mmap(0x00000000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF330000
memcntl(0xFFFFFD7FF5760000, 4200, MC_ADVISE, MADV_WILLNEED, 0, 0) = 0
stat("/opt/GCC-7.2.0.x64/lib/amd64/libsendfile.so.1", 0xFFFFFD7FFFDFEBF0) Err#2 ENOENT
stat("/home/myuser/libuv/build/libsendfile.so.1", 0xFFFFFD7FFFDFEBF0) Err#2 ENOENT
stat("/lib/64/libsendfile.so.1", 0xFFFFFD7FFFDFEBF0) = 0
resolvepath("/lib/64/libsendfile.so.1", "/lib/amd64/libsendfile.so.1", 1023) = 27
open("/lib/64/libsendfile.so.1", O_RDONLY)	= 3
mmapobj(3, MMOBJ_INTERPRET, 0xFFFFFD7FFF3309C8, 0xFFFFFD7FFFDFEB7C, 0x00000000) = 0
close(3)					= 0
mmap(0x00000000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF320000
memcntl(0xFFFFFD7F62DA0000, 2688, MC_ADVISE, MADV_WILLNEED, 0, 0) = 0
stat("/opt/GCC-7.2.0.x64/lib/amd64/libsocket.so.1", 0xFFFFFD7FFFDFEBF0) Err#2 ENOENT
stat("/home/myuser/libuv/build/libsocket.so.1", 0xFFFFFD7FFFDFEBF0) Err#2 ENOENT
stat("/lib/64/libsocket.so.1", 0xFFFFFD7FFFDFEBF0) = 0
resolvepath("/lib/64/libsocket.so.1", "/lib/amd64/libsocket.so.1", 1023) = 25
open("/lib/64/libsocket.so.1", O_RDONLY)	= 3
mmapobj(3, MMOBJ_INTERPRET, 0xFFFFFD7FFF3209B0, 0xFFFFFD7FFFDFEB7C, 0x00000000) = 0
close(3)					= 0
mmap(0x00000000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF310000
memcntl(0xFFFFFD7FFDF80000, 30568, MC_ADVISE, MADV_WILLNEED, 0, 0) = 0
stat("/opt/GCC-7.2.0.x64/lib/amd64/librt.so.1", 0xFFFFFD7FFFDFEBF0) Err#2 ENOENT
stat("/home/myuser/libuv/build/librt.so.1", 0xFFFFFD7FFFDFEBF0) Err#2 ENOENT
stat("/lib/64/librt.so.1", 0xFFFFFD7FFFDFEBF0)	= 0
resolvepath("/lib/64/librt.so.1", "/lib/amd64/librt.so.1", 1023) = 21
open("/lib/64/librt.so.1", O_RDONLY)		= 3
mmapobj(3, MMOBJ_INTERPRET, 0xFFFFFD7FFF310A28, 0xFFFFFD7FFFDFEB7C, 0x00000000) = 0
close(3)					= 0
mmap(0x00000000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF300000
stat("/opt/GCC-7.2.0.x64/lib/amd64/libgcc_s.so.1", 0xFFFFFD7FFFDFEBF0) = 0
resolvepath("/opt/GCC-7.2.0.x64/lib/amd64/libgcc_s.so.1", "/opt/GCC-7.2.0.x64/lib/amd64/libgcc_s.so.1", 1023) = 42
open("/opt/GCC-7.2.0.x64/lib/amd64/libgcc_s.so.1", O_RDONLY) = 3
mmapobj(3, MMOBJ_INTERPRET, 0xFFFFFD7FFF3007A0, 0xFFFFFD7FFFDFEB7C, 0x00000000) = 0
close(3)					= 0
mmap(0x00000000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF2F0000
memcntl(0xFFFFFD7FF2DE0000, 27880, MC_ADVISE, MADV_WILLNEED, 0, 0) = 0
stat("/opt/GCC-7.2.0.x64/lib/amd64/libc.so.1", 0xFFFFFD7FFFDFEBF0) Err#2 ENOENT
stat("/home/myuser/libuv/build/libc.so.1", 0xFFFFFD7FFFDFEBF0) Err#2 ENOENT
stat("/lib/64/libc.so.1", 0xFFFFFD7FFFDFEBF0)	= 0
resolvepath("/lib/64/libc.so.1", "/lib/amd64/libc.so.1", 1023) = 20
open("/lib/64/libc.so.1", O_RDONLY)		= 3
mmapobj(3, MMOBJ_INTERPRET, 0xFFFFFD7FFF2F0978, 0xFFFFFD7FFFDFEB7C, 0x00000000) = 0
close(3)					= 0
mmap(0x00000000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF130000
memcntl(0xFFFFFD7FFF140000, 452608, MC_ADVISE, MADV_WILLNEED, 0, 0) = 0
stat("/opt/GCC-7.2.0.x64/lib/amd64/libnsl.so.1", 0xFFFFFD7FFFDFE7E0) Err#2 ENOENT
stat("/lib/64/libnsl.so.1", 0xFFFFFD7FFFDFE7E0)	= 0
resolvepath("/lib/64/libnsl.so.1", "/lib/amd64/libnsl.so.1", 1023) = 22
open("/lib/64/libnsl.so.1", O_RDONLY)		= 3
mmapobj(3, MMOBJ_INTERPRET, 0xFFFFFD7FFF300950, 0xFFFFFD7FFFDFE76C, 0x00000000) = 0
close(3)					= 0
mmap(0x00000000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF120000
memcntl(0xFFFFFD7FFED90000, 170264, MC_ADVISE, MADV_WILLNEED, 0, 0) = 0
mmap(0x00010000, 24576, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANON|MAP_ALIGN, -1, 0) = 0xFFFFFD7FFF110000
getcontext(0xFFFFFD7FFFDFF200)
getrlimit(RLIMIT_STACK, 0xFFFFFD7FFFDFF560)	= 0
getpid()					= 26560 [26559]
lwp_private(0, 0, 0xFFFFFD7FFF112A40)		= 0x00000000
setustack(0xFFFFFD7FFF112AE8)
sysconfig(_CONFIG_STACK_PROT)			= 3
sigfillset(0xFFFFFD7FFF2E8E50)			= 0
sysi86(SI86FPSTART, 0xFFFFFD7FFFDFFA7C, 0x0000133F, 0x00001F80) = 0x00000001
fstat(1, 0xFFFFFD7FFFDFF970)			= 0
fstat(2, 0xFFFFFD7FFFDFF970)			= 0
schedctl()					= 0xFFFFFD7FFF10D000
sigaction(SIGPIPE, 0xFFFFFD7FFFDFF9B0, 0xFFFFFD7FFFDFFA30) = 0
resolvepath("./uv_tests", "uv_tests", 1024)	= 8
getcwd("/home/myuser/libuv/build", 1024) = 0
port_create(0)					= 0
fcntl(3, F_GETFD, 0xFFFFFF10D28A74C0)		= 0
fcntl(3, F_SETFD, 0x00000001)			= 0
pipe([4,5], 0)					= 0
fcntl(4, F_GETFD, 0xFFFFFF10D28A74C0)		= 0
fcntl(4, F_SETFD, 0x00000001)			= 0
fcntl(5, F_GETFD, 0xFFFFFF10D28A74C0)		= 0
fcntl(5, F_SETFD, 0x00000001)			= 0
write(5, " *", 1)				= 1
pipe([6,7], 0)					= 0
fcntl(6, F_GETFD, 0xFFFFFF10D28A74C0)		= 0
fcntl(6, F_SETFD, 0x00000001)			= 0
fcntl(7, F_GETFD, 0xFFFFFF10D28A74C0)		= 0
fcntl(7, F_SETFD, 0x00000001)			= 0
fcntl(6, F_GETFL)				= 2
fcntl(6, F_SETFL, FWRITE|FNONBLOCK)		= 0
fcntl(7, F_GETFL)				= 2
fcntl(7, F_SETFL, FWRITE|FNONBLOCK)		= 0
brk(0x008F1B70)					= 0
brk(0x008F5B70)					= 0
pipe([8,9], 0)					= 0
fcntl(8, F_GETFD, 0xFFFFFF10D28A74C0)		= 0
fcntl(8, F_SETFD, 0x00000001)			= 0
fcntl(9, F_GETFD, 0xFFFFFF10D28A74C0)		= 0
fcntl(9, F_SETFD, 0x00000001)			= 0
fcntl(8, F_GETFL)				= 2
fcntl(8, F_SETFL, FWRITE|FNONBLOCK)		= 0
fcntl(9, F_GETFL)				= 2
fcntl(9, F_SETFL, FWRITE|FNONBLOCK)		= 0
open("test/fixtures/empty_file", O_RDONLY|O_NDELAY|O_LARGEFILE) = 10
fcntl(10, F_SETFD, 0x00000001)			= 0
fstat(10, 0xFFFFFD7FFFDFF7D0)			= 0
close(10)					= 0
sysconfig(_CONFIG_PAGESIZE)			= 4096
priocntlsys(1, 0xFFFFFD7FFFDFF710, 3, 0xFFFFFD7FFFDFF830, 0) = 26560
priocntlsys(1, 0xFFFFFD7FFFDFF690, 1, 0xFFFFFD7FFFDFF790, 0) = 5
priocntlsys(1, 0xFFFFFD7FFFDFF650, 0, 0xFFFFFD7FFF2E4588, 0) = 5
mmap(0x00000000, 131072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF0EC000
mmap(0x00000000, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFF0D0000
sigaction(SIGCANCEL, 0xFFFFFD7FFFDFF440, 0x00000000) = 0
mmap(0x00000000, 2088960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_NORESERVE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFEED1000
mmap(0x00010000, 65536, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANON|MAP_ALIGN, 4294967295, 0) = 0xFFFFFD7FFEEC0000
uucopy(0xFFFFFD7FFFDFF440, 0xFFFFFD7FFF0CEFE8, 24) = 0
lwp_create(0xFFFFFD7FFFDFF4F0, LWP_SUSPENDED, 0xFFFFFD7FFFDFF4EC) = 2
/1:	lwp_continue(2)					= 0
/2:	lwp_create()	(returning as new lwp ...)	= 0
/2:	setustack(0xFFFFFD7FFEEC02E8)
/1:	mmap(0x00000000, 2088960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_NORESERVE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFEB91000
/2:	schedctl()					= 0xFFFFFD7FFF10D010
/1:	uucopy(0xFFFFFD7FFFDFF440, 0xFFFFFD7FFED8EFE8, 24) = 0
/1:	lwp_create(0xFFFFFD7FFFDFF4F0, LWP_SUSPENDED, 0xFFFFFD7FFFDFF4EC) = 3
/1:	lwp_continue(3)					= 0
/3:	lwp_create()	(returning as new lwp ...)	= 0
/1:	mmap(0x00000000, 2088960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_NORESERVE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFE992000
/3:	setustack(0xFFFFFD7FFEEC0AE8)
/1:	uucopy(0xFFFFFD7FFFDFF440, 0xFFFFFD7FFEB8FFE8, 24) = 0
/3:	schedctl()					= 0xFFFFFD7FFF10D020
/1:	lwp_create(0xFFFFFD7FFFDFF4F0, LWP_SUSPENDED, 0xFFFFFD7FFFDFF4EC) = 4
/4:	lwp_create()	(returning as new lwp ...)	= 0
/1:	lwp_continue(4)					= 0
/4:	setustack(0xFFFFFD7FFEEC12E8)
/1:	mmap(0x00000000, 2088960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_NORESERVE|MAP_ANON, 4294967295, 0) = 0xFFFFFD7FFE793000
/4:	schedctl()					= 0xFFFFFD7FFF10D030
/1:	uucopy(0xFFFFFD7FFFDFF440, 0xFFFFFD7FFE990FE8, 24) = 0
/1:	lwp_create(0xFFFFFD7FFFDFF4F0, LWP_SUSPENDED, 0xFFFFFD7FFFDFF4EC) = 5
/1:	lwp_continue(5)					= 0
/5:	lwp_create()	(returning as new lwp ...)	= 0
/4:	lwp_park(0x00000000, 0)				= 0
/5:	setustack(0xFFFFFD7FFEEC1AE8)
/1:	lwp_unpark(4)					= 0
/5:	schedctl()					= 0xFFFFFD7FFF10D040
/4:	open("test/fixtures/empty_file", O_RDONLY|O_NDELAY|O_LARGEFILE) = 10
/1:	port_associate(3, 4, 0x00000006, 0x00000001, 0x00000000) = 0
/4:	fcntl(10, F_SETFD, 0x00000001)			= 0
/1:	port_associate(3, 4, 0x00000008, 0x00000001, 0x00000000) = 0
/4:	fstat(10, 0xFFFFFD7FFEB8FD70)			= 0
/4:	close(10)					= 0
/4:	write(9, "\0", 1)				= 1
/1:	port_getn(3, 0xFFFFFD7FFFDF99A0, 1024, 1, 0x00000000) = 0 [1]
/1:	read(8, "\0", 1024)				= 1
Assertion failed in /1:	write(2, " A s s e r t i o n   f a".., 20)	= 20
/home/myuser/libuv/test/test-fs.c/1:	write(2, " / H O M E / M Y U S E R".., 60)	= 60
 on line /1:	write(2, "   o n   l i n e  ", 9)		= 9
549/1:	write(2, " 5 4 9", 3)				= 3
: /1:	write(2, " :  ", 2)				= 2
req->result == UV_ENOTDIR/1:	write(2, " r e q - > r e s u l t  ".., 25)	= 25

/1:	write(2, "\n", 1)				= 1
/1:	sigaction(SIGABRT, 0x00000000, 0xFFFFFD7FFFDF9410) = 0
/1:	sigaction(SIGABRT, 0xFFFFFD7FFFDF9350, 0xFFFFFD7FFFDF93D0) = 0
/1:	lwp_sigmask(SIG_SETMASK, 0x00000000, 0x00000000, 0x00000000, 0x00000000) = 0xFFBFFEFF [0xFFFFFFFF]
/1:	lwp_kill(1, SIGABRT)				= 0
/1:	    Received signal #6, SIGABRT [default]
/1:	      siginfo: SIGABRT pid=26560 uid=5093 code=-1
```

**Comment by bnoordhuis** [comment] 2018-01-17 20:06
`errno` is - or is supposed to be - a thread-local variable.  I suppose it's possible your libc's `scandir()` isn't thread-safe somehow.

**Comment by bnoordhuis** [comment] 2018-04-12 14:07
I'm closing this out, seeing there's been no movement on this and OpenIndiana not being a supported platform.  If you figure out what the issue is and there is something libuv can do to improve things, let me know.

**Closed by bnoordhuis** 2018-04-12 14:07 UTC
Labels: solaris, test
