### ISSUE TITLE
mv: rename src/.deps/libuv_la-fs-poll.Tpo to src/.deps/libuv_la-fs-poll.Plo: No such file or directory

### ISSUE THREAD

**Issue by nevernet** [libuv/libuv#644] opened 2015-12-09 12:40 UTC
details:

```
cd /Users/qinxin/neovim/.deps/build/src/libuv-build && /Applications/Xcode.app/Contents/Developer/usr/bin/make V=1 install
/bin/sh ./libtool  --tag=CC   --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DPACKAGE_NAME=\"libuv\" -DPACKAGE_TARNAME=\"libuv\" -DPACKAGE_VERSION=\"1.7.3\" -DPACKAGE_STRING=\"libuv\ 1.7.3\" -DPACKAGE_BUGREPORT=\"https://github.com/libuv/libuv/issues\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libuv\" -DVERSION=\"1.7.3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBDL=1 -DHAVE_LIBPTHREAD=1 -I. -I/Users/qinxin/neovim/.deps/build/src/libuv  -I/Users/qinxin/neovim/.deps/build/src/libuv/include -I/Users/qinxin/neovim/.deps/build/src/libuv/src  -I/Users/qinxin/neovim/.deps/build/src/libuv/src/unix  -g -O2 -fvisibility=hidden -g -std=gnu89 -pedantic -Wall -Wextra -Wno-unused-parameter   -D_DARWIN_USE_64_BIT_INODE=1 -D_DARWIN_UNLIMITED_SELECT=1   -g -O2 -fvisibility=hidden -g -std=gnu89 -pedantic -Wall -Wextra -Wno-unused-parameter -MT src/libuv_la-fs-poll.lo -MD -MP -MF src/.deps/libuv_la-fs-poll.Tpo -c -o src/libuv_la-fs-poll.lo `test -f 'src/fs-poll.c' || echo '/Users/qinxin/neovim/.deps/build/src/libuv/'`src/fs-poll.c
mv -f src/.deps/libuv_la-fs-poll.Tpo src/.deps/libuv_la-fs-poll.Plo
mv: rename src/.deps/libuv_la-fs-poll.Tpo to src/.deps/libuv_la-fs-poll.Plo: No such file or directory
make[4]: *** [src/libuv_la-fs-poll.lo] Error 1
make[3]: *** [build/src/libuv-stamp/libuv-install] Error 2
make[2]: *** [CMakeFiles/libuv.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [deps] Error 2
```

**Comment by nevernet** [comment] 2015-12-09 12:40
and also i have been tried latest version of libuv, and got same error as before.

**Comment by bnoordhuis** [comment] 2015-12-09 12:44
I see you reported https://github.com/neovim/neovim/issues/3806 as well.  It looks like a neovim issue to me, unless you get the same error with the v1.x branch from this repo.

**Comment by saghul** [comment] 2015-12-09 13:05
Closing as it's not an error within libuv, but related to how neovim does the build. (I just tried to compile v1.x on OSX with autotools, no problem there)

**Closed by saghul** 2015-12-09 13:05 UTC

**Comment by nevernet** [comment] 2015-12-09 13:46
sorry , i have been tried to build libuv separate (clone latest version from here, and build it ) and got same error.

```
sh autogen.sh
./configure
make
```

**Comment by saghul** [comment] 2015-12-09 14:22
Can you paste the entire output?

**Comment by nevernet** [comment] 2016-05-15 13:23
```
  libuv git:(v1.x) make
  CC       src/libuv_la-fs-poll.lo
mv: rename src/.deps/libuv_la-fs-poll.Tpo to src/.deps/libuv_la-fs-poll.Plo: No such file or directory
make: *** [src/libuv_la-fs-poll.lo] Error 1

**Comment by saghul** [comment] 2016-05-15 13:31
I cannot reproduce this. What versions of autotools are you using? How did you install it?

**Comment by nevernet** [comment] 2016-05-15 13:31
@saghul Could you tell me when and how the *.Tpo will be generated?

**Comment by saghul** [comment] 2016-05-15 13:32
I have no idea. It's autotools who does that.

**Comment by nevernet** [comment] 2016-05-15 13:33
```
libuv git:(v1.x) autoconf -V
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```

**Comment by nevernet** [comment] 2016-05-15 13:34
```
ibuv git:(v1.x) libtool --version
ltmain.sh (GNU libtool) 2.2.6b
Written by Gordon Matzigkeit <gord@gnu.ai.mit.edu>, 1996

Copyright (C) 2008 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by nevernet** [comment] 2016-05-15 13:34
```
libuv git:(v1.x) automake --version
automake (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
```

**Comment by nevernet** [comment] 2016-05-15 13:35
@saghul  i have been posted related tools info, please help me checked. 

install libuv by following steps:
```
sh autogen.sh
./configure
make
...
```

**Comment by nevernet** [comment] 2016-05-15 13:57
@saghul i have been solved this issue by upgrade the version of libtool. 
the real reason is the conflicts of my local libtool. 

default libtool is /usr/local/bin/libtool, but version is 2.2.x
after i install new version of libtool via brew,  but the libtool is still not linked to the "brew libtool"

solved it by following commands:
```
cp /usr/local/bin/libtool /usr/local/bin/libtool.bak
cp /usr/local/bin/libtoolize /usr/local/bin/libtoolize.bak

ln -sf /usr/local/Cellar/libtool/2.4.6/bin/glibtool /usr/local/bin/libtool
ln -sf /usr/local/Cellar/libtool/2.4.6/bin/glibtoolize /usr/local/bin/libtoolize
ln -sf /usr/local/Cellar/libtool/2.4.6/bin/glibtool /usr/local/bin/glibtool
ln -sf /usr/local/Cellar/libtool/2.4.6/bin/glibtoolize /usr/local/bin/glibtoolize
```
