### ISSUE TITLE
Add support to release the socket handle

### ISSUE THREAD

**Issue by Matheus28** [libuv/libuv#510] opened 2015-09-06 01:31 UTC
There's the `uv_tcp_open` function, which allows us to pass a file descriptor to libuv and let it take control of it. What I'd like to request would be a function to get back control of the socket.

The use case that I have for this is having one loop that reads some data from the socket, then based on the data it receives, move it to a specific loop (that runs on another thread).

**Comment by saghul** [comment] 2015-09-07 10:02
This is basically #390. Right now there is a way to do this, but it works on Unix ony:

- Get the fd with `uv_fileno`
- Duplicate the fd with `dup`
- Close the handle with `uv_close`

You can now take the duplicated fd and open it in another handle with `uv_tcp_open`.

I'm going to close this as a duplicate of #390.

**Closed by saghul** 2015-09-07 10:02 UTC

**Comment by Matheus28** [comment] 2015-09-07 10:55
Alright. Thank you.
