### ISSUE TITLE
Better error when a file descriptor is watched twice

### ISSUE THREAD

**Issue by Fishrock123** [libuv/libuv#1172] opened 2016-12-16 19:29 UTC
Currently this causes an assertion failure crash as described in this node issue: https://github.com/nodejs/node/issues/3604

It's been a while since there was action on the Node.js issue, so i thought it would be a good idea to bring it over here for visibility.

**Comment by bnoordhuis** [comment] 2016-12-19 12:20
It's not as easy to fix as one might think.

Option 1 is to make `uv__io_start()` and `uv__io_stop()` fallible but I expect that will shift the abort to the caller in many cases, simply because there is no way forward on error.

Option 2 is to support multiplexing.  We can probably do that without breaking ABI but it's going to be a lot of work and stands a reasonable chance of introducing regressions.

**Comment by saghul** [comment] 2016-12-21 22:07
FWIW, I'd like to see Option 2 implemented for v2 for example.

**Comment by txdv** [comment] 2016-12-22 07:25
That seems like a change with no real benefit to me.

Why would someone want to watch one file descriptor multiple times?

Also, should this work across two different loops? That would make the implementation even harder.

**Comment by saghul** [comment] 2016-12-22 08:30
> Why would someone want to watch one file descriptor multiple times?

To watch for different events.  Some libraries offer functions for watching fds for readability / writability, and it's easier to work with those by using different poll handles, for example.

Also, libev did this, so porting an application is easier if our semantics are more aligned.

Last, failing with an assert is just ugly.

> Also, should this work across two different loops? That would make the implementation even harder.

Not it won't. Different loops have different uv__io_t arrays, so events would be triggered in both loops just like now. No problem there.

**Comment by JendaPlhak** [comment] 2017-03-07 10:49
Any progress being made in this? It causing us great deal of trouble at the moment :-(

**Comment by txdv** [comment] 2017-03-07 14:25
Doesn't look like anyone is working on this.

**Comment by saghul** [comment] 2017-03-08 11:07
@JendaPlhak Nope. But PRs are welcome if you are up for it!

**Comment by gireeshpunathil** [comment] 2018-04-11 10:08
@bnoordhuis - I guess your option 2 is about allowing multiple watchers for the same fd right? By not making the `fd` as the primary key for the watcher list, instead bloating the list into an array of structures, with each entry can have multiple fd-watcher pairs, and processes every entry for an event on the fd. 

It looks great to me, and may not have side effects.

BTW, I tried asserting `assert(loop->watchers[w->fd] == NULL)` in uv__io_start but it caused a good number of libuv tests to fail.

**Comment by gireeshpunathil** [comment] 2018-05-28 09:53
given the complexity involved in a proper fix for this corner case issue, as a pragmatic approach can we document the behavior and resolve this? if maintainers agree, I can come up with a write up. thanks.

**Comment by Fishrock123** [comment] 2019-08-10 03:09
Sounds like this is a structural issue - maybe addressable in libuv 2?

**Closed** 2020-12-28 16:51 UTC
Labels: feature-request
