### ISSUE TITLE
2 tests in test-spawn fail

### ISSUE THREAD

**Issue by ff2000** [libuv/libuv#40] opened 2014-12-05 16:14 UTC
Gentoo Linux, libuv-1.0.1
model: Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz

=============================================================

[%  72|+ 177|-   0|T   0|S   0]: spawn_reads_child_path
`spawn_reads_child_path` failed: exit code 6
Output from process `spawn_reads_child_path`:
exit_cb
Assertion failed in /var/tmp/portage/dev-libs/libuv-1.0.1/work/libuv-1.0.1/test/test-spawn.c on line 66: exit_status == 1

=============================================================

[%  75|+ 183|-   1|T   0|S   0]: spawn_setuid_setgid
`spawn_setuid_setgid` failed: exit code 6
Output from process `spawn_setuid_setgid`:
Assertion failed in /var/tmp/portage/dev-libs/libuv-1.0.1/work/libuv-1.0.1/test/test-spawn.c on line 1054: r == 0

=============================================================

[% 100|+ 241|-   2|T   0|S   0]: Done.

**Comment by saghul** [comment] 2015-01-28 21:33
Tentatively closing since this seems fixed. None of the Jenkins slaves are able to reproduce it.

If it fails again, please ask and I'll reopen :-)

**Closed by saghul** 2015-01-28 21:33 UTC
