### ISSUE TITLE
windows: uv_pipe_getpeername() behaves differently than on unix

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#246] opened 2015-03-05 21:54 UTC
See https://github.com/iojs/io.js/pull/956#issuecomment-77457620

In a nutshell: calling `uv_pipe_getpeername()` on a client socket on UNIX returns the path to the server socket.  On Windows, it seems to return an empty string.

/cc @txdv

**Comment by saghul** [comment] 2015-03-06 08:32
Can you try this (untested) patch? https://github.com/saghul/libuv/commit/f67b4c8753b9309c4d6a9e8de55f5726940d57cd

**Comment by txdv** [comment] 2015-03-06 11:40
I thought I had everything covered in my testcase, sorry. I'll check it out tomorrow in the morning.

**Comment by bnoordhuis** [comment] 2015-03-21 13:22
Sorry for the delay: https://jenkins-iojs.nodesource.com/view/iojs/job/iojs+any-pr+multi/357/

That's iojs/io.js@99c79f8 + iojs/io.js#956 + bnoordhuis/io.js@ea5a853 and that's libuv/libuv@34da61b + saghul/libuv@f67b4c8.  Clear? ;-)

**Comment by saghul** [comment] 2015-03-21 13:54
Doh, libuv fails to compile. I'll re-check the patch, sorry.

**Comment by saghul** [comment] 2015-03-24 00:10
@bnoordhuis I looked deeper into this, but I can't seem to make Windows fail with a libuv test case. Can you please clarify what behavior is not consistent? AFAIS, client sockets (those which do uv_pipe_connect) do have the pipe name when doing uv_pipe_getpeername, see the checks in this function: https://github.com/libuv/libuv/blob/v1.x/test/test-pipe-getsockname.c#L54

I did notice a difference, however: on windows the client callback is executed first and server connection callback after, while on Linux its reversed.

Still, I see correct values. Can you re-test? Or am I missing something?

**Comment by martell** [comment] 2015-06-27 21:39
I tested all the release versions and have determined
pipe_getsockname_blocking was broken between 1.2.1 and 1.3.0

**Comment by martell** [comment] 2015-07-09 23:46
@saghul have you looked further into this?
@txdv might know more as he is the author of the commit :)

**Comment by saghul** [comment] 2015-07-10 06:17
I did review the code, but couldn't reproduce the issue.

**Comment by martell** [comment] 2015-07-10 06:22
So pipe_getsockname_blocking passes the testcase for you on windows?

It's broken for me using mingw-w64

**Comment by saghul** [comment] 2015-07-10 07:14
@martell it does pass using MSVC, didn't try with MinGW. The original report came from an issue seen in iojs, which is always compiled with MSVC.

**Comment by martell** [comment] 2015-07-11 16:08
@saghul I see :)
I'll continue the discussion over on #264 then as this is not known to be related :)

**Comment by saghul** [comment] 2015-09-11 08:57
@bnoordhuis ping?

**Comment by saghul** [comment] 2016-09-16 06:36
Closing. Feel free to reopen if you manage to reproduce it.

**Closed by saghul** 2016-09-16 06:36 UTC
Labels: bug
