### ISSUE TITLE
uv_fs_mkstemp

### ISSUE THREAD

**Issue by flowlo** [libuv/libuv#322] opened 2015-04-20 12:33 UTC
As far as I see from the API docs, only [creating temporary *directories*](http://docs.libuv.org/en/stable/fs.html#c.uv_fs_mkdtemp) is supported.

I'd like to have `libuv` fully support `mktemp` (see [`mkstemp`](http://linux.die.net/man/3/mkstemp) and [`_mktemp_s`](https://msdn.microsoft.com/en-us/library/t8ex5e91.aspx)). That means creating single files too, with patterns and whatnot.

In case this get's accepted, I'd be willing to submit a PR.

**Comment by saghul** [comment] 2015-04-20 14:50
This would be a welcome addition, someone did ask for it in the past. Feel free to write the PR, and thanks for volunteering!

**Comment by stevengj** [comment] 2015-08-19 20:23
In case it is helpful, here is a Windows equivalent of `mktemp` (from JuliaLang/julia#12699):
```C
char *my_mktemp(char *fname)
{
#ifdef _WIN32
    size_t wlen = MultiByteToWideChar(CP_UTF8, 0, fname, -1, NULL, 0);
    if (!wlen) return NULL;
    wchar_t *fname_w = (wchar_t*)alloca(wlen*sizeof(wchar_t));
    if (!MultiByteToWideChar(CP_UTF8, 0, fname, -1, fname_w, wlen) ||
        !_wmktemp(fname_w) ||
        !WideCharToMultiByte(CP_UTF8, 0, fname_w, -1, fname, strlen(fname)+1,
                             NULL, NULL))
        return NULL;
    return fname;
#else
    return mktemp(fname);
#endif
}
```

**Comment by saghul** [comment] 2015-08-19 20:25
@stevengj Thanks! Any chance you can submit it as a Pull Request, with a test or two? :-)

**Comment by stevengj** [comment] 2015-08-19 20:28
Is there a Windows equivalent of `mkstemp`, i.e. which "atomically" picks a filename, creates it, and returns the open file descriptor?  I guess [GetTempFileNameW](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364991(v=vs.85).aspx) actually creates the file too, although it closes it, but it is not quite the same in semantics to `mkstemp` as far as the filename is concerned.

**Comment by stevengj** [comment] 2015-08-19 20:29
@saghul, one difficulty is that I don't actually use Windows, and I only program for Windows via cross-compilation.   I tested my Julia code cited above via AppVeyor, but it doesn't look like you are using AppVeyor/Travis CI with libuv, which makes me a little nervous about submitting a PR.

**Comment by saghul** [comment] 2015-08-19 21:11
> Is there a Windows equivalent of mkstemp, i.e. which "atomically" picks a filename, creates it, and returns the open file descriptor? I guess GetTempFileNameW actually creates the file too, although it closes it, but it is not quite the same in semantics to mkstemp as far as the filename is concerned.

Not that I'm aware of. We probably have to manually do it, like `uv_fs_mkdtemp`.

> one difficulty is that I don't actually use Windows (I only program for Windows via cross-compilation). I tested my Julia code cited above via AppVeyor, but it doesn't look like you are using AppVeyor/Travis CI with libuv, which makes me a little nervous about submitting a PR.

We do have a Jenkins CI, which I can trigger so the Windows part will be tested, don't worry :-)

**Comment by stevengj** [comment] 2015-08-20 02:28
(I really like seeing automated multi-platform test results for every PR; you should think about setting it up.)

**Comment by saghul** [comment] 2015-08-20 07:07
We are using the infrastructure provided by Node, which is being worked on right now, so we should eventually have it.

**Comment by flowlo** [comment] 2015-08-20 13:05
@stevengj Yup, the two Windows APIs mentioned so far are not a suitable alternative to `mkstemp`.

Just compare those portions:

> The `mkstemp()` function generates a unique temporary filename from template, creates and opens the file, and returns an open file descriptor for the file.

vs

> The `_mktemp_s` function creates a unique file name by modifying the template argument, so that after the call, the template pointer points to a string containing the new file name.

vs

> If `GetTempFileNameW` succeeds, the return value specifies the unique numeric value used in the temporary file name. If the uUnique parameter is nonzero, the return value specifies that same number.

Also, I checked [StackOverflow](http://stackoverflow.com/questions/6036227/), where a found [this bug at MinGW](http://sourceforge.net/p/mingw/bugs/2003/) that might help. Also, `uv_fs_mkdtemp` and [`fs__mkdtemp`](https://github.com/libuv/libuv/blob/df62b54aa2b3d916ca442ee84f0678129a848c4f/src/win/fs.c#L752-L807) are releveant.

**Comment by stevengj** [comment] 2015-08-20 14:10
Although `mktemp` is easier to implement, it's not clear to me that libuv should provide this; it seems better to provide only `uv_fs_mkstemp`, assuming one can be implemented (perhaps along the lines of the MinGW patch @flowlo linked).   Given a working `mkstemp`, is there any need for `mktemp`?

**Comment by saghul** [comment] 2015-08-20 15:21
@stevengj Indeed, we'd want mkstemp.

**Comment by sam-github** [comment] 2015-08-20 19:28
@orangemocha do you have an opinion on best way to implement a `mkstemp()` equivalent on Windows?

**Comment by orangemocha** [comment] 2015-08-21 01:33
The closest thing in Windows would be GetTempFileNameW, but it doesn't support the same template semantics. If you absolutely wanted those, I am afraid you'd have to re-implement it from scratch.

Just an idea: you could define an API that has less strict expectations on the name of the resulting file, leaving more flexibility for the implementation. It could take a prefix, but not a full template, and only a portion of the prefix might be used. This way it could be implemented in terms of GetTempFileName on Windows and mkstemp on Posix.

**Comment by sam-github** [comment] 2015-08-21 05:36
I like that, there is nothing so great about having to put the `XXXXXX` in exactly as it is done in `mkstemp()`. Can you point at the docs for `GetTempFileName()`?

**Comment by saghul** [comment] 2015-08-21 08:27
> The closest thing in Windows would be GetTempFileNameW, but it doesn't support the same template semantics. If you absolutely wanted those, I am afraid you'd have to re-implement it from scratch.
> 
> Just an idea: you could define an API that has less strict expectations on the name of the resulting file, leaving more flexibility for the implementation. It could take a prefix, but not a full template, and only a portion of the prefix might be used. This way it could be implemented in terms of GetTempFileName on Windows and mkstemp on Posix.

We have aligned ourselves with the Unix side in the past (in the fs APIs), and we kinda already have the bulk of the work in here: https://github.com/libuv/libuv/blob/v1.x/src/win/fs.c#L753 I'd go with reimplementing `mkstemp`.

**Comment by orangemocha** [comment] 2015-08-21 09:25
@sam-github : https://msdn.microsoft.com/en-us/library/windows/desktop/aa364991(v=vs.85).aspx

**Comment by sam-github** [comment] 2015-09-05 00:31
@saghul we align ourselves with unix, but not when that means it is difficult or impossible to do it on Windows (uv has no fork(2), for example), in that case the API tends towards a higher-level: does what is useful, not just some system call primitive.

I'll take a look at the Windows docs and see if I can propose a usable api that consists of the commonalities of mkstemp() and GetTempFileName()

**Comment by saghul** [comment] 2015-09-05 09:04
@sam-github I meant specifically in the fs APIs. We already have `mkdtemp`, which is manually implemented on Windows based on OpenBSD's (IIRC) implementation. I don't see why we should take any compromise here, if we can just do the same.

Unless I'm missing something, that is :-)

**Comment by saghul** [comment] 2016-05-17 10:46
Closing in favor of #729.

**Closed by saghul** 2016-05-17 10:46 UTC
Labels: help-wanted

**Comment by stevengj** [comment] 2016-05-17 14:24
@saghul, the ordinary github practice would be to have the PR automatically close this issue when it is merged.  (This will happen if the commit or the issue description includes something like `closes #322`.)

**Comment by saghul** [comment] 2016-05-17 14:56
I don't disagree, but I also don't like to see duplicates.

**Comment by stevengj** [comment] 2016-05-17 16:38
A PR is not a duplicate of an issue; it is the solution to the issue.
