### ISSUE TITLE
vcbuild.bat Building on Windows x64

### ISSUE THREAD

**Issue by vsberm** [libuv/libuv#1318] opened 2017-04-26 03:30 UTC
use libuv-1.11.0, Visual Studio 2015 (Update 3).
Running command `vcbuild.bat release x64` leads to:
```
E:\libuv-1.11.0>vcbuild.bat release x64
['-Dtarget_arch=x64', '-Duv_library=static_library', '.\\uv.gyp', '-I', '.\\comm
on.gypi', '--depth=.', '-Dhost_arch=x64']
Traceback (most recent call last):
  File "gyp_uv.py", line 94, in <module>
    run_gyp(gyp_args)
  File "gyp_uv.py", line 38, in run_gyp
    rc = gyp.main(args)
  File ".\build\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File ".\build\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File ".\build\gyp\pylib\gyp\generator\ninja.py", line 2476, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
KeyError: 'Debug_x64'
Failed to create vc project files.
```

**Comment by vsberm** [comment] 2017-04-26 04:00
if use command `vcbuild.bat release AMD64`
create libuv.lib after, run command `dumpbin  /headers libuv.lib`, the libuv.lib is not x64
```
E:\libuv-1.11.0\out\Release\obj>dumpbin  /headers libuv.lib
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file libuv.lib

File Type: LIBRARY

ANON OBJECT HEADER VALUES
               1 version
             14C machine (x86)
        59001974 time date stamp Wed Apr 26 11:52:20 2017
                 ClassID: {0CB3FE38-D9A5-4DAB-AC9B-D6B6222653C2}
           27BEC size
               0 flags

ANON OBJECT HEADER VALUES
               1 version
             14C machine (x86)
        59001974 time date stamp Wed Apr 26 11:52:20 2017
                 ClassID: {0CB3FE38-D9A5-4DAB-AC9B-D6B6222653C2}
           25B7C size
               0 flags
```

**Comment by saghul** [comment] 2017-04-26 06:23
> if use command vcbuild.bat release AMD64
> create libuv.lib after, run command dumpbin /headers libuv.lib, the libuv.lib is not x64

That's because "AMD64" is not an arch our script recognizes, so it falls back to the default, x86.

As for yor original issue, I've never seen it before :-S Do you have the latest GYP version?

**Comment by moteus** [comment] 2017-05-23 11:00
When i try build with MSVC 2015 I have to set GYP_MSVS_VERSION like `set GYP_MSVS_VERSION=2015`.

**Comment by saghul** [comment] 2017-05-29 19:14
@moteus is that the case also with the latest GYP version?

**Comment by moteus** [comment] 2017-05-30 09:07
I use [a478c1a commit](https://chromium.googlesource.com/external/gyp/+/a478c1ab51ea3e04e79791ac3d1dad01b3f57434) of gyp. 
But also I have MSVC 2010 installed on my system.

**Comment by bzoz** [comment] 2017-06-29 10:09
@moteus sorry, I cannot reproduce - with both VS2015 and 2010 installed, `vcbuild release x64` works as expected for libuv 1.11 and that GYP commit.

Is there anything specific about your configuration? Windows version? Also, have you tried to reproduce this whit a freshly downloaded clean copy of libuv?

**Comment by moteus** [comment] 2017-06-29 10:21
I run `VS2015 x64 Native Tools Command Prompt`
then do 
```
git clone https://github.com/libuv/libuv -b v1.12.0
cd libuv
vcbuild release x64 shared
```
I got 
```
f:\tmp\libuv>vcbuild release x64 shared
git clone https://chromium.googlesource.com/external/gyp build/gyp
Cloning into 'build/gyp'...
remote: Sending approximately 11.43 MiB ...
remote: Total 17913 (delta 11272), reused 17913 (delta 11272)
Receiving objects: 100% (17913/17913), 11.43 MiB | 109.00 KiB/s, done.
Resolving deltas: 100% (11272/11272), done.
['-Dtarget_arch=x64', '-Duv_library=shared_library', '.\\uv.gyp', '-I', '.\\common.gypi', '--depth=.', '-Dhost_arch=x64']
Project files generated.
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools. Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [f:\tmp\libuv\libuv.vcxproj]
```
After that I did `set GYP_MSVS_VERSION=2015` and launch same command and all builds fine.

**Comment by bzoz** [comment] 2017-06-29 13:45
Can you please provide the output of `env` on your developer command prompt?

**Comment by moteus** [comment] 2017-06-29 14:10
```
ALLUSERSPROFILE=C:\ProgramData
CommandPromptType=Native
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramFiles=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
ComSpec=C:\Windows\system32\cmd.exe
Framework40Version=v4.0
FrameworkDIR64=C:\Windows\Microsoft.NET\Framework64
FrameworkDir=C:\Windows\Microsoft.NET\Framework64
FrameworkVersion64=v4.0.30319
FrameworkVersion=v4.0.30319
INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\\shared;C:\Program Files (x86)\Windows Kits\8.1\include\\um;C:\Program Files (x86)\Windows Kits\8.1\include\\winrt;
LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;
LIBPATH=C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral;\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral;
LOCALAPPDATA=C:\Users\alexey\AppData\Local
NETFXSDKDir=C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\
NUMBER_OF_PROCESSORS=4
OS=Windows_NT
Path=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\MSBuild\14.0\bin\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Ruby22\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW
Platform=X64
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_ARCHITEW6432=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3c03
ProgramData=C:\ProgramData
ProgramFiles(x86)=C:\Program Files (x86)
ProgramFiles=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SQLANY11=C:\Program Files\SQL Anywhere 11
SQLANYSAMP11=C:\Users\Public\Documents\SQL Anywhere 11\Samples
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\alexey\AppData\Local\Temp
TMP=C:\Users\alexey\AppData\Local\Temp
UCRTVersion=10.0.10240.0
UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
USERNAME=alexey
USERPROFILE=C:\Users\alexey
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
VisualStudioVersion=14.0
VS100COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools\
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\
VSSDK140Install=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\
windir=C:\Windows
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log
WindowsLibPath=C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral
WindowsSDK_ExecutablePath_x64=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\
WindowsSDK_ExecutablePath_x86=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\8.1\
WindowsSDKLibVersion=winv6.3\
WindowsSDKVersion=\
```

**Comment by bzoz** [comment] 2017-06-29 15:46
@moteus what version of VS2010 are you using?

@vsberm does your problem persists after downloading a clean copy of libuv?

**Comment by moteus** [comment] 2017-06-29 15:51
```
Microsoft Visual Studio 2010
Version 10.0.30319.1 RTMRel
Microsoft .NET Framework
Version 4.6.01055 RTMRel

Installed Version: VC Express
```
```
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC>cl -?
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.30319.01 for 80x86
```

**Comment by bzoz** [comment] 2017-06-29 16:08
@moteus, so this is what I think is happening:
 
* Running `vcbuild` from developer prompt makes it skip VS version autodetection. Normally, when it finds Visual Studio it also sets `GYP_MSVS_VERSION` accordingly. But since you have `WindowsSDKDir` set it jumps straight to `uv.sln` generation.
* GYP defaults to VS2010 if no `GYP_MSVS_VERSION` is specified. Try opening your `uv.sln` from VS2010 - it should work
* Finally, VS2010 Express by default does not support 64-bit builds. This is probably why it fails for you and works for me, since I tried this with Professional version

So, as for solution: either define `GYP_MSVS_VERSION` or do not use `Developer Command Prompt`

**Comment by moteus** [comment] 2017-06-29 16:45
I whant build not with msvc 2010 but with 2015.
I know that 2010 express does not support x64.
And yes I can do this when set correct version of `GYP_MSVS_VERSION`.
Like I say I have no big problems with that.
May be problem when buld x86 from 2015 environment. 
It compiles without any error but uses 2010.
In fact I need both variant. So ideal solution will be
use current envirionment.

**Comment by bzoz** [comment] 2017-07-04 10:57
@moteus  Yep, use `GYP_MSVS_VERSION` to force VS version.

@vsberm I'm gonna close the issue. If it still reproduces with clean libuv download feel free to reopen it.

**Closed by bzoz** 2017-07-04 10:57 UTC
