### ISSUE TITLE
Slowdown on `uv_cpu_info`

### ISSUE THREAD

**Issue by H4ad** [libuv/libuv#4098] opened 2023-07-19 02:11 UTC
I first discovered this issue because on https://github.com/nodejs/node/issues/48831

Using the following JS Code, I added several comments to track the issue, you can find them here: https://github.com/h4ad-forks/node/commit/04e1b7956abbd24ffafaaee3bf2abb87b17b243f

```js
// get-report.js
const now = performance.now();
process.report.getReport()
console.log(`Took ${performance.now() - now}ms`);
```
> Just run with: node get-report.js

My output is this one:

```
...
init - 1689736802117
model name: model name	: 
after defines - 1689736802117
after buffers - 1689736802117
after snprintf - 1689736802117
after uv__calloc - 1689736802117
after uv__open_file - 1689736802117
after fgets - 1689736802117
after for ;; - 1689736802117
after uv__open_file /proc/cpuinfo - 1689736802133
inside for - 1689736802133
found - 1689736802133
inside for - 1689736802133
found - 1689736802133
inside for - 1689736802133
found - 1689736802133
inside for - 1689736802133
found - 1689736802133
inside for - 1689736802133
found - 1689736802133
inside for - 1689736802133
found - 1689736802133
inside for - 1689736802133
found - 1689736802133
inside for - 1689736802133
found - 1689736802133
inside for - 1689736802133
found - 1689736802133
inside for - 1689736802133
found - 1689736802133
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
found - 1689736802134
inside for - 1689736802134
buffer: 
parse error - 1689736802134
after for ;; - 1689736802134
on nocpuinfo - 1689736802134
cpu: 31
maxcpu: 32
after for maxcpu - 1689736802661
after uv__free - 1689736802661
after memcpy - 1689736802661
after for cpu < maxcpu - 1689736802661
after uv__free - 1689736802661
...
Took 550.9842159971595ms
```

From what I investigated, I think the problem is in this line:

https://github.com/libuv/libuv/blob/d09441ca03e399fe641da88624c8ea0476967187/src/unix/linux.c#L1808-L1824

This part of the code is very slow as it creates a `uv__open_file` for each CPU on the machine.

* **Version**: 1.45.0
* **Platform**: Linux h4ad 5.15.0-76-generic 83~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bnoordhuis** [comment] 2023-07-19 07:45
What is the goal of your bug report? I believe you understand the change was intentional and therefore not something we'll change back again.

**Comment by H4ad** [comment] 2023-07-19 11:21
I just want to raise some attention to this slowdown to see if there is something that we can do.

If you think this behavior is ok and there is nothing we can do about it, I can close this issue.

**Comment by vtjnash** [comment] 2023-07-19 12:54
https://github.com/libuv/libuv/commit/434eb4b0ac29e853e85562119fda3fa681642f17 It seems working as intended now to me from reading that commit message

**Comment by H4ad** [comment] 2023-07-19 14:23
libuv already does something similar for time:

https://github.com/libuv/libuv/blob/d09441ca03e399fe641da88624c8ea0476967187/src/unix/internal.h#L169-L172

What's the difference in this case?

**Comment by vtjnash** [comment] 2023-07-19 16:19
600ms (over half a second) is a concerning amount of time though. Seems like nearly a kernel bug at that rate, if so.

**Comment by bnoordhuis** [comment] 2023-07-19 22:01
> libuv already does something similar for time:

Because "give me the current time with nanosecond precision" is an operation you may realistically end up doing thousands of times per second. "Give me details on all CPUs"? Not so much.

As to the benchmark (I hesitate to call it that):

> 0,01s user 0,00s system 1% cpu 0,649 total

Vs.

> 0,00s user 0,00s system 98% cpu 0,008 total

Note how during the bad run the system was doing something else for 99% of the recorded time. I suspect you're basically looking at an benchmarking artifact.

Now, if you can reproduce it with e.g. `perf stat -r 500` then yeah, that'd be worrisome - but like Jameson says, you're probably looking at a kernel bug in that case.

Maintainers, feel free to reopen if you feel strongly but I'm going to close this.

**Closed by bnoordhuis** 2023-07-19 22:01 UTC

**Comment by feisuzhu** [comment] 2024-11-12 14:56
Please reopen this, it took me 4000ms to run this.

```
const now = performance.now();
process.report.getReport()
console.log(`Took ${performance.now() - now}ms`);
```

```
root@6c92459bf81a:/# node a.js
Took 3862.274124ms
root@6c92459bf81a:/#
```
