### ISSUE TITLE
uv_cpu_info reads /proc/stat multiple times

### ISSUE THREAD

**Issue by lgf10** [libuv/libuv#3858] opened 2022-12-14 16:28 UTC
We are facing an issue with LXC/LXD, which results in /proc/stat randomly returning an incorrect number of CPUs (we are in contact with the developers of LXC to fix this issue) - i.e. /proc/stat usually lists all 28 cores, but sometimes only lists 4.

This causes an issue in uv_cpu_info: /proc/stat is read multiple times and libuv sensibly expects the CPU count of both reads to match. https://github.com/libuv/libuv/blob/master/src/unix/linux-core.c#L590
Sadly this issue is frequent enough that even reads in quick succession can differ, causing the npm build to fail:
[ERROR] Stderr: 'node: ../deps/uv/src/unix/linux-core.c:615: read_times: Assertion `num == numcpus' failed.

Is there a reason that /proc/stat is read multiple times? If not, we would be willing to contribute a PR that changes uv_cpu_info to only read /proc/stat once. It would be fine for us if uv_cpu_info reads the "wrong" /cpu/stat, as long as the assertion does not fail.

* **Platform**: Linux

**Comment by vtjnash** [comment] 2022-12-14 17:18
Duplicate of https://github.com/libuv/libuv/issues/2351

**Comment by bnoordhuis** [comment] 2022-12-16 12:54
I have an idea of how to fix this but it's going to require something of an overhaul of the current code.

Related: I see we read the CPU speed from `/proc/cpuinfo` on x86 but `/sys/devices/system/cpu/cpu\d+/cpufreq/scaling_cur_freq` on other architectures.

I want to harmonize that so it always uses `scaling_cur_freq` because the values from `cpuinfo` are wrong-ish, they're the base frequency.

On my system `cpuinfo` reports 2.2 GHz for every core, even though two are running at 3.6 Ghz. `scaling_cur_freq` reports the correct values.

If anyone sees problems with that change, please speak up now. :-)

**Comment by bnoordhuis** [comment] 2022-12-18 22:18
@lgf10 can you check if #3861 solves your issue?

**Closed** 2023-01-14 04:08 UTC
