### ISSUE TITLE
[RFC] Extend uv_spawn to set child processor affinity

### ISSUE THREAD

**Issue by bradking** [libuv/libuv#1389] opened 2017-06-28 14:56 UTC
I have a use case where we need to set the processor affinity of child processes.  We don't control the code of the child processes so we can't ask them to set the affinity themselves.  However, it is possible for a parent process to control the affinity of its children when creating them.  This requires support from the process spawn implementation in order to take actions between creating and running the child process:

* On Linux we can `fork`, then call [sched_setaffinity(2)](http://man7.org/linux/man-pages/man2/sched_setaffinity.2.html) in the child, and then `execvp`.
* On Windows we can `CreateProcess` with `CREATE_SUSPENDED`, then call [SetProcessAffinityMask](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686223.aspx) with the child process handle, and then `ResumeThread` the child's main thread. 

I propose to add support for this to `uv_spawn` by extending `uv_process_options_t` and `enum uv_process_flags`  with optional settings to configure child process affinity.  This is similar to the `uid` and `gid` settings we have now.  If this sounds reasonable I can spell out a more detailed proposal for the interface and semantics, and then proceed to implementation.

**Comment by bnoordhuis** [comment] 2017-06-28 18:09
There's an open pull request (#597 - which purely coincidentally I re-reviewed just now) that adds a similar feature to thread APIs.  It would be nice if this and that aren't too dissimilar.

> I propose to add support for this to uv_spawn by extending uv_process_options_t and enum uv_process_flags with optional settings to configure child process affinity.

That sounds like it would break ABI, meaning it can't land in v1.x.  Extending an enum is not a problem, that could go into a minor release, but extending a struct is.

**Comment by bradking** [comment] 2017-06-28 18:35
Thanks for the link.  I'll look at that PR's interface.

We may be able to extend the struct while maintaining ABI compatibility.  The only interface through which libuv accesses a `struct uv_process_options_s` is through the pointer given to `uv_spawn`.  We could extend the structure with additional fields at the end, and then access those fields only if an extra flag is given in the `flags` field.  Clients built against the old struct definition will not populate the extra flag so we won't access beyond the end of the struct they allocated.

**Comment by bnoordhuis** [comment] 2017-06-28 19:07
I'm familiar with the technique; it's been IBM's modus operandi for decades. :-)

The problem is this though: `uv_spawn()` currently asserts when it sees an unknown flag, so code using the new flag will trigger a SIGABRT with older libuv versions.  Lack of foresight, I agree, but here we are.

**Comment by bradking** [comment] 2017-06-28 19:18
> code using the new flag will trigger a SIGABRT with older libuv versions

Yes, and that is better than silently ignoring some flag the caller expects to be honored.  Do we expect a client built against libuv 1.13 to run with libuv 1.12?  If so then how can new features ever be added?   A new API's symbol won't exist in the older `.so`.

The ABI concern is only for the other direction: a client built against libuv 1.12 should be able to run with libuv 1.13.

**Comment by bradking** [comment] 2017-06-28 19:20
Instead of `SIGABRT` on an unknown flag should we fail with `UV_EINVAL` or a similar error?

**Comment by saghul** [comment] 2017-06-28 19:34
> Do we expect a client built against libuv 1.13 to run with libuv 1.12?

Unless it's using a new API yes.



> If so then how can new features ever be added?

If those features break the ABI, we will add them on the next major: 2.0.0.

**Comment by bradking** [comment] 2017-06-28 19:51
> we will add them on the next major: 2.0.0.

Sure, but this discussion is about whether we can add the proposed feature to the 1.x API.  AFAICT we can.

Clients using the new flag in the `uv_process_options_t` `flags` field would qualify as using a new API, so we then wouldn't expect them to work on an older version.  If libuv checks for the new flag before accessing the new struct fields, then we won't access them on older clients and will remain ABI compatible with them.

**Comment by bnoordhuis** [comment] 2017-06-28 22:40
> Do we expect a client built against libuv 1.13 to run with libuv 1.12?

Yes.  Now that I think about it, user code can always check if `uv_version() >= 0x10D00`, but that would need to be well-documented.

> If so then how can new features ever be added? A new API's symbol won't exist in the older .so.

That's detectable at runtime, you can look up the symbol with dlsym().

**Comment by saghul** [comment] 2017-06-29 07:13
> Sure, but this discussion is about whether we can add the proposed feature to the 1.x API. AFAICT we can.
> 
> Clients using the new flag in the uv_process_options_t flags field would qualify as using a new API, so we then wouldn't expect them to work on an older version. If libuv checks for the new flag before accessing the new struct fields, then we won't access them on older clients and will remain ABI compatible with them.

I know we can, that's not the point. Personally (I'm not speaking for every libuv contributor here) I don't see this case as important enough to warrant a ABI compatibility hack. It's a great feature to have, don't get me wrong, but it can happily land in master and arrive with 2.0.

**Comment by bradking** [comment] 2017-07-11 17:57
Moving on to the actual API design, based on the interface in #597, `uv_process_options_t` will gain these fields:

```c
char*  cpumask;
size_t cpumask_size;
```

Each byte in `cpumask` can be either zero (false) or non-zero (true) to indicate whether the corresponding processor at that index is included.

PR #597 also defines a `uv_thread_cpumasksize` function (which I've just suggested renaming to a name that is not "thread"-specific).  With that we can require that `cpumask_size` in `uv_process_options_t` must be at least as large as `uv_thread_cpumasksize` reports.  Client code can detect whether `uv_thread_cpumasksize` returns `-ENOTSUP` to know whether `cpumask` can be used.

`uv_spawn` will use `cpumask` if it is non-NULL.  On supported platforms (e.g. Linux and Windows) it will use the mask to set the processor affinity for the child process.  On platforms where this is not implemented, `uv_spawn` will return `-ENOTSUP`.

**Comment by bnoordhuis** [comment] 2017-07-13 19:18
Sounds reasonable to me.

**Comment by santigimeno** [comment] 2018-02-28 21:16
Closing as https://github.com/libuv/libuv/pull/1527 already landed.

**Closed by santigimeno** 2018-02-28 21:16 UTC
