### ISSUE TITLE
io_uring: possible issue handling CQ overflow

### ISSUE THREAD

**Issue by santigimeno** [libuv/libuv#4598] opened 2024-11-04 14:03 UTC
Refs: https://lore.kernel.org/io-uring/3d913aef-8c44-4f50-9bdf-7d9051b08941@app.fastmail.com/T/#mcddcf299eb2ec40aca4bf8b938067b9682c8eb27

> ... However,
it's worth noting that this will only happen if there's overflow going
on, and presumably only if the overflow list is quite long. That does
indicate a problem with the user of the ring, generally overflow should
not be seen at all. Entirely independent from this backport being buggy,
just wanted to bring it up as it is cause for concern on the application
side.

Refs: https://github.com/nodejs/node/issues/55587

**Comment by justuswilhelm** [comment] 2024-11-06 02:46
The Nix flake-based QEMU VM in the below linked repository reproduces the issue reliably:

https://github.com/justuswilhelm/libuv-kernel-crash-repro

There are some light instructions on how to run it and what results to expect. Please let me know if it works for you or if you have any more questions.

**Comment by santigimeno** [comment] 2024-11-06 09:25
Thanks for all that info an investigation. I'll take a look as soon as I can.

**Comment by bnoordhuis** [comment] 2024-11-06 12:40
Can either of you check how many SQ vs. CQ entries the `io_uring_setup` system call creates (the sq_entries and cq_entries fields in the out param)

Overflow can only happen when SQ entries outnumber CQ entries, right? Otherwise there should always be room in the CQ ring buffer since we don't perform operations that produce more than one CQE per SQE.

strace on my system tells me I get 256 SQEs and 512 CQEs, the opposite of what I just described, and my system indeed doesn't appear to be affected.

**Comment by justuswilhelm** [comment] 2024-11-08 02:38
I've added a full strace to the repro-repo. Here are just the sq entry numbers:

```
sq_entries=64, cq_entries=128
sq_entries=256, cq_entries=512
sq_entries=64, cq_entries=128
sq_entries=256, cq_entries=512
sq_entries=64, cq_entries=128
sq_entries=256, cq_entries=512
```

This is the full log: https://github.com/justuswilhelm/libuv-kernel-crash-repro/blob/main/strace_io_uring_setup.log

Hope it helps!

**Comment by justuswilhelm** [comment] 2024-11-08 03:12
One more thing I have just found out (and suspected):

There's no need to run npm ci to crash the program. You can run this script and it will crash with high likelihood:

```javascript
import { lstat, open } from 'node:fs/promises';

const p = '/etc/os-release';
const o = await open("/dev/stdout", "w");
const w = (msg) => o.write(msg);
const outer = 20;
const inner = 100000;


for (let i = 0; i < outer; i++) {
        const promises = [];
        for (let j = 0; j < inner; j++) {
                promises.push(lstat(p));
        }
        await Promise.all(promises);
        await w(".");
}

await w("\nDone");
```

![image](https://github.com/user-attachments/assets/5e6a6d7b-655f-4a57-b332-7baaa6da425d)


By the way, the problem of uninterruptible processes at least has been solved by updating to Linux 6.11.6 #1-NixOS.

**Comment by bnoordhuis** [comment] 2024-11-08 20:45
Thanks for that. Libuv has overflow handling here:

https://github.com/libuv/libuv/blob/d4ab6fbba4669935a6bc23645372dfe4ac29ab39/src/unix/linux.c#L1220-L1233

But your test case never hits that code path on my machine (checked by placing a breakpoint there in gdb.)

Interestingly, the test case from 30fc896cc (the commit that added overflow handling) also never actually overflows the CQ ring here.

@santigimeno Santi, I'm out of ideas. Now that I think about it, I don't believe I was ever able to hit that overflow that was the cause of https://github.com/neovim/neovim/issues/23595 either.

**Comment by santigimeno** [comment] 2024-11-08 21:44
> Overflow can only happen when SQ entries outnumber CQ entries, right? Otherwise there should always be room in the CQ ring buffer since we don't perform operations that produce more than one CQE per SQE.

I'm not sure this is entirely accurate. From https://manpages.ubuntu.com/manpages/lunar/man3/io_uring_queue_init_params.3.html:

> The SQ ring entries do not impose a limit on the number of  in-flight
       requests  that  the ring can support, it merely limits the number that can be submitted to
       the kernel in one go (batch).
     
So yes, we can enter in overflow state when sending lots of requests, even if the SQ ring is not full at all. In the example from  https://github.com/libuv/libuv/issues/4598#issuecomment-2463673055, the CQ ring is overflowing all the time (the `IORING_SQ_CQ_OVERFLOW` being set). So maybe we should have some kind of backpressure mechanism implemented to  try to avoid this?

**Comment by santigimeno** [comment] 2024-11-08 22:03
> Interestingly, the test case from https://github.com/libuv/libuv/commit/30fc896cc1b5822e9f1eb462587fe4b368a6215c (the commit that added overflow handling) also never actually overflows the CQ ring here.

I guess it depends on the kernel version. I hit that state once. If I increase the number of requests it hits multiple times. I'm pretty sure you have, but have you added: `uv_loop_configure(loop, UV_LOOP_USE_IO_URING_SQPOLL);` ?

**Comment by bnoordhuis** [comment] 2024-11-09 10:48
Oh... I think I misunderstood e78e29c231481683c7e72450eeeb1b75b1109b2c.

The idea was to disable sqpoll by default (because broken) but not disable it entirely, and keep using IORING_OP_EPOLL_CTL (because not broken), and then users can opt into sqpoll at their discretion with `UV_USE_IO_URING=1` if they're confident their kernel is up to the task.

Disabling sqpoll  unless one calls uv_loop_configure is no good because it means node users can never opt into sqpoll, unless node grows a new flag (meh) or starts scanning the environment for UV_USE_IO_URING (really meh.)

Anyway... yes, with UV_LOOP_USE_IO_URING_SQPOLL I see overflows but I already figured it out before that :-)

The kernel's sqpoll thread vacuums up incoming SQEs as fast as we submit them; probably faster than we pull off CQEs from the CQ ring.

I'm not sure if that's actually something we want to fix because the alternative is to push operations to the thread pool, and that's likely slower overall. But, for your consideration: #4601

**Comment by santigimeno** [comment] 2024-11-09 18:42
> The idea was to disable sqpoll by default (because broken) but not disable it entirely, and keep using IORING_OP_EPOLL_CTL (because not broken), and then users can opt into sqpoll at their discretion with `UV_USE_IO_URING=1` if they're confident their kernel is up to the task.

That's exactly what was implemented but using a loop flag instead of checking `UV_USE_IO_URING`, which I think was one of the [proposed](https://github.com/libuv/libuv/pull/4421#issuecomment-2225152035) [solutions](https://github.com/libuv/libuv/pull/4421#issuecomment-2225860128). If you have a concrete proposal to improve things I'm happy to do it, though maybe it's too late now that it has been pushed into a release.

**Comment by bnoordhuis** [comment] 2024-11-09 20:36
Hah, okay, I see that what I wrote was kind of ambiguous:

> having people opt-in through an environment variable or uv_loop_configure(loop, UV_LOOP_USE_IO_URING)?

That "or" was intended as an inclusive OR, not XOR :-)

I'm thinking that it should work like this:

1. `UV_USE_IO_URING=0` disables io_uring completely
2. `UV_USE_IO_URING=1` enables epoll batching _and_ sqpoll
3. No `UV_USE_IO_URING` enables epoll batching but _not_ sqpoll
4. The loop flag works like (2)

The flag should have taken a boolean as an argument, in hindsight, but eh, live and learn.

Alternatively, we could leave epoll batching as an always-on thing and make the environment variable and loop flag only affect sqpoll. Because honestly, it's a pretty good optimization.

**Comment by saghul** [comment] 2024-11-09 22:03
FWIW, I agree with your last paragraph.

**Comment by bnoordhuis** [comment] 2024-11-19 21:33
#4601 came with a pretty dramatic performance regression and we're not really doing anything wrong in the first place so I'm going to go ahead and close this as a wontfix.

**Closed by bnoordhuis** 2024-11-19 21:33 UTC
