### ISSUE TITLE
libuv-1.42.0 can't work under Windows 7x64

### ISSUE THREAD

**Issue by myfoundation** [libuv/libuv#3305] opened 2021-09-13 21:28 UTC
* **Version**: libuv-1.42.0
* **Platform**: Windows 7 x64

libuv-1.42.0 can't working under Windows 7x64, but libuv-1.41.0 working OK

**Reason:**
file libuv-1.42.0\src\win\util.c
function int uv_os_gethostname(char* buffer, size_t* size) use GetHostNameW() instead gethostname() call, but for GetHostNameW() call
Minimum supported client Windows 8.1, Windows 8
Minimum supported server Windows Server 2012
See https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-gethostnamew

So, need return gethostname() back for return support any Windows 7 version (or do macro for select Windows 7/8 durong compiling).

libuv-1.41.0 version of  int uv_os_gethostname(char* buffer, size_t* size) working under Windows 7 fine.

**Comment by bnoordhuis** [comment] 2021-09-13 21:30
Duplicate of #3260. Summary: Windows 7 is no longer supported by us.

**Closed by bnoordhuis** 2021-09-13 21:30 UTC
