### ISSUE TITLE
bug in libuv io_uring causes incorrect event reports to epoll and busy loop

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#4323] opened 2024-02-20 15:43 UTC
Julia is running into a bug where epoll returns POLLHUP on every uv_run iteration on fd 13, long after libuv closed fd 13 (which was originally a dup of stdin). This causes every future time that libuv opens fd 13 for it to immediately get closed again with EOF.

Upstream reproducer: https://github.com/JuliaLang/julia/pull/53392

Here are some snippets of where the strace log goes wrong: notice how after uv_close (13) it continues to get epoll_pwait events on 13 (that repeats until the program exits), note that `io_uring_enter` are logged, but not `io_uring_ctl` events, so we have to just infer the presence of those

```
// open 13 as stdin in libuv
fcntl(0, F_DUPFD_CLOEXEC, 3)            = 13
ioctl(13, TCGETS, 0x7ffe6fa65960)       = -1 ENOTTY (Inappropriate ioctl for device)
newfstatat(13, "", {st_mode=S_IFIFO|0600, st_size=0, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/dev/null", O_RDONLY|O_CLOEXEC) = 14
fcntl(13, F_GETFL)                      = 0 (flags O_RDONLY)
ioctl(13, FIONBIO, [1])                 = 0
...
// read EOF from stdin and close it
io_uring_enter(7, 3, 3, IORING_ENTER_GETEVENTS, NULL, 0) = 3
epoll_pwait(5, [{events=EPOLLIN|EPOLLHUP, data={u32=13, u64=13}}], 1024, -1, NULL, 8) = 1
brk(0x55c74bc5e000)                     = 0x55c74bc5e000
read(13, "empty!(Base.EXT_DORMITORY) # If "..., 65536) = 1713
close(13)                               = 0
io_uring_enter(7, 1, 1, IORING_ENTER_GETEVENTS, NULL, 0) = 1
epoll_pwait(5, [{events=EPOLLHUP, data={u32=13, u64=13}}], 1024, 0, NULL, 8) = 1
...
// make a new pipe in libuv, which gets assigned to fd 13
epoll_pwait(5, [{events=EPOLLHUP, data={u32=13, u64=13}}], 1024, 0, NULL, 8) = 1
io_uring_enter(7, 1, 1, IORING_ENTER_GETEVENTS, NULL, 0) = 1
pipe2([13, 18], O_NONBLOCK|O_CLOEXEC)   = 0
fcntl(13, F_GETFL)                      = 0x800 (flags O_RDONLY|O_NONBLOCK)
ioctl(13, FIONBIO, [1])                 = 0
fcntl(18, F_GETFL)                      = 0x801 (flags O_WRONLY|O_NONBLOCK)
ioctl(18, FIONBIO, [1])                 = 0
...
// read data from pipe, and invalid EPOLLHUP
io_uring_enter(7, 1, 1, IORING_ENTER_GETEVENTS, NULL, 0) = 1
epoll_pwait(5, [{events=EPOLLHUP, data={u32=13, u64=13}}, {events=EPOLLIN, data={u32=13, u64=13}}], 1024, -1, NULL, 8) = 2
read(13, "q", 65536)                    = 1
close(13)                               = 0
io_uring_enter(7, 1, 1, IORING_ENTER_GETEVENTS, NULL, 0) = 1
epoll_pwait(5, [{events=EPOLLHUP, data={u32=13, u64=13}}], 1024, 0, NULL, 8) = 1
```

**Comment by santigimeno** [comment] 2024-02-21 13:01
I'm happy to take a look but have no experience with Julia so please, bear with me. Following [this](https://github.com/JuliaLang/julia/pull/53392#issuecomment-1953383509) I've been able to reproduce the issue by building Julia from commit https://github.com/JuliaLang/julia/commit/e5496e0d1700797ab721e9158bd39093542e3118. Then I wanted to use a modified version of the libuv code on top of https://github.com/JuliaLang/libuv/commit/344a3f5f00c9514e88a5f7463c621efb221aed23 in which I added some logs that print to stderr and added these changes locally with this patch:
```
diff --git a/deps/libuv.mk b/deps/libuv.mk
index eacabac55e..3b02d6a90e 100644
--- a/deps/libuv.mk
+++ b/deps/libuv.mk
@@ -1,7 +1,7 @@
 ## LIBUV ##
 ifneq ($(USE_BINARYBUILDER_LIBUV),1)
-LIBUV_GIT_URL:=https://github.com/JuliaLang/libuv.git
-LIBUV_TAR_URL=https://api.github.com/repos/JuliaLang/libuv/tarball/$1
+LIBUV_GIT_URL:=https://github.com/santigimeno/libuv.git
+LIBUV_TAR_URL=https://api.github.com/repos/santigimeno/libuv/tarball/$1
 $(eval $(call git-external,libuv,LIBUV,configure,,$(SRCCACHE)))
 
 UV_CFLAGS := -O2
diff --git a/deps/libuv.version b/deps/libuv.version
index 9ae54aa7be..7b980773dc 100644
--- a/deps/libuv.version
+++ b/deps/libuv.version
@@ -3,5 +3,5 @@ LIBUV_JLL_NAME := LibUV
 
 ## source build
 LIBUV_VER := 2
-LIBUV_BRANCH=julia-uv2-1.48.0
-LIBUV_SHA1=afa1c67fa496eb49ade1e520f76fd018a1409eaa
+LIBUV_BRANCH=santi/io_uring
+LIBUV_SHA1=f982cec43c66f115527eea637892984646c7a5da
```
Then I built everything again but couldn't see the logs so I'm not sure I'm doing it correctly. I appreciate any guidance here.

**Comment by vtjnash** [comment] 2024-02-21 14:05
You can additionally set `DEPS_GIT=libuv` and it will checkout a git repo in deps/srccache/libuv that you can modify locally. (commonly these options are set in a `Make.user` file in the toplevel folder, so that you don't have to type them on the command line each time). If you do that call `make -C deps reinstall-libuv` to rebuild it with your changes.

Thanks for taking a look!

**Comment by santigimeno** [comment] 2024-02-21 14:45
@vtjnash so I did:
```bash
$ make USE_BINARYBUILDER_LIBUV=0 DEPS_GIT=libuv
```
which built everything from my repo and also did the checkout. Then I modify the code in `deps/srccache/libuv` and then run
```bash
$ make -C deps reinstall-libuv
```
but it didn't seem to rebuild anything. Do I have to do smthg else?

**Comment by santigimeno** [comment] 2024-02-22 07:52
I think we're hitting this. From `man 7 epoll`:

> 6.  Will closing a file descriptor cause it to be removed from all epoll interest lists?

           Yes, but be aware of the following point.  A file descriptor is a reference to an open file description (see open(2)).  Whenever a file descriptor is duplicated via dup(2), dup2(2), fcntl(2) F_DUPFD, or fork(2), a new file descriptor referring to the same open file description is created.  An open file description continues to exist until all file descriptors referring to it have been closed.

           A file descriptor is removed from an interest list only after all the file descriptors referring to the underlying open file description have been closed.  This means that even after a file descriptor that is part of an interest list has been closed, events may be reported for that file descriptor if other file descriptors referring to the same underlying file description remain open.  To prevent this happening, the file descriptor must be explicitly removed from the interest list (using epoll_ctl(2) EPOLL_CTL_DEL) before it is duplicated.  Alternatively, the application must ensure that all file descriptors are closed (which may be difficult if file descriptors were duplicated behind the scenes by library functions that used dup(2) or fork(2)).

So, we need to make sure the duped fd is closed after the `EPOLL_CTL_DEL` is performed. I've confirmed this fixes the issue by disabling the batching of `IORING_OP_EPOLL_CTL` (commenting this [line](https://github.com/libuv/libuv/blob/507f3046d104db2be2c33d5e8fc0d5322818a62c/src/unix/linux.c#L1265)). One possible solution I see is linking the `IORING_OP_EPOLL_CTL` with a `IORING_OP_CLOSE` op and then call the close cb, though I don't know if it's worth the effort and maybe just removing the `ctl` ring is a simpler/better solution. @bnoordhuis  wdyt?

**Comment by bnoordhuis** [comment] 2024-02-22 12:53
Ha, I knew this was going to be about closed file descriptors just by looking at the issue title. :-)

For my understanding, this concerns a file descriptor that is watched by epoll but then closed by julia (?) by means of uv_fs_close (?) or a close system call that doesn't go through libuv?

**Comment by vtjnash** [comment] 2024-02-22 13:18
No, this fd is entirely the responsibility of libuv, with the caveat that this was stdin, so it is a pipe shared with other processes

**Comment by bnoordhuis** [comment] 2024-02-23 18:55
@vtjnash so it's basically `uv_pipe_open(&handle, dup(STDIN_FILENO))`, `uv_read_start(...)`, and eventually `uv_close(...)`? Hm, I would expect that to Just Work for the reason Santi mentioned.

**Comment by vtjnash** [comment] 2024-02-23 19:11
Yes, which I think should be _broken_ for the reasons Santi mentioned (it is batched but not flushed yet)?

**Comment by santigimeno** [comment] 2024-02-28 09:29
So, here's a reproducer of the issue. It crashes with current v1.x, it doesn't if the EPOLL_CTL_DEL are executed immediately. To experience the busy loop, as mentioned in the comments, just comment the `assert()` and the `close()` calls.
```c
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <uv.h>

uv_pipe_t pipe1;
uv_pipe_t pipe2;
uv_idle_t idle_handle;
static int iters;
int duped_fd;
int newpipefds[2];

void alloc_buffer(uv_handle_t *handle, size_t suggested_size, uv_buf_t *buf) {
  *buf = uv_buf_init((char*) malloc(suggested_size), suggested_size);
}

void read_data2(uv_stream_t *stream, ssize_t nread, const uv_buf_t *buf) {
  if (nread < 0) {
    assert(nread == UV_EOF);
    close(duped_fd);
    uv_close((uv_handle_t*)&pipe2, NULL);
    uv_close((uv_handle_t*)&idle_handle, NULL);
  } else {
    // If nread == 0 is because of POLLHUP received still from pipefds[0] file
    // description which is still referenced in duped_fd. It should not happen
    // if close(pipe1) was called after EPOLL_CTL_DEL. Comment this assert to
    // expose the busy loop.
    assert(nread > 0);
  }
}

void idle_cb(uv_idle_t* handle) {
  if (++iters == 1) {
    uv_pipe_init(uv_default_loop(), &pipe2, 0);

    pipe(newpipefds);

    uv_pipe_open(&pipe2, newpipefds[0]);

    uv_read_start((uv_stream_t*)&pipe2, alloc_buffer, read_data2);
  } else {
    // Comment this close for the busy loop to happen.
    close(newpipefds[1]);
    uv_idle_stop(handle);
  }
}

void read_data(uv_stream_t *stream, ssize_t nread, const uv_buf_t *buf) {
  assert(nread == UV_EOF);
  uv_close((uv_handle_t*)stream, NULL);
  uv_idle_start(&idle_handle, idle_cb);
}

int main() {
  uv_loop_t *loop = uv_default_loop();

  uv_pipe_init(loop, &pipe1, 0);
  uv_idle_init(loop, &idle_handle);

  int pipefds[2];
  pipe(pipefds);

  uv_pipe_open(&pipe1, pipefds[0]);
  int duped_fd = dup(pipefds[0]);

  uv_read_start((uv_stream_t*)&pipe1, alloc_buffer, read_data);

  // Close the write end of the pipe so POLLHUP is generated
  close(pipefds[1]);

  return uv_run(loop, UV_RUN_DEFAULT);
}
```

**Comment by bnoordhuis** [comment] 2024-02-28 10:31
Oh darn, the bug is obvious now that I look at it more closely. You're right, Santi, `uv__platform_invalidate_fd()` should not delay the EPOLL_CTL_DEL system call. I'll submit a fix.

(Funny, I wrote that code last year but I didn't remember I made it do that.)

**Closed** 2024-03-21 08:23 UTC
Labels: bug
