### ISSUE TITLE
win,pipe: regression after #4470

### ISSUE THREAD

**Issue by santigimeno** [libuv/libuv#4548] opened 2024-09-27 10:02 UTC
So after the new `v1.49.0` release, the Node.js test suite is failing pretty badly specially with the `child_process` tests. See:
https://github.com/nodejs/node/pull/55114. My bad I didn't catch this before the release, but was having problems with the CI on Windows.

I've been looking at the changes and it seems to come from the change in https://github.com/libuv/libuv/pull/4470.
So as an example, when running the following test, the process never exits:
```
 out/Release/node.exe test/parallel/test-child-process-fork.js
 ```
 
 Reverting all changes in `win/pipe.c` make the tests to pass again (at least most of them)
 
 /cc @vtjnash

**Comment by bnoordhuis** [comment] 2024-09-27 14:48
My vote is for RRR (Revert, Release, Revisit), also because of the macos autotools build breakage.

**Comment by saghul** [comment] 2024-09-27 14:52
+1

**Comment by vtjnash** [comment] 2024-09-30 18:29
I missed that the IPC implementation bypasses the async read implementation, so it is not eligible for the async performance optimizations. I think this should fix it, but I'm waiting for it to finish compile to run tests:
```diff
diff --git a/src/win/pipe.c b/src/win/pipe.c
index 76ea169e..d46ecb9f 100644
--- a/src/win/pipe.c
+++ b/src/win/pipe.c
@@ -2094,17 +2094,13 @@ static int uv__pipe_read_ipc(uv_loop_t* loop, uv_pipe_t* handle) {
       /* Store the pending socket info. */
       uv__pipe_queue_ipc_xfer_info(handle, xfer_type, &xfer_info);
     }
-
-    more = 1;
   }

   /* Return whether the caller should immediately try another read call to get
-   * more data. */
-  if (more && *data_remaining == 0) {
-    /* TODO: use PeekNamedPipe to see if it is really worth trying to do
-     * another ReadFile call. */
-  }
-
+   * more data. Calling uv__pipe_read_exactly will hang if there isn't data
+   * available, so we cannot do this unless we are guaranteed not to reach that.
+   */
+  more = *data_remaining > 0;
   return more;

 invalid:

```

**Comment by vtjnash** [comment] 2024-09-30 19:32
locally I see a lot of nodejs tests failing for various reason. One that I noted is this:
```
=== debug test-stdout-close-catch ===
Path: parallel/test-stdout-close-catch
node:assert:90
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'EAGAIN'
- 'EPIPE'
    at ChildProcess.<anonymous> (C:\cygwin64\home\jameson\node\test\parallel\test-stdout-close-catch.js:31:10)
    at ChildProcess.<anonymous> (C:\cygwin64\home\jameson\node\test\common\index.js:493:15)
    at ChildProcess.emit (node:events:518:35)
    at maybeClose (node:internal/child_process:1103:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 'EAGAIN',
  expected: 'EPIPE',
  operator: 'strictEqual'
}

Node.js v23.0.0-pre
Command: C:\cygwin64\home\jameson\node\out\Debug\node.exe C:\cygwin64\home\jameson\node\test\parallel\test-stdout-close-catch.js
```
Which makes me worry Windows is mapping this error wrong, causing libuv to need to map it wrong (04a35efe69001a27e177aebde6c8db6f4cca7e4b). This is slated to be fixed in libuv v2, but I'm not sure it can be fixed in v1.

**Comment by santigimeno** [comment] 2024-09-30 21:50
Yes, I was seeing that error locally too. Is related to any of the changes added for `v1.49.0`?

**Comment by santigimeno** [comment] 2024-10-01 22:33
So I've been investigating this `EAGAIN` error and seems to be caused https://github.com/libuv/libuv/commit/47c833675bef34edcfaccd97a9a21b0d82aa1fc4. I think the problem is that the aforementioned commit was focusing on `ReadFile()` calls, but the failure in the test is generated in a `WriteFile()` call, and in that case it probably matches better with the `EPIPE` error (I couldn't find official documentation about that specific case though). Should we just revert the commit or be more granular on how that error is translated (`EAGAIN` for `ReadFile()` and `EPIPE` for `WriteFile()`) ?

**Comment by vtjnash** [comment] 2024-10-02 02:07
I am reluctant to revert that, as this is a correction for handling a recent set of bug introduced into Cygwin, and that is likely used quite a bit, especially in the nodejs tests. Unfortunately the Cygwin IO implementation is very old and accumulated a lot of bugs recently and would benefit from using something more correctly implemented like libuv--but I digress. But we should potentially investigate whether libuv WriteFile can continue to directly map this to EPIPE, or whether it should in fact need to resubmit it to the write queue (eg if there are multiple active readers when one closes)

**Comment by vtjnash** [comment] 2024-10-02 02:26
Actually, looking closer at the test source, it looks like it may be a test of exactly that recently introduced Cygwin bug, since it mentions spawning a posix shell, and the Cygwin IO is no longer possible to use in non-Cygwin programs, so I think it is likely the failure here is caused by the recent Cygwin bug and was previously being (wrongly) passing due to libuv incorrectly mapping that error

**Comment by santigimeno** [comment] 2024-10-02 07:11
I'm running this test on `cmd.exe` on a Windows VM. I don't know if in this scenario we're dealing with Cigwin at all

**Comment by vtjnash** [comment] 2024-10-02 15:00
Okay, I see the same testing with cmd directly. I was confused because the test says it is mangled for JSON execution, and that does not seem safe for using with either a posix nor cmd shell. I am attempting some local testing, and it looks like if you slow things down in a debugger, it will randomly either fail because it gets EOF (the write was queued then failed later) or EAGAIN (the write failed to be queued) back from this uv_write, either of which is a somewhat sketchy errno mapping (for the write, not a read):
```    case ERROR_BROKEN_PIPE:                 return UV_EOF;```
Seems like the write fix here is to ensure libuv will map both of those errors different for uv_write to mean EPIPE

**Closed** 2024-10-03 20:12 UTC
