### ISSUE TITLE
Assertion failed in test/test-hrtime.c 

### ISSUE THREAD

**Issue by mimi1vx** [libuv/libuv#2215] opened 2019-03-03 14:00 UTC
[  160s] not ok 119 - hrtime
[  160s] # exit code 6
[  160s] # Output from process `hrtime`:
[  160s] # Assertion failed in test/test-hrtime.c on line 50: diff < (uint64_t) 80 * NANOSEC / MILLISEC
<
* **1.26.0**: 
* **s390x - openSUSE Tumbleweed**:

**Comment by richardlau** [comment] 2019-03-03 14:10
I think this has been addressed by https://github.com/libuv/libuv/pull/2186 which should make the [next release](https://github.com/libuv/libuv/issues/2213).

**Comment by bnoordhuis** [comment] 2019-03-03 17:23
That's right. I'll close this as a duplicate of #2117.

**Closed by bnoordhuis** 2019-03-03 17:23 UTC
