### ISSUE TITLE
When using uv_udp_send，the function sends packets, but the packets sent are inconsistent

### ISSUE THREAD

**Issue by icechenbing** [libuv/libuv#3693] opened 2022-07-19 06:48 UTC
![image](https://user-images.githubusercontent.com/6427220/179684061-21ef0148-f6d7-49d4-8bf1-9451d98b1cb6.png)
The first packet can be sent correctly, and the content of the second packet is wrong。

**Comment by icechenbing** [comment] 2022-07-19 06:54
the udp packet is bytes using KCP protocol , the second packet KCP sn is 1(0x01)

**Comment by bnoordhuis** [comment] 2022-07-19 08:18
> the content of the second packet is wrong

Define 'wrong'?

**Comment by icechenbing** [comment] 2022-07-19 08:22
> 



> > the content of the second packet is wrong
> 
> Define 'wrong'?

yes, the second, third，fourth ，continued packet all wrong. only first packet sent correctly

**Comment by icechenbing** [comment] 2022-07-19 08:52
Forget to introduce the environment ：Andriod/Linux
In Windows environment, this problem does not exist。

**Comment by bnoordhuis** [comment] 2022-07-19 09:38
Can you explain what is wrong about the packets? I don't want to have to guess.

**Comment by icechenbing** [comment] 2022-07-19 11:29
> Can you explain what is wrong about the packets? I don't want to have to guess.

In my KCP protocol, I designed serialization（sn） to increase from 0 to n.
Then starts sending one KCP packet after another. From the result of packet capturing, the first packet is sent accurately (Sn in the KCP protocol is 0). The second packet needs to be 1 as expected, but it can be seen from the above PIC that the SN field is incorrect（0x20，means 32）.
I guess that the UDP packet content was tampered with when it was sent.

**Comment by bnoordhuis** [comment] 2022-07-19 12:51
Right, and you open a bug report here because....?

I'm going to close this because the odds are overwhelmingly in favor of it being a bug in your code. This bug tracker is not a free "help me fix my code" service.

If want me to reopen it, please include a minimal test case that demonstrates the problem is inside libuv.

**Closed by bnoordhuis** 2022-07-19 12:51 UTC
