### ISSUE TITLE
about accept multiple loops

### ISSUE THREAD

**Issue by baisai** [libuv/libuv#932] opened 2016-07-01 02:04 UTC
i want to run multiple loops and listen one port
but aceept  server socket and client handle must be running on the same loop.
is there a way accept client socket running other loop or multiple loops listen the same port

**Comment by saghul** [comment] 2016-07-01 08:12
There is no way to accept a client on another loop. There are a number of things you can do:

- create the listener handle, then create X new loops, send the handle to them using uv_write2 and listen in all of them
- if you're on Linux (> 3.9 IIRC), create X new loops and bind a handle to the same IP and port using SO_REUSEPORT
- have a single loop accept all incoming connections and send them to other loops using uv_write2.

**Comment by baisai** [comment] 2016-07-01 11:04
thank you for your answer
do you mean to use name pipe to send the handle?
en...i have test for uv_listen in A loop thread and uv_accept in B loop thread. it work in windows success!!!
i think use name pipe send handle in the same process may be a little slowly
would libuv can providing this support?

**Comment by baisai** [comment] 2016-07-01 11:04
thank you for your answer
do you mean to use name pipe to send the handle?
en...i have test for uv_listen in A loop thread and uv_accept in B loop thread. it work in windows success!!!
i think use name pipe send handle in the same process may be a little slowly
would libuv can providing this support?

**Comment by saghul** [comment] 2016-07-01 11:24
I don't see libuv providing support for this anytime soon. The only reason why it "works" on Windows is the lack of an assert. It's not thread-safe, so your application may break in unexpected ways. Don't do that.

As for speed: don't guess, benchmark.

**Comment by saghul** [comment] 2016-07-01 11:25
Closing this as "not an issue, works as intended".

**Closed by saghul** 2016-07-01 11:25 UTC

**Comment by terrywh** [comment] 2017-08-23 13:58
just a quick question: does the 
* create the listener handle, then create X new loops, send the handle to them using uv_write2 and listen in all of them
apply to "unix domain socket" ?

**Comment by odiszapc** [comment] 2017-09-07 15:22
@saghul Let me also ask the same: is sending server handle and then listening in multiple loops cross-platform? Thx!

**Comment by saghul** [comment] 2017-09-07 17:20
@odiszapc Yes, it is.

**Comment by haohaolee** [comment] 2018-07-13 03:20
@saghul Hi, I have a question as well. Why not just pass the server handle as the parameter to create_thread？
