### ISSUE TITLE
1.26.0: some tests are failing

### ISSUE THREAD

**Issue by kloczek** [libuv/libuv#2191] opened 2019-02-16 16:51 UTC
<pre>not ok 107 - getaddrinfo_fail
# exit code 134
# Output from process `getaddrinfo_fail`:
# Assertion failed in test/test-getaddrinfo.c on line 43: status &lt; 0
not ok 108 - getaddrinfo_fail_sync
# exit code 134
# Output from process `getaddrinfo_fail_sync`:
# Assertion failed in test/test-getaddrinfo.c on line 112: 0 &gt; uv_getaddrinfo(uv_default_loop(), &amp;req, NULL, &quot;xyzzy.xyzzy.xyzzy.&quot;, NULL, NULL)
</pre>

**Comment by bnoordhuis** [comment] 2019-02-21 11:41
That probably means your DNS resolver returns _something_ for the (normally invalid) domain name `xyzzy.xyzzy.xyzzy.` (note the trailing dot - it's a FQDN.)

I'm closing this as a duplicate of https://github.com/libuv/libuv/issues?q=is%3Aissue+xyzzy.xyzzy.xyzzy but thanks anyway for the report. :-)

**Closed by bnoordhuis** 2019-02-21 11:41 UTC
Labels: duplicate, test
