### ISSUE TITLE
Not delivered signals

### ISSUE THREAD

**Issue by mad-rain** [libuv/libuv#1474] opened 2017-08-13 15:43 UTC
* **Version**: Latest
* **Platform**: Ubuntu 16.04

Hi,

We've a strange problem, not even sure its related directly to libuv. 

Our machine running a proxy server build on top of libuv. Its just proxing TCP & UDP traffic to application servers. Everything works very stable for many days. The proxy is running as a service under systemd.

We're using SIGUSR2 to signal proxy to reload its config. After some time (hours) of running the proxy doesn't get any signals at all.

We tried to put some debug prints directly in uv__signal_handler - and it prints nothing.

This is how we send the signal:

systemctl kill --signal SIGUSR2 proxy

The proxy is completelly non-blocking and single threaded, also it even works after we send a signal. Then after 60 seconds or so systemd kills it due to undelivered signal. No memory issues found using valgrind.

Lines from system log:
```
Aug 12 14:02:31 prod systemd[1]: proxy.service: Main process exited, code=killed, status=12/USR2
Aug 12 14:02:31 prod systemd[1]: proxy.service: Unit entered failed state.
Aug 12 14:02:31 prod systemd[1]: proxy.service: Failed with result 'signal'.
```

Any advice?

Andrew.

**Comment by bnoordhuis** [comment] 2017-08-13 16:20
Maybe try attaching strace before you send the signal?  That should at least tell you if the event loop makes some forward movement, if only internal to libuv.

**Comment by mad-rain** [comment] 2017-08-17 17:39
Here is what we got in strace log. The proxy was killed immediately after sending SIGUSR2. libuv's uv__signal_handler wasn't called.

```
recvmsg(11, {msg_name(28)={sa_family=AF_INET6, sin6_port=htons(38975), inet_pton(AF_INET6, "::ffff:21.148.62.179", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, msg_iov(1)=[{"\20)$\257\272O/\177b\361\n\34\v9\7\377\377\n\0\361\n\374\6", 6
5536}], msg_controllen=0, msg_flags=0}, 0) = 23
sendmsg(18, {msg_name(16)={sa_family=AF_INET, sin_port=htons(8421), sin_addr=inet_addr("10.128.0.97")}, msg_iov(1)=[{":\315\4\0\0\0\0\0b\361\n\34\v9\7\377\377\n\0\361\n\374\6", 23}], msg_controllen=0, msg_flags=0}, 0) = 23
recvmsg(11, 0x7ffdf65f7e50, 0)          = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_MONOTONIC, {8408766, 900609174}) = 0
epoll_wait(7, [{EPOLLIN, {u32=18, u64=18}}], 1024, 16911) = 1
clock_gettime(CLOCK_MONOTONIC, {8408766, 920328404}) = 0
recvmsg(18, {msg_name(16)={sa_family=AF_INET, sin_port=htons(8421), sin_addr=inet_addr("10.128.0.97")}, msg_iov(1)=[{"#\315\4\0\0\0\0\0b\6\t\260\nu\20\377\377i\1\3\1\f\3\311\1\17\0008\215\5\0\243"..., 65536}], msg_controllen=0, msg_flags=0
}, 0) = 208
sendmsg(11, {msg_name(28)={sa_family=AF_INET6, sin6_port=htons(3060), inet_pton(AF_INET6, "::ffff:26.211.5.25", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, msg_iov(1)=[{",\37:i\250\254\vRb\6\t\260\nu\20\377\377i\1\3\1\f\3\311\1\17\0008
\215\5\0\243"..., 208}], msg_controllen=0, msg_flags=0}, 0) = 208
recvmsg(18, 0x7ffdf65f7e50, 0)          = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_MONOTONIC, {8408766, 921086931}) = 0
epoll_wait(7, 0x7ffdf65f8020, 1024, 16890) = -1 EINTR (Interrupted system call)
--- SIGUSR2 {si_signo=SIGUSR2, si_code=SI_USER, si_pid=1, si_uid=0} ---
+++ killed by SIGUSR2 +++
```

**Comment by bnoordhuis** [comment] 2017-08-18 10:11
Hard to say what's going on but it looks like something restored the default SIGUSR2 behavior.  Is there an easy way for me to reproduce?  Can you reproduce with a small libuv-only program?

**Comment by bnoordhuis** [comment] 2017-09-05 15:13
No follow-up, closing.

**Closed by bnoordhuis** 2017-09-05 15:13 UTC

**Comment by zhukovaskychina** [comment] 2019-06-10 06:09
Me too。
Version: Latest
Platform: centos X.X

`            uv_signal_t userSignal;
            uv_signal_init(env.event_loop(), &userSignal);
            uv_signal_start(&userSignal, userSignalHandler, SIGUSR2);`

`        kill(pid,SIGUSR2);`

this signal is not worked after i called the command 'Kill' on the centos。

**Comment by santigimeno** [comment] 2019-06-10 07:42
Do you have a reproducible test case?

**Comment by zhukovaskychina** [comment] 2019-06-11 05:35
Yeah,perhaps i found the keys。
Platform:centos 6.0.X
kernel:Linux localhost.localdomain 2.6.32-754.12.1.el6.x86_64 #1 SMP Tue Apr 9 14:52:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
this sigal is not worked dued to the EINTR errors。

when i changed the platform。
Platform:ubuntu 16.0.4
kernel:Linux zhukovasky-computer 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
the signal is ok!!!

**Comment by bnoordhuis** [comment] 2019-06-11 09:25
> this sigal is not worked dued to the EINTR errors

I'm not sure I follow. What does that mean?
