### ISSUE TITLE
async.c:149: uv__async_io: Assertion `n == sizeof(val)' failed

### ISSUE THREAD

**Issue by jordabi** [libuv/libuv#401] opened 2015-06-18 04:34 UTC
I am getting this error at random times. Sometimes Node will run for days without this error, but other times I will get it back to back in a short period of time.  I have seen comments to the effect that it is there to catch programming errors or unexpected conditions and that it one case it was someone's misuse of an API, but I can not find where anyone has elaborated on what the issue actually was or what types of errors cause it. Any help with tracking this down and determining if it is an error in my code or in another component would be greatly appreciated.

**Comment by cynron** [comment] 2015-06-18 05:49
@saghul 

https://github.com/libuv/libuv/blob/v1.x/src/unix/async.c#L130

I think the assert 

```
assert(n == sizeof(val))
``` 

should be 

```
assert( n % sizeof(val) == 0)
```

suppose 2 thread do:

thread A: read(w->fd, buf, sizeof(buf) = 8
thread B: write(w->fd, buf, sizeof(buf)) = 8
thread A: read(w->fd, buf, sizeof(buf) = 8


then, the `n` here will be 16, not 8.

**Comment by saghul** [comment] 2015-06-18 08:14
What kind of platform are you running on? Do you have a way to reproduce it with certain degree of reliability?

**Comment by bnoordhuis** [comment] 2015-06-18 09:10
It must be Linux because that assert is in the eventfd code.  The line number doesn't match up though so it's probably not a recent version of libuv.

@jordabi What node.js version do you run?

**Comment by jordabi** [comment] 2015-06-18 14:27
@saghul, The error message I posted is copied verbatum. I do not have a reliable way to repro, which is why I'm asking for more help on this to even track down what that assertion is supposed to be testing for and in what in my app may be causing it...not the specific issue, but the kind of issue to look for.

@bnoordhuis  I am running Node 0.10.33 on CentoOS 7

**Comment by bnoordhuis** [comment] 2015-06-18 14:34
@jordabi That version of node.js uses a pretty old version of libuv, v0.10.29.  The latest v0.10 release is v0.10.36 and that is what ships with node.js v0.10.37 and v0.10.38.  My first suggestion would be to update node.js and check if the problem persists.

**Comment by jordabi** [comment] 2015-06-18 15:01
@bnoordhuis Yeah was just starting to do that and see what that breaks.  Are you aware of any major issues with the latest 0.12.x version?

**Comment by bnoordhuis** [comment] 2015-06-18 15:19
No issues that I'm aware of.  I only work on io.js though so that isn't saying much.

**Comment by jordabi** [comment] 2015-06-24 18:33
@bnoordhuis Well, I upgrade to 0.10.38 and had not seen the issue for the past several days so I thought your suggestion to upgrade did the trick...However, I just got the error again, and it appears to be the same error with a different line number:

node: ../deps/uv/src/unix/async.c:124: uv__async_io: Assertion `n == sizeof(val)' failed.

So, the same, original question stand, Can you provide any help in determining what may be causing this?

**Comment by bnoordhuis** [comment] 2015-06-24 20:11
Maybe try running node with strace attached, i.e. `strace -fo trace.log node app.js`.  It slows down the node process a great deal, though; it's not something you want to do in production.

**Comment by fmsouza** [comment] 2015-07-30 21:51
I had this same issue in my nodejs application while dealing with concurrent requests.
It happened in nodejs v0.12.7 inside a docker container, version  1.7.1, build 786b29d, installed on OS X 10.10.4.
My trace's last 100 lines are in http://pastebin.com/BUs2uTrB

Hope it can help you fix it.

**Comment by cynron** [comment] 2015-08-05 02:28
@fmsouza  more strace logs,  200 or 300 lines?

**Comment by fmsouza** [comment] 2015-09-30 17:45
Hi @cynron !
Sorry for taking so long to bring the trace, I've been too busy.

As the file size is ~1.1MB I couldn't post it on pastebin again. It's in my Google Drive and you can access here: https://drive.google.com/file/d/0B2t-CwshyXQPUnlvX3JvMGNrZlk/view?usp=sharing

I managed to reproduce the problem by running ```httperf``` a little amount of times. Those were my inputs and outputs that produced this log in the server:

```
$ httperf --server my.server.address --port 3001 --uri /v2/search --num-conn 50 --rate 10 --timeout 5
httperf --timeout=5 --client=0/1 --server=my.server.address --port=3001 --uri=/v2/search --rate=10 --send-buffer=4096 --recv-buffer=16384 --num-conns=50 --num-calls=1
httperf: warning: open file limit > FD_SETSIZE; limiting max. # of open files to FD_SETSIZE
Segmentation fault: 11

$ httperf --server my.server.address --port 3001 --uri /v2/search --num-conn 50 --rate 5 --timeout 5
httperf --timeout=5 --client=0/1 --server=my.server.address --port=3001 --uri=/v2/search --rate=5 --send-buffer=4096 --recv-buffer=16384 --num-conns=50 --num-calls=1
httperf: warning: open file limit > FD_SETSIZE; limiting max. # of open files to FD_SETSIZE
Maximum connect burst length: 1

Total: connections 50 requests 35 replies 14 test-duration 9.810 s

Connection rate: 5.1 conn/s (196.2 ms/conn, <=26 concurrent connections)
Connection time [ms]: min 1042.0 avg 2956.7 max 4759.6 median 3039.5 stddev 846.5
Connection time [ms]: connect 183.1
Connection length [replies/conn]: 1.000

Request rate: 3.6 req/s (280.3 ms/req)
Request size [B]: 73.0

Reply rate [replies/s]: min 0.6 avg 0.6 max 0.6 stddev 0.0 (1 samples)
Reply time [ms]: response 1105.3 transfer 1745.2
Reply size [B]: header 382.0 content 559849.0 footer 0.0 (total 560231.0)
Reply status: 1xx=0 2xx=14 3xx=0 4xx=0 5xx=0

CPU time [s]: user 1.21 system 8.54 (user 12.3% system 87.1% total 99.3%)
Net I/O: 781.0 KB/s (6.4*10^6 bps)

Errors: total 36 client-timo 5 socket-timo 0 connrefused 15 connreset 16
Errors: fd-unavail 0 addrunavail 0 ftab-full 0 other 0
```

**Comment by cynron** [comment] 2015-10-08 04:02
Hi @fmsouza ,

last lines from your strace log:

```
1733  epoll_pwait(5, {{EPOLLOUT, {u32=39, u64=39}}, {EPOLLOUT, {u32=20, u64=20}}}, 1024, 0, [PROF], 8) = 2
1733  write(39, "\"order\":\"A72032\",\"speed\":17,\"dir"..., 893386) = 35568
1733  write(20, "22.877197,\"longitude\":-43.422058"..., 886546) = 41040
1733  epoll_pwait(5, {{EPOLLIN, {u32=12, u64=12}}}, 1024, 116, [PROF], 8) = 1
1733  read(12, "\361\361\2\0\3\371@\0\367\1\0\0\1\0\0\0\10\0\0\0\0\0\0\0\0\0\0\0\210\23\0\0"..., 65536) = 65536
1733  read(12, "ine\0\4\0\0\000217\0\2order\0\7\0\0\0A71627\0\20s"..., 65536) = 65536
1733  read(12, "\0V\f\34\34R\374\351)a\363#4\2line\0\4\0\0\000413\0\2orde"..., 65536) = 61937
1733  futex(0x18b2918, FUTEX_WAKE_PRIVATE, 1) = 1
1736  <... futex resumed> )             = 0
1736  futex(0x18b2918, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff <unfinished ...>
1733  futex(0x18b2918, FUTEX_WAKE_PRIVATE, 1) = 1
1737  <... futex resumed> )             = 0
1737  futex(0x18b2918, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff <unfinished ...>
1733  mmap(0x2ce24f0f000, 3227648, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x2ce24f0f000
1733  munmap(0x2ce24f0f000, 987136)     = 0
1733  munmap(0x2ce25214000, 61440)      = 0
1733  mmap(0x2ce25000000, 2179072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x2ce25000000
1733  mmap(0x30530b66c000, 3227648, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x30530b66c000
1733  munmap(0x30530b66c000, 606208)    = 0
1733  munmap(0x30530b914000, 442368)    = 0
1733  mmap(0x30530b700000, 2179072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x30530b700000
1733  writev(41, [{"HTTP/1.1 200 OK\r\nX-Powered-By: E"..., 382}, {"[{\"line\":\"438\",\"order\":\"A27640\","..., 1080420}], 2) = 51984
1733  accept4(17, 0, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = 22
1733  accept4(17, 0, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = 23
1733  accept4(17, 0, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
1733  write(36, "(VIA AV. SANTA CRUZ) X CAMPO GRA"..., 948106) = 41040
1733  read(8, 0x7ffdf867bf50, 1024)     = -1 EAGAIN (Resource temporarily unavailable)
1733  write(2, "node: ../deps/uv/src/unix/async."..., 90) = 90
1733  mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f298a0fa000
1733  rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
1733  tgkill(1733, 1733, SIGABRT)       = 0
1733  --- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=1733, si_uid=1001} ---
1740  +++ killed by SIGABRT (core dumped) +++
1741  +++ killed by SIGABRT (core dumped) +++
1739  +++ killed by SIGABRT (core dumped) +++
1738  +++ killed by SIGABRT (core dumped) +++
1737  +++ killed by SIGABRT (core dumped) +++
1736  +++ killed by SIGABRT (core dumped) +++
1735  +++ killed by SIGABRT (core dumped) +++
1734  +++ killed by SIGABRT (core dumped) +++
1733  +++ killed by SIGABRT (core dumped) +++
```


***1733  read(8, 0x7ffdf867bf50, 1024)     = -1 EAGAIN (Resource temporarily unavailable)
1733  write(2, "node: ../deps/uv/src/unix/async."..., 90) = 90***

according to previous strace output, `fd 8` is the event fd for `async handle`

no prior `epoll_pwait` says `fd 8` is ready for `EPOLLIN`, so `read`  fails, which leads to crash here. 

and the same as `fd 17`, also no prior `epoll_pwait` says `fd 17` is ready for `EPOLLIN`.  

it seems an `epoll_pwait` is skipped, and the following invocation for io callback using incorrect ready events.

i do not know why, memory corruption here?

**Comment by cynron** [comment] 2015-10-08 05:24
@fmsouza 

backtrace when crashing?

    $ gdb /path/to/node /path/to/core/file

and then type command `bt` in gdb.

**Comment by bnoordhuis** [comment] 2015-10-08 15:59
@fmsouza Can you try https://github.com/libuv/libuv/pull/565?  You can apply it to your node.js checkout like this:

```
$ curl -L https://github.com/libuv/libuv/pull/565.diff | git apply --directory=deps/uv/
$ ./configure && make
```

**Comment by sittingbool** [comment] 2015-11-05 13:37
I continue running into the same problem on another line node: ../deps/uv/src/unix/async.c:130: uv__async_io: Assertion `n == sizeof(val)' failed.

**Comment by bnoordhuis** [comment] 2015-11-05 16:48
@sittingbool Does #565 help?  You should be able to `rm -rf deps/uv`, replace it with the current libuv v1.x branch and rebuild.

**Comment by saghul** [comment] 2015-12-14 20:47
No follow up, closing.

**Closed by saghul** 2015-12-14 20:47 UTC

**Comment by donnyhardyanto** [comment] 2016-01-02 01:13
I have similar problem. The problem triggered when 2 client accessing in same times, or by load test 1000 requests sequentially.

I tried to use #565, but error:
```
root@ubuntu1:/apias/src/node-v5.3.0# curl -L https://github.com/libuv/libuv/pull/565.diff | git apply --directory=deps/uv/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   136    0   136    0     0    101      0 --:--:--  0:00:01 --:--:--   101
  0     0    0 10633    0     0   3898      0 --:--:--  0:00:02 --:--:-- 11445
error: patch failed: deps/uv/src/queue.h:30
error: deps/uv/src/queue.h: patch does not apply
error: patch failed: deps/uv/src/threadpool.c:223
error: deps/uv/src/threadpool.c: patch does not apply
error: patch failed: deps/uv/src/unix/async.c:78
error: deps/uv/src/unix/async.c: patch does not apply
error: patch failed: deps/uv/src/unix/core.c:721
error: deps/uv/src/unix/core.c: patch does not apply
error: patch failed: deps/uv/src/unix/fsevents.c:149
error: deps/uv/src/unix/fsevents.c: patch does not apply
error: patch failed: deps/uv/src/unix/linux-inotify.c:120
error: deps/uv/src/unix/linux-inotify.c: patch does not apply
error: patch failed: deps/uv/src/unix/loop-watcher.c:47
error: deps/uv/src/unix/loop-watcher.c: patch does not apply
error: patch failed: deps/uv/src/unix/signal.c:234
error: deps/uv/src/unix/signal.c: patch does not apply
error: patch failed: deps/uv/src/unix/stream.c:779
error: deps/uv/src/unix/stream.c: patch does not apply
error: patch failed: deps/uv/src/uv-common.c:337
error: deps/uv/src/uv-common.c: patch does not apply
error: deps/uv/test/test-emfile.c: No such file or directory
```

**Comment by saghul** [comment] 2016-01-04 07:51
Latest Node already has the patch applied.

**Comment by brizzbane** [comment] 2016-03-11 21:37
Googled error, and found this issue.

Is there still a known bug somewhere?  Using pyuv.  Can post backtrace..

**Comment by saghul** [comment] 2016-03-14 08:37
@brizzbane can you reliably reproduce it?

**Comment by donnyhardyanto** [comment] 2016-03-15 03:31
I also got this error all the time. As far that I know, I setup the server
for production, and somebody calling me the server cannot be contact, and
take a look, this error cause the node to crash.

I am using actionhero framework, only creating action that write to console
and setup Postman to bombard the action api for 2 process @10000 sequential
request requests, and my node/actionhero framework will crash before the
completion. I am using Debian with node 5.x.x. Do similar thing on node in
Windows, but not crash and the 2 process @10000 sequential requests passed
without problem.

Donny

**Comment by brizzbane** [comment] 2016-03-17 21:45
@saghul I realized that the error started happening after I did queue_work(), so I stopped calling that way, and it went away.  Figured it was one thread trying to communicate to another?

**Comment by saghul** [comment] 2016-03-18 10:34
@donnyhardyanto I'm sorry, but I didn't get any of what you said. So far nobody managed to come up with a reliable test for this, so there is not much we can do.

@brizzbane libuv is not thread-safe, so you can't call most uv_ functions inside the queue_work function. That might explain it.

**Comment by amitguptagwl** [comment] 2016-09-02 16:16
I am facing same issue.

Summary of what I am doing: I have written a npm package. When a http request comes, it reads response from a relevant file -> process the response -> send it back to client. I was reading the file in async mode and then processing the response. It was causing following error and stopping my application;

node: ../src/tcp_wrap.cc:61: static v8::Local<v8::Object> node::TCPWrap::Instantiate(node::Environment*, node::AsyncWrap*): Assertion `(instance.IsEmpty()) == (false)' failed.
Aborted (core dumped)

Then after reading this [answer](http://stackoverflow.com/a/21584732/453767) on stackoverflow, I converted async call into sync call which improved the situation a bit;

But now I am facing

node: ../deps/uv/src/unix/async.c:130: uv__async_io: Assertion `n == sizeof(val)' failed.
Aborted (core dumped)

node --version
v5.2.0
npm --version
3.9.5

Any help?
