### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by Hello-lingu** [libuv/libuv#4424] opened 2024-05-26 08:48 UTC
I use Debian12.
I build on it, but appear problem:

```
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:5687：check-TESTS] error 1
make[1]: leaving directory“/home/lingu/Downloads/libuv-1.x”
make: *** [Makefile:5952：check-am] error 2
```

**Comment by saghul** [comment] 2024-05-26 10:38
Do you have the full test output?

**Comment by Hello-lingu** [comment] 2024-05-26 14:58
The file libuv.txt is full test output.
If you need more information, i am very gladly tell you.

If you see this e-mail, please reply.
Thanks.





                       
原始邮件
                       
                     

发件人："Saúl Ibarra Corretgé"< ***@***.*** &gt;;

发件时间：2024/5/26 18:38

收件人："libuv/libuv"< ***@***.*** &gt;;

抄送人："lingu"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [libuv/libuv] build fail (Issue #4424)




 
Do you have the full test output?

**Comment by saghul** [comment] 2024-05-26 16:14
Please attach the file as a comment here.

**Comment by Hello-lingu** [comment] 2024-05-27 13:57
This is the full test output.
[libuv.txt](https://github.com/libuv/libuv/files/15456804/libuv.txt)

**Comment by santigimeno** [comment] 2024-05-27 14:02
This is a duplicate of: https://github.com/libuv/libuv/issues/4406. See: https://github.com/libuv/libuv/issues/4406#issuecomment-2116804413

**Comment by saghul** [comment] 2024-05-27 14:02
These are the failing tests:

```
not ok 407 - udp_multicast_join
# timeout
# Output from process `udp_multicast_join`: (no output)
not ok 408 - udp_multicast_join6
# timeout
# Output from process `udp_multicast_join6`: (no output)
```

This is likely due to local firewall / network configuration.

Note this is not a build failure, just 2 tests that failed, but the resulting build is usable.

**Closed** 2024-05-27 14:03 UTC
