### ISSUE TITLE
[v1.x] testsuite regression/failure (fs_write_alotof_bufs*) on hppa,mips,powerpc

### ISSUE THREAD

**Issue by lucab** [libuv/libuv#473] opened 2015-08-07 07:47 UTC
PR  #448 introduced two new tests (fs_write_alotof_bufs*) in 2bf782777fc5908b7cf13ecb61f117af8c45b9f9. Both tests are currently failing on debian autobuilders for mips and powerpc architectures:
 * https://buildd.debian.org/status/fetch.php?pkg=libuv1&arch=mips&ver=1.7.0-1&stamp=1438902052
 * https://buildd.debian.org/status/fetch.php?pkg=libuv1&arch=powerpc&ver=1.7.0-1&stamp=1438901127

```
[%  93|+ 252|-   0|T   0|S   2]: fs_write_alotof_bufs
`fs_write_alotof_bufs` failed: exit code 6
Output from process `fs_write_alotof_bufs`:
Assertion failed in test/test-fs.c on line 2382: (size_t)read_req.result == sizeof(test_buf) * iovcount
=============================================================

[%  93|+ 252|-   1|T   0|S   2]: fs_write_alotof_bufs_with_offset
`fs_write_alotof_bufs_with_offset` failed: exit code 6
Output from process `fs_write_alotof_bufs_with_offset`:
Assertion failed in test/test-fs.c on line 2490: (int64_t)((uv_stat_t*)stat_req.ptr)->st_size == offset + (int64_t)(iovcount * sizeof(test_buf))
=============================================================
```

I have not yet triaged this issue, but it is worth noting that the same package is fine on other architectures including mipsel (the little endian port for mips) and on ppc64el (the 64bits little endian port for powerpc), while both mips&powerpc are 32bits big-endian ports.

As such I suspect either the new features or the tests have some portability issue specifically related to 32bits big-endian architectures.

cc @ronkorving @bwijen @saghul for any hints on pinpointing this. My bets are either on the two casts in the testsuite or on the new `uv__getiovmax()`, but I'm not familiar enough with this code.

**Comment by ronkorving** [comment] 2015-08-07 12:04
The new iovmax is actually not really new. It was simply moved from stream to core, so your hunch about typecasting may be more in the right direction.

**Comment by bwijen** [comment] 2015-08-08 07:39
As seen in the logs, the reads fail, not the writes.
That would suggest it's not a problem with typecasting, but with the actual read, since the assertions are equal in the first test.

I will try to reproduce (on an emulator) there might be a problem with partial read/writes as @bnoordhuis has [already pointed out](https://github.com/libuv/libuv/pull/269#discussion_r28131975). If so, I have a solution in mind...

Will keep you posted.

**Comment by lucab** [comment] 2015-08-08 14:33
@bwijen the build enviroment is a plain debian unstable; both mips and powerpc ports should be supported by qemu. Otherwise there is [a process to provide guest access to porterbox](https://dsa.debian.org/doc/guest-account/), but it might be a bit cumbersome.

**Comment by bwijen** [comment] 2015-08-08 14:45
Currently setting up a ppc through qemu...

**Comment by saghul** [comment] 2015-08-09 00:36
@bwijen thanks for the help!

**Comment by bwijen** [comment] 2015-08-12 05:41
Update:
Found it, turned out I was looking in the wrong place...
The problem isn't in #448, but was introduced with: 13dd350
I already have a solution, but it needs some implementing and testing.

**Comment by ronkorving** [comment] 2015-08-12 05:55
Wow, awesome job!
Good luck!

**Comment by bwijen** [comment] 2015-08-19 19:59
Please ignore those commits, these are for testing only.
I will create a pull request if everything is fine...

**Comment by lucab** [comment] 2015-08-23 12:40
@bwijen I did a quick try of your current patch on both ports, and it looks like it fixes `fs_write_alotof_bufs` while `fs_write_alotof_bufs_with_offset` still fails.

**Comment by bwijen** [comment] 2015-08-23 20:02
@lucab You're right... The patch only fixes the fs_write_alotof_bufs, still working on a fix for the other test.

**Comment by bwijen** [comment] 2015-09-29 06:51
@saghul: I removed all preadv/pwritev syscall code. Could you please take a look?

**Comment by bwijen** [comment] 2015-10-25 13:49
Hi guys, I see other issues resolved in just a few days, my fix for this issue was almost a month ago.
I hope this isn't going to be like #269.
Please don't get me wrong, I do want to contribute, but I also want to see my efforts land...

If there is something wrong with the code, please just let me know and I will try to get it right!

**Comment by bnoordhuis** [comment] 2015-10-25 13:52
@bwijen @saghul is OOO until next month and I have only minimal time at the moment.

**Comment by bwijen** [comment] 2015-10-25 13:56
Ok, NP thanks for the feedback...

**Comment by saghul** [comment] 2015-11-04 20:20
@bwijen Ahoi, and so sorry for the delay... #498 LGTM, I'll comment there.

**Closed** 2015-12-03 07:50 UTC
