### ISSUE TITLE
Failing test 107 and 108 on fedora 29

### ISSUE THREAD

**Issue by bambuchaAdm** [libuv/libuv#2079] opened 2018-11-15 22:45 UTC
* **Version**: 1.24.0
* **Platform**: Linux localhost.localdomain 4.18.17-300.fc29.x86_64 #1 SMP Mon Nov 5 17:56:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

After clone and checkout to `v1.24.0` tag and perform instruction about building sources using autotools i got on `make check` 

```
not ok 107 - getaddrinfo_fail
# exit code 134
# Output from process `getaddrinfo_fail`:
# Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
not ok 108 - getaddrinfo_fail_sync
# exit code 134
# Output from process `getaddrinfo_fail_sync`:
# Assertion failed in test/test-getaddrinfo.c on line 117: 0 > uv_getaddrinfo(uv_default_loop(), &req, NULL, "xyzzy.xyzzy.xyzzy.", NULL, NULL)
```

Glibc version in system: `glibc-2.28-17.fc29.x86_64`

**Comment by bnoordhuis** [comment] 2018-11-16 11:09
Thanks for the report. It probably means `"xyzzy.xyzzy.xyzzy.` resolves to something on your system/network. That's not a bug as such (a libuv bug anyway) so I'll go ahead and close this out. Let me know if I should reopen.

**Closed by bnoordhuis** 2018-11-16 11:09 UTC

**Comment by bambuchaAdm** [comment] 2018-11-16 11:19
Confirm - on other network it pass without problems. I would think how this problem in test could be fixed. I was suspicious more in test rather then lib itself. Will dig in - thanks.
