### ISSUE TITLE
make check failed libuv 1.5.0

### ISSUE THREAD

**Issue by simon-sz** [libuv/libuv#346] opened 2015-05-08 06:56 UTC
[%  24|+  61|-   0|T   0|S   1]: tcp_oob
`tcp_oob` failed: exit code 6
Output from process `tcp_oob`:
Assertion failed in test/test-tcp-oob.c on line 59: nread > 0

======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [check-TESTS] 错误 1
make[1]: Leaving directory `/usr/local/risk4/RiskServer_test/include/libuv-1.5.0'
make: *** [check-am] 错误 2

**Comment by saghul** [comment] 2015-05-08 08:38
Duplicate of #258

**Closed by saghul** 2015-05-08 08:38 UTC
