### ISSUE TITLE
FreeBSD 10.1-release test failures

### ISSUE THREAD

**Issue by jbergstroem** [libuv/libuv#128] opened 2015-01-12 00:34 UTC
Below tests currently fails on Freebsd 10.1-release (64-bit):

- [ ] ipc_listen_before_write
- [ ] ipc_listen_after_write
- [ ] udp_dual_stack (ref #92, needs more work) 
- [ ] fs_event_watch_dir 

Fixed:
- [x] get_currentexe (ref #129)

```
=============================================================
[%  11|+  29|-   0|T   0|S   0]: ipc_listen_before_write
`ipc_listen_before_write` failed: exit code 134
Output from process `ipc_listen_before_write`:
got 6 bytes
Assertion failed in test/test-ipc.c on line 133: r == 0
=============================================================
[%  12|+  29|-   1|T   0|S   0]: ipc_listen_after_write
`ipc_listen_after_write` failed: exit code 134
Output from process `ipc_listen_after_write`:
got 6 bytes
Assertion failed in test/test-ipc.c on line 133: r == 0
=============================================================
[%  29|+  72|-   2|T   0|S   0]: udp_dual_stack
`udp_dual_stack` failed: exit code 134
Output from process `udp_dual_stack`:
Assertion failed in test/test-udp-ipv6.c on line 155: recv_cb_called == 1
=============================================================
[%  86|+ 212|-   3|T   0|S   0]: fs_event_watch_dir
`fs_event_watch_dir` failed: timeout
Output from process `fs_event_watch_dir`: (no output)
=============================================================
```
**Edit February 9, 2015: updating to match current status.**

**Comment by saghul** [comment] 2015-01-12 09:25
Since these failures affect FreeBSD only (OSX and Linux don't fail on those) I'd keep a single issue open.

I have a FreeBSD 10 VM and I could reproduce the failures. Some notes:

* udp_dual_stack is not skipped, which means there is IPv6 support and the test actually runs. Adding this to /etc/rc.conf makes the test pass: ipv6_ipv4mapping="YES"
* get_currentexe should be fixed by https://github.com/libuv/libuv/pull/129

**Comment by whitlockjc** [comment] 2015-08-18 21:47
I have fixed `fs_event_watch_dir` on FreeBSD 10 in #480.  Once it gets merged, I will update this issue so we can check it off the list.

**Comment by whitlockjc** [comment] 2015-08-18 23:18
I'm also seeing `spawn_setgid_fails` failing on FreeBSD 10.2.0 and 11.0-CURRENT.

**Comment by saghul** [comment] 2015-08-19 20:20
@whitlockjc did you run the tests as root by any chance? That test is quite sensible to the location of the test runner.

**Comment by whitlockjc** [comment] 2015-08-19 20:30
Nope, ran as a regular user.

**Comment by saghul** [comment] 2015-08-19 20:41
What directory? Does Mr. "nobody" have access to it? IIRC we setuid/setgid to that, which can cause trouble in some setups.

**Comment by whitlockjc** [comment] 2015-08-19 21:02
`/home/notyou/libuv`  Chances are good that `nobody` does not have access to that directory but this test runs fine on CentOS/OSX/SmartOS/... without that requirement too.

**Comment by santigimeno** [comment] 2015-09-02 20:59
I've been looking into the failures in `ipc_listen_before_write` and `ipc_listen_after_write` and the failures are caused by the particular behavior of `connect` in `FreeBSD`. Apparently in `FreeBSD` if `connect` is called and the queue of pending connections(`backlog`) is full, the call is automatically rejected with `ECONNRESET`. In the tests, `100` connections are tried and the backlog of both servers is `12`, so the error. I see different options for a fix:
- Don't abort on `ECONNRESET`.
- Decrease the number of connections.
- Increase the `backlog` of the servers.

What do you think?

**Comment by saghul** [comment] 2015-09-02 21:08
@santigimeno Thanks for looking into this! How about a combination of the last 2?

**Comment by whitlockjc** [comment] 2015-09-02 21:19
I think anything that could potentially require the user to change their environment to make the tests pass seems like more work, and it could possibly be obtrusive.  So number 3 to me does not seem ideal but I'm sure it could work along with some better test failure messages.  Number 2 seems ideal to me but I'm sure there is a fine line between testing with enough connections and not testing with too many.  So changing the number of connections alone might not be enough but would likely need some way to have the test runner specify the number of connections.  *(Imagine a user being able to pass in some environment variable or flag/option to set the connection count.)*  Even something like that would require better test failure messages.

**Note:** When I say *better test failure messages*, I'm just saying in known places where the environment configuration could cause a test to fail, we mention that in the test failure message with some link/text telling how to rerun the test or alter the configuration.

**Comment by santigimeno** [comment] 2015-09-02 21:28
@whitlockjc probably I'm missing something but what do you mean by "require the user to change their environment"? Is there anything in some of the proposed changes that provokes it?

**Comment by saghul** [comment] 2015-09-02 21:31
@whitlockjc The backlog refers to the parameter passed to `uv_listen`, if I'm understanding what @santigimeno means here, so there would be no need for adjusting the environment.

**Comment by santigimeno** [comment] 2015-09-02 21:32
Yes that's correct.

**Comment by santigimeno** [comment] 2015-09-02 21:36
BTW, I fail to understand why so many connections are needed in the tests. Any idea?

**Comment by saghul** [comment] 2015-09-02 21:37
@santigimeno TBH I don't know either. We should be fine with less of them too.

**Comment by santigimeno** [comment] 2015-09-02 22:05
PR:  https://github.com/libuv/libuv/pull/504

**Comment by whitlockjc** [comment] 2015-09-02 22:13
I'm an idiot, I crossed my wires.  Sorry for the noise.

**Comment by saghul** [comment] 2015-09-02 22:24
@whitlockjc no worries!

Since we're here, there is a failure which I could ever only see inside Jenkins:

~~~~
`tcp_create_early` failed: exit code 134
Output from process `tcp_create_early`:
Assertion failed in test/test-tcp-create-socket-early.c on line 126: memcmp(&addr.sin_addr, &sockname.sin_addr, sizeof(addr.sin_addr)) == 0
~~~~

Other tests fail for the same reason. I could never replicate it locally, even with the same version of FreeBSD. Any ideas anyone?

**Comment by santigimeno** [comment] 2015-11-12 14:21
@saghul I've been able to reproduce the Jenkins issues in my machine. In order to reproduce the failures, the tests have to be run in a jail that has not defined the `loopback`interface. The jail in Jenkins has *only* defined one network interface: 
```
name: vlan4093
internal: 0
physical address: 00:25:90:d5:8a:90
address: 172.16.31.2
netmask: 255.255.255.0
```
There's no `loopback` interface. This causes most of the failures. Adding the lo interface to the jail is simple. Just edit the jail config file and modify the `jail_$jailname_ip` variable. For example:
```
export jail_$jailname_ip="lo0|127.0.0.1,lo0|::1,vlan4093|172.16.31.2"
```
With this change, along with the change in https://github.com/libuv/libuv/pull/614, all the tests pass in my jail. Also, adding the IPv6 lo address prevents skipping the IPv6 tests.

**Comment by saghul** [comment] 2015-11-13 11:44
@santigimeno Wow, I would have not found that in a million years, thank you! @nodejs/build any chance the FreeBSD jails can be updated? Thanks!

**Comment by saghul** [comment] 2015-11-13 11:46
Hum, @-ing a team in another org might not work... /cc @rvagg @jbergstroem

**Comment by bnoordhuis** [comment] 2015-11-13 12:09
The freebsd buildbots have a LOCALHOST environment variable set with the loopback address.

**Comment by santigimeno** [comment] 2015-11-13 12:42
@bnoordhuis do you mean that the loopback address should be already available?

**Comment by bnoordhuis** [comment] 2015-11-13 12:56
Yes, the buildbots are supposed to set it when they run tests.  https://github.com/nodejs/node/blob/v5.0.0/test/common.js#L95-L116 is the relevant code in the node.js test runner.

**Comment by santigimeno** [comment] 2015-11-13 13:30
@bnoordhuis it seems this is not happening in the `libuv` job. The loopback address is not detected in the `platform_output` test. Also, the test failures correspond with not having the loopback interface defined.

**Comment by saghul** [comment] 2015-12-03 08:10
Closing since we now have a green build on FreeBSD. Thanks to everyone who made this possible :heart:

**Closed by saghul** 2015-12-03 08:10 UTC
