### ISSUE TITLE
Using libuv from C++ I get this error:

### ISSUE THREAD

**Issue by ftomassetti** [libuv/libuv#254] opened 2015-03-10 12:59 UTC
```
/usr/local/include/uv.h:649:12: error: conflicting types for 'uv_tty_set_mode'
inline int uv_tty_set_mode(uv_tty_t* handle, int mode) {
           ^
/usr/local/include/uv.h:642:15: note: previous declaration is here
UV_EXTERN int uv_tty_set_mode(uv_tty_t*, uv_tty_mode_t mode);
              ^
1 error generated.
```

**Comment by saghul** [comment] 2015-03-10 13:13
How are you compiling your code? Node / iojs are written in C++ and don't face this issue.

**Comment by txdv** [comment] 2015-03-10 13:55
Also the lines 642 and 649 do not contain anything whatsoever.

**Comment by txdv** [comment] 2015-03-10 14:00
This is it: https://github.com/txdv/libuv/blob/v1.x/include/uv.h#L641-L648

I don't understand why this is happening.

**Comment by saghul** [comment] 2015-03-10 14:02
That's some magic @bnoordhuis added to avoid a warning when compiling with C++, and keep the ABI backwards compatible, if memory serves right.

Lines are off by one, but that would be because we landed changes in that file.

**Comment by txdv** [comment] 2015-03-10 14:03
But, but Reviewed-By: Saúl Ibarra Corretgé <saghul@gmail.com>

**Comment by saghul** [comment] 2015-03-10 14:06
Yes, it does compile.

**Comment by txdv** [comment] 2015-03-10 14:15
The problem is that @ftomassetti  is setting _cplusplus is still using a C compiler.

You can see 2 methods with the same signature (uv_tty_set_mode) which a C++ compiler can distinguish based on the types the parameters take (overloading) but C doesn't since the the ABI in C is strictly only the function name and doesn't include the function parameter types.

**Comment by bnoordhuis** [comment] 2015-03-10 15:32
Someone else reported the same issue recently and IIRC the issue was indeed something somewhere defining `__cplusplus` without checking whether the compiler is actually a C++ compiler.  I don't think you can rightly blame libuv for failing to build under such conditions.

**Comment by saghul** [comment] 2015-03-11 07:57
Tentatively closing since it's not a libuv issue.

**Comment by kazuho** [comment] 2015-03-12 01:55
FYI the problem happens if you include `uv.h` within an `extern "C"` block.  For example,
```
extern "C" {
#include <uv.h>
}
```
will end in the reported compile error.

In other words, when using the recent versions of libuv, the users should not surround the `#include` line with `extern "C"`.

**Comment by saghul** [comment] 2015-03-12 08:41
@bnoordhuis thoughts?

**Comment by kazuho** [comment] 2015-03-12 11:35
Correction to my comment above:
> the commit has broken ABI compatibility (since there is no guarantee that sizeof(enum type) is equal to sizeof(int))

While it is theoretically true that ABI compatibility is not guaranteed in this case by the C/C++ specifications, whether it had actually broken the compatibility or not depends on each calling convention.  I am _not_ aware of any calling convention on a modern CPU that would be affected by this change (the only 32-bit CPU I am aware of that would get affected is 68k :-)).

Considering the fact, a better way to fix the issue might be to use `extern "c++"` as done in PR #265.

**Comment by saghul** [comment] 2015-03-18 10:33
#265 landed, closing! Thanks again, @kazuho

**Closed by saghul** 2015-03-18 10:33 UTC
