### ISSUE TITLE
Event loop ending early despite ref'ed handle

### ISSUE THREAD

**Issue by mscdex** [libuv/libuv#230] opened 2015-02-25 22:58 UTC
I have a poll handle that is monitoring a socket and every time I get notified of a requested event, I call `uv_poll_start()` with a possibly new event mask. However it seems that despite having called `Ref();` (from node's ObjectWrap) after creating the poll handle and even calling `uv_ref((uv_handle_t*)poll_handle);`, the event loop ends early because the poll handle became "inactive" after calling "uv_poll_start()` at the end of my processing function. I know the handle is still ref'ed because I examined the handle's internal flags property.

I found that if I return from my processing function before `uv_poll_start()` is called (e.g. backpressure is being applied and I need to stop processing for the time being), then everything works great.

This is with libuv 0.10.30/node 0.10.36.

**Comment by saghul** [comment] 2015-02-26 09:40
An inactive handle does not hold the loop  from exiting, even if it's ref'd, this is by design. Now, if a poll handle gets an error (ie, the callback gets called with status != 0), the poll handle is automatically stopped, so if it's the only handle around there is nothing preventing the loop from exiting.

**Comment by mscdex** [comment] 2015-02-26 14:50
Is there any way around this? Do I have to keep around a second ("fake") handle that is always active until I explicitly deactivate it?

**Comment by saghul** [comment] 2015-02-26 15:24
That's pretty much what you can do. An async handle would do, since they are always active and do nothing.

I've thought of adding a new mode to uv_run in the past: UV_RUN_FOREVER, but it would not help in this case.

**Comment by saghul** [comment] 2015-03-02 16:12
Closing since libuv behaves as advertised.

**Closed by saghul** 2015-03-02 16:12 UTC

**Comment by RealYukiSan** [comment] 2024-03-19 07:10
> I know the handle is still ref'ed because I examined the handle's internal flags property.
How do you examine the internal flags at runtime? I'd like to debug why the event loop exits early, but I have no idea where to start figuring it out. any suggestion @mcsdex ?

**Comment by RealYukiSan** [comment] 2024-03-19 07:34
@saghul wrote:
> An inactive handle does not hold the loop from exiting, even if it's ref'd, this is by design.

if the internal poll inside libuv not blocking or holding tcp connection, do I need an idle handle to prevent the loop from exiting?

I have tcp and stdin handles. If you'd like to take a look at my use case, here's the work-in-progress code: [client.c](https://github.com/RealYukiSan/chat_app/blob/master/client.c)

**Comment by bnoordhuis** [comment] 2024-03-19 09:04
> How do you examine the internal flags at runtime?

See `uv_print_all_handles()` and `uv_print_active_handles()` in uv.h. The flags are printed as `[RAI]`, meaning Referenced, Active, Internal.
