### ISSUE TITLE
Test failed: Assertion failed in test/test-getaddrinfo.c on line 43: status < 0

### ISSUE THREAD

**Issue by PrinceDhaliwal** [libuv/libuv#939] opened 2016-07-07 11:10 UTC
Here is the relevant information on running `make check`:
```
ok 171 - get_loadavg
ok 172 - handle_fileno
ok 173 - homedir
ok 174 - tmpdir
ok 175 - hrtime
not ok 176 - getaddrinfo_fail
# Output from process `getaddrinfo_fail`:
# Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
not ok 177 - getaddrinfo_fail_sync
# Output from process `getaddrinfo_fail_sync`: (no output)
ok 178 - getaddrinfo_basic
ok 179 - getaddrinfo_basic_sync
ok 180 - getaddrinfo_concurrent
ok 181 - getnameinfo_basic_ip4
```
I am using Ubuntu 16.04 - LTS. I ran the command twice but still the test failed.

**Comment by cjihrig** [comment] 2016-07-07 13:42
Does `xyzzy.xyzzy.xyzzy.` resolve to something on your system?

**Comment by saghul** [comment] 2016-07-07 14:23
This is a problem in your network. It returns something for the domain we made up for the test. There are a number of occurrences of this if you search through the issue tracker. Long story short: not a bug.

Closing.

**Closed by saghul** 2016-07-07 14:23 UTC
