### ISSUE TITLE
Delayed process exit when dns query is in progress

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#364] opened 2015-05-25 19:16 UTC
See https://github.com/joyent/node/issues/25349 for specific details. 

A process using libuv trying to exit will hang until dns resolution completes.  In the case of Node it was reported as occurring when process.exit(1) is called and a dns query is still running.

Opening to get input on whether trying to fix this in libuv makes sense.

**Comment by bnoordhuis** [comment] 2015-05-25 20:55
It's a known issue.  There is no good way to cancel the query except by killing the thread and that can lead to instability.

It might be possible to reap the thread with pthread_cancel() but then threads need to take great care to set PTHREAD_CANCEL_DISABLE whenever they do something that can lead to data loss (basically everything that is not transient.)

**Comment by mhdawson** [comment] 2015-05-25 21:00
In the process.exit case since the overall process is about to exit anyway, how about just leaving the threads running and avoiding cleaning up structures it may still touch ?  Its not pretty but would avoid delaying the exit process.

**Comment by bnoordhuis** [comment] 2015-05-25 21:02
That would lead to data loss if there are in-flight requests doing file operations.

**Comment by mhdawson** [comment] 2015-05-25 22:14
I guess the same (data loss) might be true if the user sends a SIGINT or SIGTERM as the default handlers don't wait for the threads to terminate.  

In the case of process.exit() one option would be document that it tries to exit as safely as possible and as a result a delayed exit might be possible.

Another option might be to only wait for threads if they are doing potentially unsafe operations but I can see that getting complicated.

**Comment by saghul** [comment] 2015-05-26 08:20
Duplicate of https://github.com/libuv/libuv/issues/203 ?

**Comment by bnoordhuis** [comment] 2015-05-26 09:33
Oh, indeed.  Forgot about that one.  Let's continue the discussion there.

**Closed by bnoordhuis** 2015-05-26 09:33 UTC
