### ISSUE TITLE
get_ibmi_physical_address can't handle when Qp2getifaddrs returns names longer than 10 characters

### ISSUE THREAD

**Issue by NattyNarwhal** [libuv/libuv#3062] opened 2020-12-03 17:04 UTC
Qp2getifaddrs seems to return on some systems the line names suffixed with... something (part of the IP? it's not consistent). These names are occasionally longer than 10 characters, which is the maximum name size in IBM i, and what the buffer is allocated for. The ASCII-to-EBCDIC conversion function then aborts because the buffer is too small for the conversion. With a sample program:

![line descs vs. sample program](https://user-images.githubusercontent.com/3161292/101061744-31e61d00-3567-11eb-98c8-66b4ed2007a7.png)

Stack trace in GDB:

![stack trace](https://user-images.githubusercontent.com/3161292/101061777-40343900-3567-11eb-9c99-16bdef75085e.png)

Sample program adapted from libuv source:

```
#include <stdio.h>
#include <net/if.h>
#include <arpa/inet.h>
#include <as400_protos.h>

int main(void)
{
  struct ifaddrs_pase *ifap = NULL, *cur;
  int inet6, r = 0;
  char ipaddr[INET_ADDRSTRLEN];
  if (Qp2getifaddrs(&ifap))
    return 1;  /* The second loop to fill in the array */
  for (cur = ifap; cur; cur = cur->ifa_next) {
    if (!(cur->ifa_addr->sa_family == AF_INET6 ||
          cur->ifa_addr->sa_family == AF_INET))
      continue;
    if (!(cur->ifa_flags & IFF_UP && cur->ifa_flags & IFF_RUNNING))
      continue;
    printf("Name: %s\n", cur->ifa_name);
    inet6 = (cur->ifa_addr->sa_family == AF_INET6);
    if (inet6) {
      inet_ntop(AF_INET6, &((struct sockaddr_in6*)cur->ifa_addr)->sin6_addr, ipaddr, INET_ADDRSTRLEN);
      printf("IPv6: %s\n", ipaddr);
    } else {
      inet_ntop(AF_INET, &((struct sockaddr_in*)cur->ifa_addr)->sin_addr, ipaddr, INET_ADDRSTRLEN);
      printf("IPv4: %s\n", ipaddr);
    }
    printf("Flags: %x\n", cur->ifa_flags);
  }
  Qp2freeifaddrs(ifap);
  return r;
}
```

It was noticed trying to run npm, but in Node, `os.networkInterfaces` is enough to surface the crash.

* **Version**: vendored in nodejs12
* **Platform**: IBM i 7.2

**Comment by ThePrez** [comment] 2020-12-03 17:53
cc @libuv/ibmi

**Comment by kadler** [comment] 2020-12-03 18:02
Looks like potentially a bug in SLIC. It goes through great lengths to ensure the name is null terminated, but then does a memcpy of the length without the null terminator. SLIC does return a field with the name length, though, so we could work around the issue by using that length. Of course, Qp2getifaddrs wraps the SLIC code and does some processing on it, so I'm not yet sure if that field makes it through. If not, we could at least limit it to 10 characters, since that's the max of a line description name, though that may still not be correct if the name is less than 10 (but at least we wouldn't abort())

**Comment by kadler** [comment] 2020-12-03 19:18
Ok, looks like that length field does not make its way to the caller of Qp2getifaddrs, so we need a SLIC fix here.

**Comment by kadler** [comment] 2020-12-03 19:59
@NattyNarwhal I've let the SLIC team know about the issue, but you should open a ticket with IBM support so that we can get investigate further, get an APAR opened, and get a test fix. FWIW, I've been unable to recreate this issue internally, so I suspect there's more to it than I initially expected.

**Comment by kadler** [comment] 2020-12-03 20:01
We can leave this issue open so that we can investigate if a workaround is possible/needed.

**Comment by NattyNarwhal** [comment] 2020-12-24 22:15
Not stale, blocking on something else.

**Comment by zheddie** [comment] 2021-01-27 05:11
@NattyNarwhal , I found that the ifa_name is just a char * pointer, it didn't have a fixed length. Can you show me where's length 10 is defined. I know the "line description" on IBM i has max length as 10, but not sure why ifa_name MUST be the same as line description.  So, we need to know what's the exact ifa_name you got on your system? Of course, before you move it to any string with  a fixed length. thx.

**Comment by NattyNarwhal** [comment] 2021-01-27 18:32
I'm not sure what you mean, while `Qp2getifaddrs` (and certainly the `getifaddrs` it's close enough to) doesn't have to return a line description name, it should, or things that expect 10-character line description names like [the code that gets physical addresses from a line description](https://github.com/libuv/libuv/blob/v1.x/src/unix/ibmi.c#L318) will break.

The exact `ifa_name` values I got were in the first screenshot of the original post.

**Comment by zheddie** [comment] 2021-01-28 02:30
oh. I see. So, the issue is the ifa_name returned here includes the virtual line id.Based on the SLIC guys' explain, this is as design. The ifa_name include the line description and the VLAN ID, when it's not *NONE. So, the length can not be expected to be 10.

**Comment by kadler** [comment] 2021-01-28 03:08
Yeah, this seems to be a bug in libuv then. We'll have to adjust the code to handle this length and remove the assertion

I suspect we'll have to strip off the VLAN ID prior to calling QDCRLIND. I'm not sure how simple this is. If line descriptions cannot contain periods, then it's easy enough to find the period and truncate it there. If line descriptions can contain periods, this will be much more difficult to determine.

The other question is do we remove the VLAN ID from the name returned by `uv_interface_addresses`? I think it does make sense here, since you really should have a unique id for the VLAN interface and seems to follow the convention I've found looking at Linux and FreeBSD examples.

**Comment by GautierFR** [comment] 2021-02-22 13:38
Hi, 
we have this issue open (initial issue open for us) and we confirm that the issue persist even in V7R4 OS/400. 
Do you have a feedback / fix available from your previous posts? 

Thank you.

**Comment by kadler** [comment] 2021-02-23 22:20
>  If line descriptions cannot contain periods, then it's easy enough to find the period and truncate it there. If line descriptions can contain periods, this will be much more difficult to determine.

Interface names are based on the line description name and line descriptions are objects so yes, periods are allowed in their names (along with other special characters).

I think we'll need to do something like the XPF ioctl API does:

https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/apis/ioctl.htm

> 4
> The interface (line description) name has been extended to allow a VLAN ID to be appended for SIOCGIFLIND, SIOCADDRT6, and SIOCDELRT6. To specify a particular interface with a VLAN ID, append a dot followed by the VLAN ID (1 to 4094 inclusive) to the end of the interface name ( "linename.vlanid").
>
> If any interface name contains a dot the following convention will be used:
>
>    The whole string, including the dot, will initially be treated as the interface name.
>    If no such interface exists, all characters following the last dot will be treated as a VLAN ID.
>
> For example vethline.1 will initially look for the interface 'vethline.1'. If this interface does not exist, it will look for the interface 'vethline' with a VLAN ID of 1.

I think we'd do something like this:

```
if name_len <= 10
  // Try passing name to QDRLIND
if name_len > 10 or error
  // Strip off trailing VLAN ID and pass to QDRLIND
```

The name buffer needs to be increased to at least 16: object name (10), dot, vlan id (4 for 4094), null terminator.

We also need to handle errors better. Aborting due to an assertion failure is not a valid way to handle errors like this. If we encounter an error trying to get the MAC address, we should return a dummy/NULL MAC address or an error return code.

**Comment by kadler** [comment] 2021-02-26 19:03
@dmabupt can you work on a fix for this? I'm quite busy at the moment with other projects.

At a minimum, we could start by changing the code to use a 16-byte buffer for the interface name and removing the abort (easiest fix here is if the srclen is greater than the target len, set srclen to target len). This would at least prevent `npm` from aborting. We'd still have the issue of not retrieving a correct MAC address for VLAN interfaces, but I don't think `npm` actually cares what the MAC address is - it's just a byproduct of how Node.js retrieves interface details.

**Comment by NattyNarwhal** [comment] 2021-02-26 19:06
This is the preliminary workaround I had:

```diff
diff --git a/src/unix/ibmi.c b/src/unix/ibmi.c
index 96efc02b..afaab471 100644
--- a/src/unix/ibmi.c
+++ b/src/unix/ibmi.c
@@ -317,13 +317,25 @@ static int get_ibmi_physical_address(const char* line, char (*phys_addr)[6]) {
   unsigned int rcvrlen = sizeof(rcvr);
   unsigned char format[8], line_name[10];
   unsigned char mac_addr[sizeof(rcvr.loca_adapter_address)];
+  char *line_without_vlan, *first_dot;
   int c[6];
 
   /* format is input parameter 3 to QDCRLIND */
   iconv_a2e("LIND0500", format, sizeof(format));
 
-  /* line_name is input parameter 4 to QDCRLIND */
-  iconv_a2e(line, line_name, sizeof(line_name));
+  /* we may get VLAN ID with line name, so truncate it if possible */
+  line_without_vlan = strdup(line);
+  if (line_without_vlan != NULL) {
+    first_dot = strchr(line_without_vlan, '.');
+    if (first_dot != NULL)
+      *first_dot = '\0';
+
+    /* line_name is input parameter 4 to QDCRLIND */
+    iconv_a2e(line_without_vlan, line_name, sizeof(line_name));
+    free(line_without_vlan);
+  } else {
+    iconv_a2e(line, line_name, sizeof(line_name));
+  }
 
   /* err is input parameter 5 to QDCRLIND */
   errcode_s err;
```

Not well tested. It doesn't blow up on my system, but no idea if it fixes the person's original issue. (Getting them to try it.)

**Comment by kadler** [comment] 2021-02-26 19:12
Unfortunately, that change would break retrieving info for interfaces whose names contain a dot, eg. "MY.ETHLINE"

**Comment by NattyNarwhal** [comment] 2021-02-26 19:20
I guess strrchr would probably be the actual fix then. Nor does this fix the aborts either...

**Comment by kadler** [comment] 2021-02-26 19:31
`strrchr` could be used, for sure. Wouldn't even need to iconv it twice but pass an EBCDIC period (0x4b) as the char to look for

**Comment by NattyNarwhal** [comment] 2021-02-26 19:34
I guess the difficulty is figuring out if it's a VLAN ID. If it's over 10 characters, it almost certainly is, but it's hard to tell if it had the VLAN ID appended while being within bounds without some signalling that it has one.

**Comment by kadler** [comment] 2021-02-26 19:57
Correct, there's no way to _know_. We can only go on heuristics and assumptions. I outlined a mechanism in pseudocode based on what the XPF ioctls do.

Basically:

1. Names over 10 characters long _must_ contain a VLAN ID (or somehow we got back invalid data from Qp2getifaddrs)
2. Names 10 or under which do not contain a dot _must not_ contain a VLAN ID
3. Names 10 or under which contain a dot _may_ contain a VLAN ID. Assume it doesn't and if you get an error, try it again with the VLAN ID stripped off

Now, number 3 could be improved by checking if the character after the dot is a numeric character (ASCII 0xC0-0xC9, EBCDIC 0xF0-0xF9), but no matter what you're going to have issues if you have both an interface named eg. ETH (with VLAN ID 2) and ETH.2 since in either case Qp2getifaddrs returns "ETH.2" as the name. I don't think there's anything that can be done here without the OS changing its behavior.

**Comment by NattyNarwhal** [comment] 2021-02-26 20:18
So something like (excluding the checking the numerics afterward):

```
diff --git a/src/unix/ibmi.c b/src/unix/ibmi.c
index 96efc02b..b55ade03 100644
--- a/src/unix/ibmi.c
+++ b/src/unix/ibmi.c
@@ -317,13 +317,25 @@ static int get_ibmi_physical_address(const char* line, char (*phys_addr)[6]) {
   unsigned int rcvrlen = sizeof(rcvr);
   unsigned char format[8], line_name[10];
   unsigned char mac_addr[sizeof(rcvr.loca_adapter_address)];
+  char *line_without_vlan, *last_dot;
   int c[6];
 
   /* format is input parameter 3 to QDCRLIND */
   iconv_a2e("LIND0500", format, sizeof(format));
 
-  /* line_name is input parameter 4 to QDCRLIND */
-  iconv_a2e(line, line_name, sizeof(line_name));
+  /* we may get VLAN ID with line name, so truncate it if possible */
+  line_without_vlan = strdup(line);
+  if (line_without_vlan != NULL && strlen(line) > 10) {
+    last_dot = strrchr(line_without_vlan, '.');
+    if (last_dot != NULL)
+      *last_dot = '\0';
+
+    /* line_name is input parameter 4 to QDCRLIND */
+    iconv_a2e(line_without_vlan, line_name, sizeof(line_name));
+    free(line_without_vlan);
+  } else {
+    iconv_a2e(line, line_name, sizeof(line_name));
+  }
 
   /* err is input parameter 5 to QDCRLIND */
   errcode_s err;
```

It would at least mitigate the crashes.

As for other ideas, if there's nothing in the flags, what about the functions Qp2getifaddrs is calling behind the scenes? Would it flag if it had to return a VLAN ID?

**Comment by mlitters** [comment] 2021-02-26 21:19
Hi Calvin,
many thanks for your Workaround. I will try that - we have the same error on a customers system. 

@kadler  I am not sure if the problem is a SLIC topic as you mentioned above or is it a libuv problem or is it a mix?
If it is an IBM i / SLIC Problem is there an open ticket? 
Many thanks for your work!

**Comment by NattyNarwhal** [comment] 2021-03-01 15:13
The workaround patch I posted earlier seems to work; it's just a matter of handling edge cases, it seems.

**Comment by DavidRusso** [comment] 2021-03-09 21:37
I have a customer who is running Node 10.24.0 on IBM i. On their system, they get an error like this when trying to run `os.networkInterfaces()`:

```
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 2 (Unknown system error 2)
--
at Object.networkInterfaces (os.js:198:30)
```
On my test system it works fine with the same Node version. 

The error message is different than shown above, but I'm wondering if this could be the same issue?

**Comment by kadler** [comment] 2021-04-08 16:35
> The error message is different than shown above, but I'm wondering if this could be the same issue?

This issue is about a crash that occurs when the interface name is greater than 10 due to a VLAN ID suffix, so it's not directly the same. However, the issue could be due to the code not handling VLANs properly at all and interface names that contain a VLAN ID and still less <= 10 characters would not trigger the crash, but still not work properly. In that case, uv_interface_addresses will return the rc returned by calling `get_ibmi_physical_address` even though it does retrieve the interfaces (just with possibly all-zeroes for the MAC address).

**Comment by kadler** [comment] 2021-04-09 18:01
FYI, we've applied my patch from #3144 to our internal builds and they're rolling out today. Node 12 is already public, while Node 10 should be in an hour and Node 14 in a few hours. You may need to run `yum clean metadata` before running `yum upgrade` to see these updates.

**Closed** 2021-04-28 15:53 UTC
Labels: ibmi
