### ISSUE TITLE
VS2008 Linking Errors with Static libuv Library

### ISSUE THREAD

**Issue by 2ix** [libuv/libuv#553] opened 2015-09-29 02:48 UTC
Created a `static library` build with `vcbuild.bat debug x86 static`.
Created a Win32 Console Application in VS2008 not using pre-compiled headers.
Additional Include Directory `libuv\include`.
Additional Library Directory `libuv\Debug\lib`.
Additional Dependency `libuv.lib`.

```
#include <uv.h>

int main(int argc, char *argv[])
{
  uv_loot_t *loop = uv_default_loop();
  return 0;
}
```

When building I see many linking errors for example `LNK 2005: _exit already defined in MSVCRTD.lib (MSVCR90D.dll)` and further down `LNK2001: unresolved external symbol...` in libuv.lib.

I'm not sure what is wrong as I have set the appropriate include/library/dependency in VS2008.

Please, any suggestions?

**Comment by saghul** [comment] 2015-09-29 08:01
Was libuv also compiled with VS 2008? Can you check what runtime libuv was linked with, using Dependency Walker?

**Comment by 2ix** [comment] 2015-09-29 09:48
@saghul Yes compiled with VS 2008. I have also opened the solution and compiled it directly in VS 2008 too.

**Comment by saghul** [comment] 2015-09-29 09:52
Are you linking your project with these? https://github.com/libuv/libuv/blob/v1.x/uv.gyp#L115

**Comment by 2ix** [comment] 2015-09-29 10:05
Nope, I will try that and let you know. Thank you :)

**Comment by saghul** [comment] 2015-09-29 10:07
You have to link with those, libuv uses symbols from there.

**Comment by 2ix** [comment] 2015-09-29 22:27
@saghul Errors still occurring after linking with the additional libraries. No link errors with libuv directly but still see the `LNK 2005: _exit already defined in MSVCRTD.lib` and other already defined errors.

**Comment by saghul** [comment] 2015-09-29 22:29
Can you paste the errors you get, the list of libraries you currently link with and a screenshot of dependency walker?

**Comment by 2ix** [comment] 2015-09-29 22:34
```
1>Linking...
1>LIBCMTD.lib(crt0dat.obj) : error LNK2005: _exit already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(crt0dat.obj) : error LNK2005: __exit already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(crt0dat.obj) : error LNK2005: __cexit already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(crt0dat.obj) : error LNK2005: __amsg_exit already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(crt0dat.obj) : error LNK2005: __initterm_e already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(invarg.obj) : error LNK2005: __invoke_watson already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(invarg.obj) : error LNK2005: __set_invalid_parameter_handler already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(dbgheap.obj) : error LNK2005: __CrtSetCheckCount already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(tidtable.obj) : error LNK2005: __encode_pointer already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(tidtable.obj) : error LNK2005: __decode_pointer already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(crt0init.obj) : error LNK2005: ___xi_a already defined in MSVCRTD.lib(cinitexe.obj)
1>LIBCMTD.lib(crt0init.obj) : error LNK2005: ___xi_z already defined in MSVCRTD.lib(cinitexe.obj)
1>LIBCMTD.lib(crt0init.obj) : error LNK2005: ___xc_a already defined in MSVCRTD.lib(cinitexe.obj)
1>LIBCMTD.lib(crt0init.obj) : error LNK2005: ___xc_z already defined in MSVCRTD.lib(cinitexe.obj)
1>LIBCMTD.lib(hooks.obj) : error LNK2005: "void __cdecl terminate(void)" (?terminate@@YAXXZ) already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(winxfltr.obj) : error LNK2005: __XcptFilter already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(dbghook.obj) : error LNK2005: __crt_debugger_hook already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(setlocal.obj) : error LNK2005: __configthreadlocale already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(sprintf.obj) : error LNK2005: _sprintf already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(crt0.obj) : error LNK2005: _mainCRTStartup already defined in MSVCRTD.lib(crtexe.obj)
1>LIBCMTD.lib(errmode.obj) : error LNK2005: ___set_app_type already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(mlock.obj) : error LNK2005: __lock already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(mlock.obj) : error LNK2005: __unlock already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(dosmap.obj) : error LNK2005: __errno already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(dosmap.obj) : error LNK2005: ___doserrno already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(dbgrptt.obj) : error LNK2005: __CrtSetReportHook already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(dbgrptw.obj) : error LNK2005: __CrtDbgReportW already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(wcstombs.obj) : error LNK2005: _wcstombs already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(atox.obj) : error LNK2005: _atoi already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(getenv.obj) : error LNK2005: _getenv already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(_file.obj) : error LNK2005: ___iob_func already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(osfinfo.obj) : error LNK2005: __get_osfhandle already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(osfinfo.obj) : error LNK2005: __open_osfhandle already defined in MSVCRTD.lib(MSVCR90D.dll)
1>LIBCMTD.lib(abort.obj) : error LNK2005: _abort already defined in MSVCRTD.lib(MSVCR90D.dll)
1>MSVCRTD.lib(ti_inst.obj) : error LNK2005: "private: __thiscall type_info::type_info(class type_info const &)" (??0type_info@@AAE@ABV0@@Z) already defined in LIBCMTD.lib(typinfo.obj)
1>MSVCRTD.lib(ti_inst.obj) : error LNK2005: "private: class type_info & __thiscall type_info::operator=(class type_info const &)" (??4type_info@@AAEAAV0@ABV0@@Z) already defined in LIBCMTD.lib(typinfo.obj)
1>LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
1>LINK : warning LNK4098: defaultlib 'LIBCMTD' conflicts with use of other libs; use /NODEFAULTLIB:library
```

```
libuv.lib
advapi32.lib
iphlpapi.lib
psapi.lib
shell32.lib
userenv.lib
ws2_32.lib
```

Not sure how to get a screenshot as the executable never builds?

**Comment by saghul** [comment] 2015-09-29 22:39
Ah, right!

I'm not very sure what's wrong. Maybe @piscisaureus or @orangemocha can spot it?

**Comment by 2ix** [comment] 2015-09-29 22:43
@saghul I think I've got it, the test described in the OP is working. The application I'm writing is building a shared library using libuv's static library and I had to change the `Code Generation` option in libuv to match.

Do you think it would be a good idea to have vcbuild.bat accept an argument such as `dll` to automagically set this option in the future too? Eg: `vcbuild.bat debug x86 static dll`

**Comment by saghul** [comment] 2015-12-14 20:30
Closing. We don't support building libuv that way, it seems. Now, if you're embedding libuv in your project you could probably build it manually calling gyp_uv.py instead of using vcbuild.bat.

**Closed by saghul** 2015-12-14 20:30 UTC

**Comment by iceonsun** [comment] 2018-05-07 08:36
For anyone who has problem:

`error LNK2019: unresolved external symbol __CrtSetReportHook referenced in`

The problem is same as rynz described.

Only need to compile uv to dynamic library. The default is static.
