### ISSUE TITLE
x/os failures

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#2196] opened 2019-02-20 20:26 UTC
* **Version**: 1.x
* **Platform**:z/OS

Probably should have opened this in this repo, but at least so people know we are working on it:

https://github.com/nodejs/build/issues/1685

**Comment by richardlau** [comment] 2019-02-20 20:33
Duplicate of https://github.com/libuv/libuv/issues/2183.

**Comment by bnoordhuis** [comment] 2019-02-21 11:17
Yep, closing as duplicate. Nice to know it's being worked on though.

**Closed by bnoordhuis** 2019-02-21 11:17 UTC
Labels: duplicate
