### ISSUE TITLE
uv_fs_read() result is not equals preadv().

### ISSUE THREAD

**Issue by osom8979** [libuv/libuv#2332] opened 2019-06-14 00:43 UTC
* **Version**: 1.29.1
* **Platform**: Darwin MacBookPro.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

Updated from version 1.22.0 to version 1.29.1

In the documentation, `uv_fs_read()` guarantees the same behavior as `preadv()`, but the result is not.

It worked fine in 1.22.0, but not in 1.29.1.

In `uv__fs_read()`, if `HAVE_PREADV` is `0`, it is seen as a result of calling the `pread()` function.

Test code:
```cpp
uv_buf_t buf[2];
// assign buf[0] & buf[1]
uv_fs_t req = {0,};
int const READ_SIZE = uv_fs_read(nullptr, &req, f, buf, 2, 0, nullptr);
uv_fs_req_cleanup(&req);
```

**Comment by vtjnash** [comment] 2019-06-14 03:22
Can you say more about the discrepancy you see? The expected correct behavior for your test snippet is for some part of `buf[0]` to be filled (just like using preadv directly could do, if it was provided). There was a significant bug fix I landed recently which should have corrected some issues with larger or interrupted reads (previously it might have only filled part of `buf[0]` and might also fill part of `buf[1]`). Just as posix specifies for `read`, your application is required to handle any short reads.

**Comment by osom8979** [comment] 2019-06-15 00:35
The return value of the function is different.

```c
char buf1[5+1] = {0,};
char buf2[10+1] = {0,};
struct iovec buf[2];
buf[0].iov_base = buf1;
buf[0].iov_len = 5;
buf[1].iov_base = buf2;
buf[1].iov_len = 10;
int f = open("test.c", O_RDONLY);
ssize_t result = preadv(f, buf, 2, 0); // check the 'result' variable.
close(f);
```

If the `test.c` file is large enough, the value of `result` is expected to be `15`.

However, if `uv_fs_read()` is used, `5` is returned.

----

Are you saying 'significant bug fix' is the this commit? : https://github.com/libuv/libuv/commit/19a341919546140c37834488e1f7c46721b0d2d5

If so, my thoughts on 'correct behavior' are like 'Equivalent to preadv(2)'. (same as documentation)

This is not the 'expected internal behavior' of `preadv()`.

This is independent of the 'read interruption' caused by the library's internal circumstances reflected in the return value.

If this situation needs to be maintained, it should be reflected in the document.

**Comment by bnoordhuis** [comment] 2019-06-16 12:59
It's a libuv bug. The fallback path for when no preadv() is available only considers the first buffer. I'll open a pull request with a bug fix later today or tomorrow.

**Comment by vtjnash** [comment] 2019-06-18 14:40
FWIW, libuv is following the spec for `preadv` precisely already. This is not a bug in libuv (although we can still change our emulation behavior), but a bug in the application, as it can happen even if we aren't emulating `preadv`:
"Note that readv is not guaranteed to fill all the buffers. It may stop at any point, for the same reasons read would." and "It is not an error if this number is smaller than the number of bytes requested".

For systems which have `preadv` (so our emulation isn't in use anyways), I'd say that the most common reason I see for a short-read to happen is the delivery of the SIGCHLD signal, although SIGALARM can also be a cause in some applications.

**Closed** 2019-06-20 10:08 UTC
